In [82]:
# p1[['Company Name', 'Legal Name / ACRA UEN', 'Commodity Focus', 'HQ Country','APAC Offices','Notes']]
# pillar2['Known Client Base'], names from p2['Notable Cases / Disputes'], url in pillar2['Notes']
# pillar3['Known Clients'], url in p3['Notes']

In [83]:
import pandas as pd

# display columns without truncation
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

# display rows without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.expand_frame_repr", False)

In [188]:
# read 3 pillars
p1 = pd.read_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar1.csv", encoding="utf-8")
p2 = pd.read_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar2.csv", encoding="utf-8")
p3 = pd.read_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar3.csv", encoding="utf-8")

In [199]:
# pillar 1 legal names
# combine 3 columns in pillar 1
df1 = p1['Legal Name / ACRA UEN'].copy()
# remove brackets from legal name col 
df1= df1.str.replace(r"[\(\[].*?[\)\]]", "", regex=True).str.strip()

#remove the UEN
import re
def strip_uen(cell):
    if not isinstance(cell, str) or not cell.strip():
        return cell
    # remove everything from the slash onward (the UEN number/code)
    # handles inconsistent spacing before/after the slash
    return re.sub(r"\s*/\s*[A-Za-z0-9]+\s*", "", cell).strip()

df1 = df1.apply(strip_uen)

#rename to Firm name
df1.name = 'Firm Name'
df1

0                                       TRAFIGURA GROUP PTE. LTD.
1                                             VITOL ASIA PTE LTD.
2                                    MERCURIA HOLDINGS  PTE. LTD.
3                                      GUNVOR SINGAPORE PTE. LTD.
4                            LOUIS DREYFUS COMPANY ASIA PTE. LTD.
5                                    WILMAR INTERNATIONAL LIMITED
6                                              OLAM GROUP LIMITED
7                         COFCO INTERNATIONAL SINGAPORE PTE. LTD.
8                         CARGILL ASIA PACIFIC HOLDINGS PTE. LTD.
9                                    GLENCORE SINGAPORE PTE. LTD.
10                     ARCHER-DANIELS-MIDLAND SINGAPORE PTE. LTD.
11                                           BUNGE ASIA PTE. LTD.
12                                           MARUBENI CORPORATION
13                                        MITSUI & CO.  PTE. LTD.
14                            PTT INTERNATIONAL TRADING PTE. LTD.
15                                     SHELL EASTERN TRADING  LTD
16                                        BP ASIA PACIFIC PTE LTD
17     TOTALENERGIES MARKETING ASIA-PACIFIC MIDDLE EAST PTE. LTD.
18                            SINOCHEM INTERNATIONAL OIL  PTE LTD
19                                 AGROCORP INTERNATIONAL PTE LTD
20                              GOLDEN AGRI INTERNATIONAL PTE LTD
21                                   MUSIM MAS HOLDINGS PTE. LTD.
22                                        FIRST RESOURCES LIMITED
23                                   AAVANTI INDUSTRIES PTE. LTD.
24                                     OLAM AGRI HOLDINGS LIMITED
25                                     GERALD SINGAPORE PTE. LTD.
26                                     PACIFIC BASIN SG PTE. LTD.
27                                         WILMAR SUGAR PTE. LTD.
28                          SAHARA ENERGY INTERNATIONAL PTE. LTD.
29                                SOCAR Trading Singapore Pte Ltd
30                                WOGEN SOUTH EAST ASIA PTE. LTD.
31                                     TRAXYS SINGAPORE PTE. LTD.
32                             TRAFIGURA CARBON TRADING PTE. LTD.
33                                                  IXM PTE. LTD.
34                         Aditya Birla Global Trading  Pte. Ltd.
35                          Tata International Singapore Pte Ltd.
36                                       VINMAR OVERSEAS  PTE LTD
37                                            HELM ASIA Pte. Ltd.
38                                 SINO GAS HOLDINGS PTE. LIMITED
39                        POSCO INTERNATIONAL SINGAPORE PTE. LTD.
40                                           OILMAR SGP PTE. LTD.
41                                   NALA RENEWABLES PTE. LIMITED
42                                   Straits Energy Resources Bhd
43                                   INDOFOOD AGRI RESOURCES LTD.
44                                 ADARO INTERNATIONAL  PTE. LTD.
45                                 HG METAL MANUFACTURING LIMITED
46                               SD Guthrie International Limited
47                                           AGREX ASIA PTE. LTD.
48                                    LX_INTERNATIONAL  PTE. LTD.
49                        HYUNDAI CORPORATION SINGAPORE PTE. LTD.
50              WOODSIDE ENERGY AUSTRALIA ASIA HOLDINGS PTE. LTD.
51                                SAMSUNG C&T SINGAPORE PTE. LTD.
52                                    SINOPEC FUEL OIL  PTE. LTD.
53                                          SOJITZ ASIA PTE. LTD.
54                  SUMITOMO CORPORATION ASIA & OCEANIA PTE. LTD.
55                                    CITIC COMMODITIES PTE. LTD.
56                            PETROCHINA INTERNATIONAL  PTE. LTD.
57                                     UNIPEC SINGAPORE PTE. LTD.
58                               Sinopec International  Pte. Ltd.
59                              SK ENERGY INTERNATIONAL PTE. LTD.
60                                       ITOCHU Singapore Pte Ltd
61                                  GS GLOBAL SINGAPORE PTE. LTD.
62                              CIPTA COMMODITY TRADING PTE. LTD.
63                                    DAVIS COMMODITIES PTE. LTD.
64                                          OM MATERIALS  PTE LTD
65              BANPU MINERALS  PTE LTD, BANPU SINGAPORE PTE LTD.
66                             HD HYUNDAI OIL SINGAPORE PTE. LTD.
67                           TOYOTA TSUSHO ASIA PACIFIC PTE. LTD.
68                             CHALCO TRADING SINGAPORE PTE. LTD.
69                                      SHELL SINGAPORE PTE. LTD.
70                            SUMMIT ENERGY & RESOURCES PTE. LTD.
71      Pertamina International Marketing & Distribution Pte. Ltd
72                              Idemitsu International  Pte. Ltd.
73                              ENEOS OIL & ENERGY ASIA PTE. LTD.
74                              COSMO OIL INTERNATIONAL PTE. LTD.
75                                          JFE SHOJI CORPORATION
76                         CENTURY COMMODITIES SOLUTION PTE. LTD.
77                                   RAWSTEEL MINMETALS PTE. LTD.
78                             GCE Agri; GCE BUSINESS CONSULTANTS
79                                   DKC STEEL SINGAPORE PTE LTD.
80                                             MRI Group Pte. Ltd
81                                       UNIFOOD INT'L  PTE. LTD.
82                        NOBLE RESOURCES INTERNATIONAL PTE. LTD.
83                                        Cemcoa Energy Pte. Ltd.
84                              INTERCHEM MANUFACTURING PTE. LTD.
85              Mitsubishi Corporation RtM International Pte Ltd.
86                                      AAA OILS & FATS PTE. LTD.
87                             TRILAND METALS SINGAPORE PTE. LTD.
88                                     GINGA PETROLEUM  PTE LTD /
89                                         CONCORD ENERGY PTE LTD
90                                        Pacific Minerals Ltd: n
91                                                        Unknown
92                                 KZ TRADING SINGAPORE PTE. LTD.
93                                   PETRACO OIL COMPANY PTE LTD.
94                            THE STRAITS INTERNATIONAL PTE. LTD.
95                                    STRAITS BUNKERING PTE. LTD.
96                                       PACIFIC ENERGY PTE. LTD.
97                                      QUANTUM GLOBAL  PTE. LTD.
98                                    MERIDIAN EQUITIES PTE. LTD.
99                           SWAN INTERNATIONAL HOLDING PTE. LTD.
100                                         Bary Chemical Pte Ltd
101           ORIENTAL ENERGY PTE LTD& ORIENTAL RESOURCES PTE LTD
102                                       BARY CHEMICAL PTE. LTD.
103                                 MAHKOTA OILS & FATS PTE. LTD.
Name: Firm Name, dtype: str

In [190]:
# p2 known client base
df2 = p2[['Firm Name','Known Client Base', 'Notable Cases / Disputes']].copy()
df2

# 0: Uniper Global Commodities SE Singapore Branch, China Merchants Energy Shipping (Singapore) Holding Pte. Ltd., Sinopec
# 1: BGN Energy, Gunvor Group, Uniserve Pte. Ltd, Technip Energies Singapore Pte. Ltd, Abu Dhabi Commercial Bank
# 2: ED&F Man Capital Markets (Singapore) Pte. Ltd., Lendlease Singapore Pte Ltd / Lendlease REIT, Citigroup / Citi Singapore, Jaguar Land Rover Singapore Pte. Ltd.
# 3: Trafigura, PSA International, Olam International, ICICI Bank Singapore Branch
# 4: Trafigura, BW Energy Holdings Pte Ltd, HSBC Singapore entities
# 5: Glory Bulk Carriers Pte Ltd, TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd., Trafigura Group Pte. Ltd, Seacon Shipping’s Singapore entities, Clearlake Shipping
# 6: Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore
# 7: Shell Singapore Pte. Ltd
# 8: nan
# 9: Star Academies
# 10: nan
# 11: Ocean Network Express Pte. Ltd.
# 12: Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd, Neptune Associated Shipping Pte Ltd
# 13: JSW International Tradecorp Pte Ltd (JSW), ST Telemedia Global Data Centres (Telemedia Global Data Centres), BTS Tankers Pte Ltd, DBS Bank, United Overseas Bank (UOB), Oversea-Chinese Banking Corporation (OCBC)
# 14: Resources Prima Group Ltd, Metro Holdings Limited, Razer, Eagle Hospitality Trust, ST Marine Ltd (Singapore Technologies Marine), O.W. Bunker Far East (Pte) Ltd, Dynamic Oil Trading (Singapore) Pte Ltd
# 15: First Resources Limited, First Sponsor Group Limited, DBS, Seatrium
# 16: United Overseas Bank (UOB), Straits Bunkering Pte Ltd
# 17: Avani Resources Pte. Ltd, Alvari Pte. Ltd.
# 18: BAFCO Singapore Pte. Ltd, The Singapore Medical Council (SMC)
# 19: FTI Consulting (Singapore) Pte. Ltd.
# 20: Oversea-Chinese Banking Corporation (OCBC), Boustead Projects Limited, Thomson Medical Group (TMG)
# 21: OCBC Bank (Oversea-Chinese Banking Corporation Limited), Winson Oil Trading Pte Ltd
# 22: Louis Dreyfus Company Asia Pte. Ltd.
# 23: Standard Chartered Bank (Singapore) Limited (SCB)
# 24: Halcyon Agri Corporation Limited, Seraya Energy, Century Holdings Pte. Ltd, KPMG, Mizuho Bank, Perennial Real Estate Holdings, Ho Lee Construction, WestBridge Ventures II Investment Holdings
# 25: Standard Chartered Bank (Singapore) Limited
# 26: Atlantic Navigation Holdings (Singapore) Limited, Royal Global Exports Pte Ltd
# 27: Louis Dreyfus Asia Pte Ltd / Louis Dreyfus Company Asia Pte. Ltd., Sunlight Mercantile Pte. Ltd., Bhavani Stores Pte Ltd (Bhavani Stores Private Limited)
# 28: nan
# 29: nan
# 30: Marina Offshore Pte Ltd, Keppel Shipyard
# 31: nan
# 32: Maybank Singapore (Maybank Singapore Limited), Petrochina International (Singapore) Pte. Ltd, World Fuel Services (Singapore) Pte Ltd
# 33: PricewaterhouseCoopers (PwC Singapore), GTP Advisory (GTP Advisory PAC)
# 34: MS First Capital Insurance (Limited), United Overseas Bank (UOB), Unipec Singapore Pte. Ltd., GrabTaxi Holdings Pte Ltd, Lendlease Singapore Pte Ltdv
# 35: ArgoGlobal Underwriting Asia Pacific Pte Ltd, Oversea-Chinese Banking Corporation (OCBC)
# 36: nan
# 37: Maersk Tankers Singapore
# 38: nan

# active SG clients that law firm acted for
df2.loc[0, 'Known Client Base'] = 'Uniper Global Commodities SE Singapore Branch, China Merchants Energy Shipping (Singapore) Holding Pte. Ltd., Sinopec'
df2.loc[1, 'Known Client Base'] = 'BGN Energy'
df2.loc[2, 'Known Client Base'] = 'ED&F Man Capital Markets (Singapore) Pte. Ltd.'
df2.loc[3, 'Known Client Base'] = 'Trafigura, Olam International, ICICI Bank Singapore Branch'
df2.loc[4, 'Known Client Base'] = 'Trafigura, BW Energy Holdings Pte Ltd, HSBC Singapore entities'
df2.loc[5, 'Known Client Base'] = 'Glory Bulk Carriers Pte Ltd, TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd.'
df2.loc[6, 'Known Client Base'] = 'Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore'
df2.loc[7, 'Known Client Base'] = 'Shell Singapore Pte. Ltd, Shell Eastern Trading (Pte) Ltd'
df2.loc[[8,9], 'Known Client Base'] = pd.NA
df2.loc[10, 'Known Client Base'] = pd.NA
df2.loc[11, 'Known Client Base'] = 'Ocean Network Express Pte. Ltd.'
df2.loc[12, 'Known Client Base'] = 'Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd'
df2.loc[13, 'Known Client Base'] = 'JSW International Tradecorp Pte Ltd (JSW), ST Telemedia Global Data Centres (Telemedia Global Data Centres), BTS Tankers Pte Ltd, DBS Bank, United Overseas Bank (UOB), Oversea-Chinese Banking Corporation (OCBC)'
df2.loc[14, 'Known Client Base'] = 'Metro Holdings Limited, Razer'
df2.loc[15, 'Known Client Base'] = 'First Resources Limited, First Sponsor Group Limited, DBS'
df2.loc[16, 'Known Client Base'] = 'United Overseas Bank (UOB), Straits Bunkering Pte Ltd'
df2.loc[17, 'Known Client Base'] = 'Avani Resources Pte. Ltd, Alvari Pte. Ltd.'
df2.loc[18, 'Known Client Base'] = 'BAFCO Singapore Pte. Ltd, The Singapore Medical Council (SMC)' 
df2.loc[19, 'Known Client Base'] = 'FTI Consulting (Singapore) Pte. Ltd.'
df2.loc[20, 'Known Client Base'] = 'Oversea-Chinese Banking Corporation (OCBC), Boustead Projects Limited, Thomson Medical Group (TMG)'
df2.loc[21, 'Known Client Base'] = 'OCBC Bank (Oversea-Chinese Banking Corporation Limited), Winson Oil Trading Pte Ltd'
df2.loc[22, 'Known Client Base'] = 'Louis Dreyfus Company Asia Pte. Ltd.'
df2.loc[23, 'Known Client Base'] = 'Standard Chartered Bank (Singapore) Limited (SCB)'
df2.loc[24, 'Known Client Base'] = 'Halcyon Agri Corporation Limited, Seraya Energy, KPMG, Mizuho Bank, Perennial Real Estate Holdings, Ho Lee Construction, WestBridge Ventures II Investment Holdings'
df2.loc[25, "Known Client Base"] = "Standard Chartered Bank (Singapore) Limited (SCB)"
df2.loc[26, 'Known Client Base'] = 'Atlantic Navigation Holdings (Singapore) Limited, Royal Global Exports Pte Ltd'
df2.loc[27, 'Known Client Base'] = 'Louis Dreyfus Asia Pte Ltd / Louis Dreyfus Company Asia Pte. Ltd.'
df2.loc[28, 'Known Client Base'] = pd.NA
df2.loc[29, 'Known Client Base'] = pd.NA
df2.loc[30, 'Known Client Base'] = 'Marina Offshore Pte Ltd'
df2.loc[31, 'Known Client Base'] = pd.NA
df2.loc[32, 'Known Client Base'] = 'Maybank Singapore (Maybank Singapore Limited), Petrochina International (Singapore) Pte. Ltd'
df2.loc[33, 'Known Client Base'] = 'PricewaterhouseCoopers (PwC Singapore), GTP Advisory (GTP Advisory PAC)'
df2.loc[34, 'Known Client Base'] = 'MS First Capital Insurance (Limited), United Overseas Bank (UOB), Unipec Singapore Pte. Ltd., GrabTaxi Holdings Pte Ltd'
df2.loc[35, "Known Client Base"] = "Argoglobal Underwriting Asia Pacific Pte Ltd, China Taiping Insurance (Singapore) Pte Ltd, Great American Insurance Company, MS First Capital Insurance Limited, QBE Insurance (Singapore) Pte Ltd"
df2.loc[36, 'Known Client Base'] = pd.NA
df2.loc[37, 'Known Client Base'] = 'Maersk Tankers Singapore'
df2.loc[38, 'Known Client Base'] = pd.NA

df2

                       Firm Name                                                                                                                                                                                                   Known Client Base                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Notable Cases / Disputes
0                     Reed Smith                                                                                               Uniper Global Commodities SE Singapore Branch, China Merchants Energy Shipping (Singapore) Holding Pte. Ltd., Sinopec                                                                                                                                                                                                                                              RTI Ltd v MUR Shipping BV [2024] UKSC 18, Sharp Corp Ltd v Viterra BV [2024] UKSC 14, The Aquafreedom [2024] EWHC 255 (Comm), The Ever Given – SMIT Salvage BV and Others v Luster Maritime SA [2024] EWCA Civ 260, Maersk Guiné-Bissau v Almar-Hum Bubacar Baldé [2024] EWHC 993 (Comm) (reedsmith.com)
1    HFW (Holman Fenwick Willan)                                                                                                                                                                                                          BGN Energy                                                                                                                                                                                                                                                                                                            The "Rena" Grounding, OW Bunker Bankruptcy, The "Prestige" Oil Spill, The "Ocean Victory" Case (https://www.studocu.com/en-gb/messages/question/5472340/what-are-some-famous-cases-that-were-advised-by-hfw-and-how-were-they-influential)
2                     Clyde & Co                                                                                                                                                                      ED&F Man Capital Markets (Singapore) Pte. Ltd.                                                                                                                                      The 'Brillante Virtuoso' Case, Precedent setting FOSFA sale of goods arbitration (switzerland), Appealing the Refined Sugar Associations Arbitration Award (UK), Collision of VLCC "ALEXANDRA 1" and "EVER SMART" (UK), Penglai 19-3 Oil Field Pollution (China/USA),  COSCO BUSAN Allision with San Francisco-Oakland Bay Bridge (USA), Agarwal Coal High Court Appeal (UK) (claude + clydeco.com + perplexity)
3             Stephenson Harwood                                                                                                                                                          Trafigura, Olam International, ICICI Bank Singapore Branch                                                                                                                                                                                                         former Yukos Oil Company shareholders v The Russian Federation, Trafigura Pte Ltd & Anor v Prateek Gupta & Ors [2026] EWHC 159 (Comm), SLB and others v PAK and others [2026] EWHC 449 (Comm), GAIL (India) Limited v SEFE Marketing & Trading Singapore Pte Limited, Narciso v Nash (ARB 009/2024) (google AI + google  & news + claude AI )
4       Watson Farley & Williams                                                                                                                                                      Trafigura, BW Energy Holdings Pte Ltd, HSBC Singapore entities                                                                                                                                                   The merger between Hapag-Lloyd and the United Arab Shipping Company (UASC), WFW advises Guinea as US$24bn Simandou African mega-project closes, Niko Resources (Bangladesh) Ltd v. Bangladesh Petroleum Exploration & Production Company Limited ("Bapex") and Bangladesh Oil Gas and Mineral Corporation ("Petrobangla"), MRI Trading AG v Erdenet Mining Corp LLC (2013) (perplexity + google AI)
5        Ince & Co Singapore LLP                                                                                                                             Glory Bulk Carriers Pte Ltd, TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd.                                                                                                                                                                                                                                                                                                                  Global Coal Ltd v London Commodity Brokers (vlex.couk),Statoil ASA v Louis Dreyfus Energy Services LP (The Harriette N)(ipsaloquitur.com ), Priyanka Shipping Limited v Glory Bulk Carriers Pte Ltd [2019] EWHC 2804 (Comm) (Gemini)
6          Norton Rose Fulbright                                                                                                                                                             Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore                                                                                                     Suez Fortune Investments Ltd v Talbot(gemini), PD Teesport Ltd v. P&O North Sea Ferries Ltd — Force Majeure / Ferry Operator Dispute (2022–2023), Carnival Corporation v. Fincantieri S.p.A — Shipbuilding Contract / Breach of Guarantee (Ongoing as of 2024–2025), Shell UK v. Greenpeace UK — FPSO Boarding Dispute (2023–2024), KfW IPEX-Bank v. World Dream Limited ("The World Dream") — Ship Mortgage Enforcement (2022–2024) (perplexity)
7                 Baker McKenzie                                                                                                                                                           Shell Singapore Pte. Ltd, Shell Eastern Trading (Pte) Ltd                                                                                                                                                                                                                                                                                      Anaklia Development Consortium (ADC) and Bob Meijer v. Georgia (ICC & ICSID parallel claims), Lakatamia Shipping Co Ltd v Su & Ors,  Lehram Capital Investments Ltd v. Baker McKenzie, Anaklia Development Consortium (ADC) v. Government of Georgia (google ai)
8            Squire Patton Boggs                                                                                                                                                                                                                 NaN                                                                                                                          LG Caltex v CNPC, Triad Shipping Co v Stellar Chartering & Brokerage Inc (The "Island Archon") [1994] 2 Lloyd's Rep 227, Merit Shipping Co Inc v T.K. Boesen A/S (The "Goodpal") [2000] 1 Lloyd's Rep 638, André & Cie S.A. v Orient Shipping (Rotterdam) B.V. (The "Laconian Confidence") [1997] 1 Lloyd's Rep 139, AIC Ltd v ITS Testing Services (UK) Ltd (The "Kriti Palm") [2006] EWCA Civ 1601 (squirepattonboggs.com)
9                 Hill Dickinson                                                                                                                                                                                                                 NaN                                                                                                                                                                                                                                                                             SY Roro 1 Pte Ltd and another v Onorato Armatori S.R.L. and others [2024] EWHC 611 (Comm) (google AI), Trafigura PTE Ltd & Anor v Gupta & Ors [2026] EWHC 159 (Comm) (hilldickinson.com/our-view/articles/commodity-trader-successful-in-fraudulent-nickel-trade-claims/)
10               Mayer Brown LLP                                                                                                                                                                                                                 NaN                                                                                                                                                                                                                                                                                                  Clearlake Shipping Pte Ltd v. Guvnor Shipping & Others, Aabar Holdings v. Glencore plc, The "Reluctant Ship Owner" Mortgages Enforcement Action, In re: Singamas and Container Cartel Litigation, In re: Glencore PLC SFO Investigation (perplexity)
11          Latham & Watkins LLP                                                                                                                                                                                     Ocean Network Express Pte. Ltd.  Latham & Watkins Advises Riverstone in Acquisition of Trailstone by Engelhart Commodities Trading Partners ( https://www.lw.com/ & Gemini), Latham & Watkins Advises Delfin Midstream on First Offshore Floating Vessel LNG Export Facility in the US (https://www.lw.com/ & Gemini), Latham & Watkins Advised Ocean Network Express in the Completion of Atlas’ Going Private Transaction(https://www.lw.com/ & Gemini), Latham & Watkins Advises Macquarie on 15-Year LNG Sale and Purchase Agreement With AMIGO LNG(https://www.lw.com/ & Gemini)
12                  Rajah & Tann                                                                                                                                                Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd                                                                                                           The Mount Apo [2019] 4 SLR 909, BWG v BWF [2020] 1 SLR 1296, PT Adidaya Energy Mandiri v MS First Capital Insurance Ltd [2022] 4 SLR 371, Sumifru Singapore Pte Ltd v Felix Santos Ishizuka and others [2022] SGHC 14, COSCO Shipping Specialized Carriers Co Ltd v PT OKI Pulp & Paper Mills and others [2023] SGHC 149, Sinopec International (Singapore) Pte Ltd v Bank of Communications Co Ltd [2024] 3 SLR 476 (sg.rajahtannasia.com)
13              Allen & Gledhill  JSW International Tradecorp Pte Ltd (JSW), ST Telemedia Global Data Centres (Telemedia Global Data Centres), BTS Tankers Pte Ltd, DBS Bank, United Overseas Bank (UOB), Oversea-Chinese Banking Corporation (OCBC)                                                                                                                          Public Prosecutor v. Captain George Vakirtzis, Public Prosecutor v. Captain Janusz Czubak, Five Ocean Corp v Cingler Ship Pte Ltd (PT Commodities & Energy Resources, intervener) [2016] 1 SLR 1159, Valency International Pte Ltd v JSW International Tradecorp Pte Ltd & Ors, Natixis Singapore Branch v Lim Oon Kuin and Ors, Hai Jiang 1401 Pte Ltd v Singapore Technologies Marine Ltd (allenandgledhill.com, chambers)
14                 Drew & Napier                                                                                                                                                                                       Metro Holdings Limited, Razer                                                                                                                                                                                                                      Suntech Power Holdings Co Ltd v GSF Capital Pte Ltd and Javier Romero, Ng Joo Soon v Dovechem Holdings Pte Ltd Re Brightoil Petroleum (S’pore) Pte Ltd [2022] SGHC 35, Voss Peer v APL Co Pte Ltd [2002] SGHC 81, Hyosung (HK) Ltd v Owners of the Ship or Vessel "Hilal I" [2000] SGHC 268 (drewnapier.com, googleai, chambers)
15               WongPartnership                                                                                                                                                           First Resources Limited, First Sponsor Group Limited, DBS                                                                                                                                                                                                                                                                                                                                                                   Timing Limited v Tay Toh Hin & Anor [2020] 5 SLR 974, Prime Shipping Corp v Public Prosecutor [2018] 4 SLR 795, Hin Leong Trading / Ocean Tankers Interpleader Proceedings (google)
16                  Helmsman LLC                                                                                                                                                               United Overseas Bank (UOB), Straits Bunkering Pte Ltd                                                                                                                                                                                                                                                                                                                                                                                Public Prosecutor v Richard Ouwehand and Others, Orion Shipping and Trading Ltd v Great Asia Maritime Ltd Vasily Trubnikov v Evgeny Volosov [2025] HKCFI 1576 (google)
17             Blackstone & Gold                                                                                                                                                                          Avani Resources Pte. Ltd, Alvari Pte. Ltd.                                                                                                                                                                                                                                                                                                                                  Marketlend Pty Ltd v QBE Insurance (Singapore) Pte Ltd Majestica Enterprises Ltd v Kams Singapore Pte Ltd $60 Million African Oil Project Arbitration (LCIA London), The Hin Leong Trading Collapse Fallout (gemini)
18         Braddell Brothers LLP                                                                                                                                                       BAFCO Singapore Pte. Ltd, The Singapore Medical Council (SMC)                                                                                                                                                                                                                                                                                                                                                                          BASF Intertrade AG Singapore Branch v H&C S Holding Pte Ltd PetroVietnam v PJSC Power Machines, Teunis Eigenraam v Ngng Pte Ltd Vessel Charterer Winding-Up Defense (gemini)
19     Joseph Tan Jude Benny LLP                                                                                                                                                                                FTI Consulting (Singapore) Pte. Ltd.                                                                                                The “Miracle Hope” [2020] SGHCR 3; BNP Paribas v Bandung Shipping Pte Ltd (Shweta International Pte Ltd and another, third parties) [2003] 3 SLR(R) 611; [2003] SGHC 111; Freight Connect (S) Pte Ltd v Paragon Shipping Pte Ltd [2015] SGCA 37; Zim Integrated Shipping Services Ltd and others v Dafni Igal and others [2010] SGCA 45; The “Rainbow Star” [2011] 3 SLR 1; [2011] SGHC 35 (jtjb.com), Paragon Shipping v Freight Connect (perplexity)
20  Dentons Rodyk & Davidson LLP                                                                                                                  Oversea-Chinese Banking Corporation (OCBC), Boustead Projects Limited, Thomson Medical Group (TMG)                                                                                                                                                                                                                                                                                                                   Government of Sri Lanka v Shipowners of Vessel X-Press Pearl and associated persons, Fastfreight Pte Ltd v Bulk Trident Shipping Ltd Case involving vessel GULF DEFFI, UniCredit Bank AG v Hin Leong Trading (Pte) Ltd (perplexity)
21               Oon & Bazul LLC                                                                                                                                 OCBC Bank (Oversea-Chinese Banking Corporation Limited), Winson Oil Trading Pte Ltd                                                                                                                                                                                                                        The Miracle Hope, Standard Chartered Bank (Singapore) Ltd v Maersk Tankers Singapore Pte Ltd (Winson Oil Trading Pte Ltd intervener) [2022] SGHC 242, The “STI Orchard” (Winson Oil Trading Pte Ltd intervener) [2022] SGHCR 6, he “Yue You 902” [2019] SGHC 106, The “Luna” and another appeal [2021] SGCA 84  (oonbazul.com)
22                   PDLegal LLC                                                                                                                                                                                Louis Dreyfus Company Asia Pte. Ltd.                                                                                                                                                                                                                                                                             The Owner and/or Demise Charterer of the Vessel “Marine Honour” v. The Owner and/or Demise Charterer of the Vessel “Vox Maxima” and Others (gemini), Acting for owners of SOV Southern Star (a DP3 vessel), Representing Japanese ship owner Masao Mizobuchi (perplexity)
23           Shook Lin & Bok LLP                                                                                                                                                                   Standard Chartered Bank (Singapore) Limited (SCB)                                                                                                                                                                              Duncan and Cameron Lindsay and another v Diablo Fortune Inc and another matter SGHC 172, Winson Oil Trading Pte Ltd v Oversea-Chinese Banking Corporation and Standard Chartered Bank (Singapore) Limited SGHC 220, Claim of more than USD80 million against OK Lim and his children, founder/ex-directors, and former senior employee of Hin Leong Trading (perplexity)

In [191]:
# p2 notable cases / disputes, then later check if the law firm acted for the client in the dispute

# extracting clients
# 0 : Trafigura Maritime Logistics Pte Ltd
# 1:  Golden Island Pte Ltd, Mitsui & Co Energy Trading Singapore (METS), Equatorial Marine Fuel Management Services
# 2:  Olam Global Agri Pte Ltd (subsidiary of olam group)
# 3: Trafigura Pte Ltd, SEFE Marketing & Trading Singapore Pte Limited
# 4: nan
# 5: nan
# 6: nan
# 7: nan
# 8 : nan
# 9: Trafigura Pte Ltd
# 10: glencore
# 11: nan
# 12: Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd
# 13: Valency International Pte Ltd
# 14: nan
# 15: nan
# 16: nan
# 17: nan
# 18: BASF Intertrade AG Singapore Branch
# 19: nan
# 20: nan
# 21: Winson Oil Trading Pte Ltd
# 22: nan
# 23: Winson Oil Trading Pte Ltd
# 24: nan
# 25: Winson Oil Trading Pte Ltd
# 26: nan
# 27: nan
# 28: nan
# 29: Antanium Resources Pte. Ltd.
# 30: Winson Oil Trading Pte Ltd
# 31: nan
# 32: nan
# 33: GP Global APAC Pte. Ltd.
# 34: Winson Oil Trading Pte Ltd, CYE
# 35: nan
# 36: nan
# 37: nan
# 38: nan

df2.rename(columns={'Notable Cases / Disputes': 'Clients'}, inplace=True)

# updated actual clients of the law firm from the notable cases / disputes column
df2.loc[[2,4,5,6,7,8,10,11,13,14,15,16,17,19,20,22,23,24,25,26,27,28,29,31,32,35,36,37,38, 30], 'Clients'] = pd.NA
df2.loc[0, 'Clients'] = 'Trafigura Maritime Logistics Pte Ltd'
df2.loc[1, 'Clients'] = 'Mitsui & Co Energy Trading Singapore (METS), Equatorial Marine Fuel Management Services'
df2.loc[3, "Clients"] = "Trafigura Pte Ltd"
df2.loc[9, "Clients"] = "Trafigura Pte Ltd"
df2.loc[12, "Clients"] = "Sumifru Singapore Pte Ltd"
df2.loc[18, "Clients"] = "BASF Intertrade AG Singapore Branch"
df2.loc[21, "Clients"] = "Winson Oil Trading Pte Ltd"   
df2.loc[33, "Clients"] = "GP Global APAC Pte. Ltd."
df2.loc[34, "Clients"] = "Winson Oil Trading Pte Ltd, CYE"

# concatenate the known clients with the clients from notable cases
def combine(row):
    a = row["Known Client Base"]
    b = row["Clients"]
    parts = []
    if not pd.isna(a):
        parts.append(a)
    if not pd.isna(b):
        parts.append(b)
    return ", ".join(parts) if parts else pd.NA

df2["Combined Clients"] = df2[["Known Client Base", "Clients"]].apply(combine, axis=1)

#keep the combined clients
df2 = df2.drop(columns=['Known Client Base', 'Clients'])
df2.rename(columns={'Combined Clients':'Known Clients'},inplace=True)

df2a = df2['Firm Name']
df2b = df2['Known Clients']
df2b

0                                                            Uniper Global Commodities SE Singapore Branch, China Merchants Energy Shipping (Singapore) Holding Pte. Ltd., Sinopec, Trafigura Maritime Logistics Pte Ltd
1                                                                                                                    BGN Energy, Mitsui & Co Energy Trading Singapore (METS), Equatorial Marine Fuel Management Services
2                                                                                                                                                                         ED&F Man Capital Markets (Singapore) Pte. Ltd.
3                                                                                                                                          Trafigura, Olam International, ICICI Bank Singapore Branch, Trafigura Pte Ltd
4                                                                                                                                                         Trafigura, BW Energy Holdings Pte Ltd, HSBC Singapore entities
5                                                                                                                                Glory Bulk Carriers Pte Ltd, TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd.
6                                                                                                                                                                Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore
7                                                                                                                                                              Shell Singapore Pte. Ltd, Shell Eastern Trading (Pte) Ltd
8                                                                                                                                                                                                                    NaN
9                                                                                                                                                                                                      Trafigura Pte Ltd
10                                                                                                                                                                                                                   NaN
11                                                                                                                                                                                       Ocean Network Express Pte. Ltd.
12                                                                                                                       Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd, Sumifru Singapore Pte Ltd
13    JSW International Tradecorp Pte Ltd (JSW), ST Telemedia Global Data Centres (Telemedia Global Data Centres), BTS Tankers Pte Ltd, DBS Bank, United Overseas Bank (UOB), Oversea-Chinese Banking Corporation (OCBC)
14                                                                                                                                                                                         Metro Holdings Limited, Razer
15                                                                                                                                                             First Resources Limited, First Sponsor Group Limited, DBS
16                                                                                                                                                                 United Overseas Bank (UOB), Straits Bunkering Pte Ltd
17                                                                                                                                                                            Avani Resources Pte. Ltd, Alvari Pte. Ltd.
18                                                                                                                    BAFCO Singapore Pte. Ltd, The Singapore Medical Council (SMC), BASF Intertrade AG Singapore Branch
19                                                                                                                                                                                  FTI Consulting (Singapore) Pte. Ltd.
20                                                                                                                    Oversea-Chinese Banking Corporation (OCBC), Boustead Projects Limited, Thomson Medical Group (TMG)
21                                                                                                       OCBC Bank (Oversea-Chinese Banking Corporation Limited), Winson Oil Trading Pte Ltd, Winson Oil Trading Pte Ltd
22                                                                                                                                                                                  Louis Dreyfus Company Asia Pte. Ltd.
23                                                                                                                                                                     Standard Chartered Bank (Singapore) Limited (SCB)
24                                                   Halcyon Agri Corporation Limited, Seraya Energy, KPMG, Mizuho Bank, Perennial Real Estate Holdings, Ho Lee Construction, WestBridge Ventures II Investment Holdings
25                                                                                                                                                                     Standard Chartered Bank (Singapore) Limited (SCB)
26                                                                                                                                        Atlantic Navigation Holdings (Singapore) Limited, Royal Global Exports Pte Ltd
27                                                                                                                                                     Louis Dreyfus Asia Pte Ltd / Louis Dreyfus Company Asia Pte. Ltd.
28                                                                                                                                                                                                                   NaN
29                                                                                                                                                                                                                   NaN
30                                                                                                                                                                                               Marina Offshore Pte Ltd
31                                                                                                                                                                                                                   NaN
32                                                                                                                          Maybank Singapore (Maybank Singapore Limited), Petrochina International (Singapore) Pte. Ltd
33                                                                                                                     PricewaterhouseCoopers (PwC Singapore), GTP Advisory (GTP Advisory PAC), GP Global APAC Pte. Ltd.
34                                                              MS First Capital Insurance (Limited), United Overseas Bank (UOB), Unipec Singapore Pte. Ltd., GrabTaxi Holdings Pte Ltd, Winson Oil Trading Pte Ltd, CYE
35                    Argoglobal Underwriting Asia Pacific Pte Ltd, China Taiping Insurance (Singapore) Pte Ltd, Great American Insurance Company, MS First Capital Insurance Limited, QBE Insurance (Singapore) Pte Ltd
36                                                                                                                                                                                                                   NaN
37                                                                                                                                                                                              Maersk Tankers Singapore
38                                                                                                                                                                                                                   NaN
Name: Known Clients, dtype: str

In [ ]:
# pillar 3
df3 = p3[['Institution Name', 'Known Clients']].copy()

# 0: Trafigura, Glencore, Gunvor, Vitol
# 1: nan
# 2: nan
# 3: nan
# 4: Marubeni, Trafigura, Glencore, Seatrium
# 5: Agrocorp International, Trafigura, Wilmar International Ltd, Louis Dreyfus Company, Rio Tinto
# 6: nan
# 7: Wilmar International, Musim Mas Group, Cargill, Sinar Mas Group, Barramundi Group
# 8: Trafigura, Gunvor, COFCO International, Bunge, Six One Commodities, Mercuria
# 9: {ok}
# 10: Vitol Group, Trafigura, Mercuria Energy Group, Gunvor Group, COFCO International
# 11: Vitol Group, Glencore, Gunvor Group, Olam Agri / Olam Group, Sinar Mas Group
# 12: Trafigura, Gunvor Group, Vitol Group, COFCO International
# 13: {ok}
# 14: {ok}
# 15: {ok}
# 16: {ok}
# 17: nan
# 18: {ok}
# 19: nan
# 20-41: nan
# 42: nan drop komgo reset index
# 43: nan
# 44: nan
# 45: nan
# 46: nan
# 47: nan
# 48: nan
# 49: The Daily Cut Pte Ltd, New & Novel Engineering Pte Ltd, Vyas Engineering Pte Ltd
# 50: nan
# 51: nan
# 52: nan
# 53: nan
# 54: nan
# 55-65: nan
# 66: nan
# 67: nan
# 68: {ok}

# update the active physical commodity trader clients in SG that the financiers lent to
df3.loc[[0], "Known Clients"] = "Trafigura, Glencore, Gunvor, Vitol"
df3.loc[[1,2,3,6,17,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67], "Known Clients"] = 'nan'
df3.loc[[4], "Known Clients"] = "Marubeni, Trafigura, Glencore, Seatrium"
df3.loc[[5], "Known Clients"] = "Agrocorp International, Trafigura, Wilmar International Ltd, Louis Dreyfus Company, Rio Tinto"
df3.loc[[7], "Known Clients"] = "Wilmar International, Musim Mas Group, Cargill, Sinar Mas Group, Barramundi Group"
df3.loc[[8], "Known Clients"] = 'Trafigura, Gunvor, COFCO International, Bunge, Six One Commodities, Mercuria'
df3.loc[10, 'Known Clients'] = 'Vitol Group, Trafigura, Mercuria Energy Group, Gunvor Group, COFCO International'
df3.loc[11, 'Known Clients'] = 'Vitol Group, Glencore, Gunvor Group, Olam Agri / Olam Group, Sinar Mas Group'
df3.loc[12, 'Known Clients'] = 'Trafigura, Gunvor Group, Vitol Group, COFCO International'
df3.loc[49, 'Known Clients'] = 'The Daily Cut Pte Ltd, New & Novel Engineering Pte Ltd, Vyas Engineering Pte Ltd'

# drop 42 and reset index
df3 = df3.drop(index=42)
df3 = df3.reset_index(drop=True)

df3a = df3['Institution Name']
df3a.name = 'Firm Name'

df3b = df3['Known Clients']

In [200]:
# split the df2 Known Clients into its own pd.series
def split_comma_list(cell):
    if not isinstance(cell, str) or not cell.strip():
        return []
    parts = re.split(r",\s*(?![^()]*\))", cell)
    return [p.strip() for p in parts]

# split each row's comma-separated string into a list
split_series = df2b.dropna().apply(split_comma_list)

# explode: each item in the list becomes its own row
exploded = split_series.explode().reset_index(drop=True)

# turn into a DataFrame with one column, one entity name per row
df2_clients_df = pd.DataFrame({"Firm Name": exploded})
df2_clients_df

                                                            Firm Name
0                       Uniper Global Commodities SE Singapore Branch
1       China Merchants Energy Shipping (Singapore) Holding Pte. Ltd.
2                                                             Sinopec
3                                Trafigura Maritime Logistics Pte Ltd
4                                                          BGN Energy
5                         Mitsui & Co Energy Trading Singapore (METS)
6                          Equatorial Marine Fuel Management Services
7                      ED&F Man Capital Markets (Singapore) Pte. Ltd.
8                                                           Trafigura
9                                                  Olam International
10                                        ICICI Bank Singapore Branch
11                                                  Trafigura Pte Ltd
12                                                          Trafigura
13                                         BW Energy Holdings Pte Ltd
14                                            HSBC Singapore entities
15                                        Glory Bulk Carriers Pte Ltd
16         TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd.
17            Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore
18                                           Shell Singapore Pte. Ltd
19                                    Shell Eastern Trading (Pte) Ltd
20                                                  Trafigura Pte Ltd
21                                    Ocean Network Express Pte. Ltd.
22                                          Sumifru Singapore Pte Ltd
23                          Sinopec International (Singapore) Pte Ltd
24                                          Sumifru Singapore Pte Ltd
25                          JSW International Tradecorp Pte Ltd (JSW)
26   ST Telemedia Global Data Centres (Telemedia Global Data Centres)
27                                                BTS Tankers Pte Ltd
28                                                           DBS Bank
29                                         United Overseas Bank (UOB)
30                         Oversea-Chinese Banking Corporation (OCBC)
31                                             Metro Holdings Limited
32                                                              Razer
33                                            First Resources Limited
34                                        First Sponsor Group Limited
35                                                                DBS
36                                         United Overseas Bank (UOB)
37                                          Straits Bunkering Pte Ltd
38                                           Avani Resources Pte. Ltd
39                                                   Alvari Pte. Ltd.
40                                           BAFCO Singapore Pte. Ltd
41                                The Singapore Medical Council (SMC)
42                                BASF Intertrade AG Singapore Branch
43                               FTI Consulting (Singapore) Pte. Ltd.
44                         Oversea-Chinese Banking Corporation (OCBC)
45                                          Boustead Projects Limited
46                                        Thomson Medical Group (TMG)
47            OCBC Bank (Oversea-Chinese Banking Corporation Limited)
48                                         Winson Oil Trading Pte Ltd
49                                         Winson Oil Trading Pte Ltd
50                               Louis Dreyfus Company Asia Pte. Ltd.
51                  Standard Chartered Bank (Singapore) Limited (SCB)
52                                   Halcyon Agri Corporation Limited
53                                                      Seraya Energy
54                                                               KPMG
55                                                        Mizuho Bank
56                                     Perennial Real Estate Holdings
57                                                Ho Lee Construction
58                         WestBridge Ventures II Investment Holdings
59                  Standard Chartered Bank (Singapore) Limited (SCB)
60                   Atlantic Navigation Holdings (Singapore) Limited
61                                       Royal Global Exports Pte Ltd
62  Louis Dreyfus Asia Pte Ltd / Louis Dreyfus Company Asia Pte. Ltd.
63                                            Marina Offshore Pte Ltd
64                      Maybank Singapore (Maybank Singapore Limited)
65                      Petrochina International (Singapore) Pte. Ltd
66                             PricewaterhouseCoopers (PwC Singapore)
67                                    GTP Advisory (GTP Advisory PAC)
68                                           GP Global APAC Pte. Ltd.
69                               MS First Capital Insurance (Limited)
70                                         United Overseas Bank (UOB)
71                                         Unipec Singapore Pte. Ltd.
72                                          GrabTaxi Holdings Pte Ltd
73                                         Winson Oil Trading Pte Ltd
74                                                                CYE
75                       Argoglobal Underwriting Asia Pacific Pte Ltd
76                        China Taiping Insurance (Singapore) Pte Ltd
77                                   Great American Insurance Company
78                                 MS First Capital Insurance Limited
79                                  QBE Insurance (Singapore) Pte Ltd
80                                           Maersk Tankers Singapore

In [201]:
# split the df3 Known Clients into its own pd series

# split each row's comma-separated string into a list
split_series = df3b.dropna().apply(split_comma_list)

# explode: each item in the list becomes its own row
exploded = split_series.explode().reset_index(drop=True)

# turn into a DataFrame with one column, one entity name per row
df3_clients_df = pd.DataFrame({"Firm Name": exploded})
df3_clients_df

                                         Firm Name
0                                        Trafigura
1                                         Glencore
2                                           Gunvor
3                                            Vitol
4                                              nan
5                                              nan
6                                              nan
7                                         Marubeni
8                                        Trafigura
9                                         Glencore
10                                        Seatrium
11                          Agrocorp International
12                                       Trafigura
13                        Wilmar International Ltd
14                           Louis Dreyfus Company
15                                       Rio Tinto
16                                             nan
17                            Wilmar International
18                                 Musim Mas Group
19                                         Cargill
20                                 Sinar Mas Group
21                                Barramundi Group
22                                       Trafigura
23                                          Gunvor
24                             COFCO International
25                                           Bunge
26                             Six One Commodities
27                                        Mercuria
28                                     Vitol Group
29                                       Trafigura
30                           Mercuria Energy Group
31                                    Gunvor Group
32                                            Vale
33                                       Rio Tinto
34                            Wilmar International
35                             COFCO International
36                           Olam Food Ingredients
37                                   Louis Dreyfus
38                                     Vitol Group
39                                       Trafigura
40                           Mercuria Energy Group
41                                    Gunvor Group
42                             COFCO International
43                                     Vitol Group
44                                        Glencore
45                                    Gunvor Group
46                          Olam Agri / Olam Group
47                                 Sinar Mas Group
48                                       Trafigura
49                                    Gunvor Group
50                                     Vitol Group
51                             COFCO International
52                                Unipec Singapore
53                         Trafigura Group pte Ltd
54                                       Trafigura
55   Trafigura Beheer BV / Trafigura Group pte Ltd
56                                             nan
57                         Mercuria Energy Trading
58                                             nan
59                                             nan
60                                             nan
61                                             nan
62                                             nan
63                                             nan
64                                             nan
65                                             nan
66                                             nan
67                                             nan
68                                             nan
69                                             nan
70                                             nan
71                                             nan
72                                             nan
73                                             nan
74                                             nan
75                                             nan
76                                             nan
77                                             nan
78                                             nan
79                                             nan
80                                             nan
81                                             nan
82                                             nan
83                                             nan
84                                             nan
85                                             nan
86                                             nan
87                           The Daily Cut Pte Ltd
88                 New & Novel Engineering Pte Ltd
89                        Vyas Engineering Pte Ltd
90                                             nan
91                                             nan
92                                             nan
93                                             nan
94                                             nan
95                                             nan
96                                             nan
97                                             nan
98                                             nan
99                                             nan
100                                            nan
101                                            nan
102                                            nan
103                                            nan
104                                            nan
105                                            nan
106                                            nan
107                                            nan
108                                 The Prax Group

In [ ]:
# vertically concatenate firms from df1, df2a, df2 clients, df3a, df3 clients
df123 = pd.concat([df1, df2a, df2_clients_df, df3a, df3_clients_df], ignore_index=True)

# df123 contains all the firm names from traders, law firms, lender
# lower everything, remove regex refer to
# https://www.youtube.com/watch?v=4O87RdBgRJ4&list=PLk3qn9pE_2w9WIuE2tWxHR4nwO_qVgT5C&index=1
# cleaning column
df123

                                                             Firm Name
0                                            TRAFIGURA GROUP PTE. LTD.
1                                                  VITOL ASIA PTE LTD.
2                                         MERCURIA HOLDINGS  PTE. LTD.
3                                           GUNVOR SINGAPORE PTE. LTD.
4                                 LOUIS DREYFUS COMPANY ASIA PTE. LTD.
5                                         WILMAR INTERNATIONAL LIMITED
6                                                   OLAM GROUP LIMITED
7                              COFCO INTERNATIONAL SINGAPORE PTE. LTD.
8                              CARGILL ASIA PACIFIC HOLDINGS PTE. LTD.
9                                         GLENCORE SINGAPORE PTE. LTD.
10                          ARCHER-DANIELS-MIDLAND SINGAPORE PTE. LTD.
11                                                BUNGE ASIA PTE. LTD.
12                                                MARUBENI CORPORATION
13                                             MITSUI & CO.  PTE. LTD.
14                                 PTT INTERNATIONAL TRADING PTE. LTD.
15                                          SHELL EASTERN TRADING  LTD
16                                             BP ASIA PACIFIC PTE LTD
17          TOTALENERGIES MARKETING ASIA-PACIFIC MIDDLE EAST PTE. LTD.
18                                 SINOCHEM INTERNATIONAL OIL  PTE LTD
19                                      AGROCORP INTERNATIONAL PTE LTD
20                                   GOLDEN AGRI INTERNATIONAL PTE LTD
21                                        MUSIM MAS HOLDINGS PTE. LTD.
22                                             FIRST RESOURCES LIMITED
23                                        AAVANTI INDUSTRIES PTE. LTD.
24                                          OLAM AGRI HOLDINGS LIMITED
25                                          GERALD SINGAPORE PTE. LTD.
26                                          PACIFIC BASIN SG PTE. LTD.
27                                              WILMAR SUGAR PTE. LTD.
28                               SAHARA ENERGY INTERNATIONAL PTE. LTD.
29                                     SOCAR Trading Singapore Pte Ltd
30                                     WOGEN SOUTH EAST ASIA PTE. LTD.
31                                          TRAXYS SINGAPORE PTE. LTD.
32                                  TRAFIGURA CARBON TRADING PTE. LTD.
33                                                       IXM PTE. LTD.
34                              Aditya Birla Global Trading  Pte. Ltd.
35                               Tata International Singapore Pte Ltd.
36                                            VINMAR OVERSEAS  PTE LTD
37                                                 HELM ASIA Pte. Ltd.
38                                      SINO GAS HOLDINGS PTE. LIMITED
39                             POSCO INTERNATIONAL SINGAPORE PTE. LTD.
40                                                OILMAR SGP PTE. LTD.
41                                        NALA RENEWABLES PTE. LIMITED
42                                        Straits Energy Resources Bhd
43                                        INDOFOOD AGRI RESOURCES LTD.
44                                      ADARO INTERNATIONAL  PTE. LTD.
45                                      HG METAL MANUFACTURING LIMITED
46                                    SD Guthrie International Limited
47                                                AGREX ASIA PTE. LTD.
48                                         LX_INTERNATIONAL  PTE. LTD.
49                             HYUNDAI CORPORATION SINGAPORE PTE. LTD.
50                   WOODSIDE ENERGY AUSTRALIA ASIA HOLDINGS PTE. LTD.
51                                     SAMSUNG C&T SINGAPORE PTE. LTD.
52                                         SINOPEC FUEL OIL  PTE. LTD.
53                                               SOJITZ ASIA PTE. LTD.
54                       SUMITOMO CORPORATION ASIA & OCEANIA PTE. LTD.
55                                         CITIC COMMODITIES PTE. LTD.
56                                 PETROCHINA INTERNATIONAL  PTE. LTD.
57                                          UNIPEC SINGAPORE PTE. LTD.
58                                    Sinopec International  Pte. Ltd.
59                                   SK ENERGY INTERNATIONAL PTE. LTD.
60                                            ITOCHU Singapore Pte Ltd
61                                       GS GLOBAL SINGAPORE PTE. LTD.
62                                   CIPTA COMMODITY TRADING PTE. LTD.
63                                         DAVIS COMMODITIES PTE. LTD.
64                                               OM MATERIALS  PTE LTD
65                   BANPU MINERALS  PTE LTD, BANPU SINGAPORE PTE LTD.
66                                  HD HYUNDAI OIL SINGAPORE PTE. LTD.
67                                TOYOTA TSUSHO ASIA PACIFIC PTE. LTD.
68                                  CHALCO TRADING SINGAPORE PTE. LTD.
69                                           SHELL SINGAPORE PTE. LTD.
70                                 SUMMIT ENERGY & RESOURCES PTE. LTD.
71           Pertamina International Marketing & Distribution Pte. Ltd
72                                   Idemitsu International  Pte. Ltd.
73                                   ENEOS OIL & ENERGY ASIA PTE. LTD.
74                                   COSMO OIL INTERNATIONAL PTE. LTD.
75                                               JFE SHOJI CORPORATION
76                              CENTURY COMMODITIES SOLUTION PTE. LTD.
77                                        RAWSTEEL MINMETALS PTE. LTD.
78                                  GCE Agri; GCE BUSINESS CONSULTANTS
79                                        DKC STEEL SINGAPORE PTE LTD.
80                                                  MRI Group Pte. Ltd
81                                            UNIFOOD INT'L  PTE. LTD.
82                             NOBLE RESOURCES INTERNATIONAL PTE. LTD.
83                                             Cemcoa Energy Pte. Ltd.
84                                   INTERCHEM MANUFACTURING PTE. LTD.
85                   Mitsubishi Corporation RtM International Pte Ltd.
86                                           AAA OILS & FATS PTE. LTD.
87                                  TRILAND METALS SINGAPORE PTE. LTD.
88                                          GINGA PETROLEUM  PTE LTD /
89                                              CONCORD ENERGY PTE LTD
90                                             Pacific Minerals Ltd: n
91                                                             Unknown
92                                      KZ TRADING SINGAPORE PTE. LTD.
93                                        PETRACO OIL COMPANY PTE LTD.
94                                 THE STRAITS INTERNATIONAL PTE. LTD.
95                                         STRAITS BUNKERING PTE. LTD.
96                                            PACIFIC ENERGY PTE. LTD.
97                                           QUANTUM GLOBAL  PTE. LTD.
98                                         MERIDIAN EQUITIES PTE. LTD.
99                                SWAN INTERNATIONAL HOLDING PTE. LTD.
100                                              Bary Chemical Pte Ltd
101                ORIENTAL ENERGY PTE LTD& ORIENTAL RESOURCES PTE LTD
102                                            BARY CHEMICAL PTE. LTD.
103                                      MAHKOTA OILS & FATS PTE. LTD.
104                                                         Reed Smith
105                                        HFW (Holman Fenwick Willan)
106                                                         Clyde & Co
107                                                 Stephenson Harwood
108                                           Watson Farley & Williams
109                                            Ince & Co Singapore LLP
110                                              Norton Rose Fulbright
111                                                     Baker McKenzie
112                                                Squire Patton Boggs
113                                                     Hill Dickinson
114                                                    Mayer Brown LLP
115                                               Latham & Watkins LLP
116                                                       Rajah & Tann
117                                                   Allen & Gledhill
118                                                      Drew & Napier
119                                                    WongPartnership
120                                                       Helmsman LLC
121                                                  Blackstone & Gold
122                                              Braddell Brothers LLP
123                                          Joseph Tan Jude Benny LLP
124                                       Dentons Rodyk & Davidson LLP
125                                                    Oon & Bazul LLC
126                                                        PDLegal LLC
127                                                Shook Lin & Bok LLP
128                                               TSMP Law Corporation
129                                                     Virtus Law LLP
130                                                      DennisMathiew
131                                                      AsiaLegal LLC
132                                                Christopher Lau, SC
133                                          Dunbar & Lim Chambers LLC
134                                             Haridass Ho & Partners
135                                          Gill Arbitration Services
136                                                 PK Wong & Nair LLC
137                                            Providence Law Asia LLC
138                                               LVM Law Chambers LLC
139                                                   Incisive Law LLC
140                                                   Damodara Ong LLC
141                                                 Focus Law Asia LLC
142                                                   Resource Law LLC
143                      Uniper Global Commodities SE Singapore Branch
144      China Merchants Energy Shipping (Singapore) Holding Pte. Ltd.
145                                                            Sinopec
146                               Trafigura Maritime Logistics Pte Ltd
147                                                         BGN Energy
148                        Mitsui & Co Energy Trading Singapore (METS)
149                         Equatorial Marine Fuel Management Services
150                     ED&F Man Capital Markets (Singapore) Pte. Ltd.
151                                                          Trafigura
152                                                 Olam International
153                                        ICICI Bank Singapore Branch
154                                                  Trafigura Pte Ltd
155                                                          Trafigura
156                                         BW Energy Holdings Pte Ltd
157                                            HSBC Singapore entities
158                                        Glory Bulk Carriers Pte Ltd
159         TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd.
160            Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore
161                                           Shell Singapore Pte. Ltd
162                                    Shell Eastern Trading (Pte) Ltd
163                                                  Trafigura Pte Ltd
164                                    Ocean Network Express Pte. Ltd.
165                                          Sumifru Singapore Pte Ltd
166                          Sinopec International (Singapore) Pte Ltd
167                                          Sumifru Singapore Pte Ltd
168                          JSW International Tradecorp Pte Ltd (JSW)
169   ST Telemedia Global Data Centres (Telemedia Global Data Centres)
170                                                BTS Tankers Pte Ltd
171                                                           DBS Bank
172                                         United Overseas Bank (UOB)
173                         Oversea-Chinese Banking Corporation (OCBC)
174                                             Metro Holdings Limited
175                                                              Razer
176                                            First Resources Limited
177                                        First Sponsor Group Limited
178                                                                DBS
179                                         United Overseas Bank (UOB)
180                                          Straits Bunkering Pte Ltd
181                                           Avani Resources Pte. Ltd
182                                                   Alvari Pte. Ltd.
183                                           BAFCO Singapore Pte. Ltd
184                                The Singapore Medical Council (SMC)
185                                BASF Intertrade AG Singapore Branch
186                               FTI Consulting (Singapore) Pte. Ltd.
187                         Oversea-Chinese Banking Corporation (OCBC)
188                                          Boustead Projects Limited
189                                        Thomson Medical Group (TMG)
190            OCBC Bank (Oversea-Chinese Banking Corporation Limited)
191                                         Winson Oil Trading Pte Ltd
192                                         Winson Oil Trading Pte Ltd
193                               Louis Dreyfus Company Asia Pte. Ltd.
194                  Standard Chartered Bank (Singapore) Limited (SCB)
195                                   Halcyon Agri Corporation Limited
196                                                      Seraya Energy
197                                                               KPMG
198                                                        Mizuho Bank
199                                     Perennial Real Estate Holdings
200                                                Ho Lee Construction
201                         WestBridge Ventures II Investment Holdings
202                  Standard Chartered Bank (Singapore) Limited (SCB)
203                   Atlantic Navigation Holdings (Singapore) Limited
204                                       Royal Global Exports Pte Ltd
205  Louis Dreyfus Asia Pte Ltd / Louis Dreyfus Company Asia Pte. Ltd.
206                                            Marina Offshore Pte Ltd
207                      Maybank Singapore (Maybank Singapore Limited)
208                      Petrochina International (Singapore) Pte. Ltd
209                             PricewaterhouseCoopers (PwC Singapore)
210                                    GTP Advisory (GTP Advisory PAC)
211                                           GP Global APAC Pte. Ltd.
212                               MS First Capital Insurance (Limited)
213                                         United Overseas Bank (UOB)
214                                         Unipec Singapore Pte. Ltd.
215                                          GrabTaxi Holdings Pte Ltd
216                                         Winson Oil Trading Pte Ltd
217                                                                CYE
218                       Argoglobal Underwriting Asia Pacific Pte Ltd
219                        China Taiping Insurance (Singapore) Pte Ltd
220                                   Great American Insurance Company
221                                 MS First Capital Insurance Limited
222                                  QBE Insurance (Singapore) Pte Ltd
223                                           Maersk Tankers Singapore
224                                                                ING
225                                                   Société Générale
226                                                        BNP Paribas
227                                                           Rabobank
228                                                 Standard Chartered
229                                                                DBS
230                                                               OCBC
231                                                                UOB
232                                                               MUFG
233                                                               SMBC
234                                                    Crédit Agricole
235                                                               HSBC
236                                                            Natixis
237                                    Bank of China, Singapore Branch
238                          China Construction Bank, Singapore Branch
239                                             ICBC, Singapore Branch
240                       Agricultural Bank of China, Singapore Branch
241          Shanghai Pudong Development Bank (SPDB), Singapore Branch
242                                        MUFG Bank, Singapore Branch
243                                   Macquarie Bank, Singapore Branch
244             Commonwealth Bank of Australia (CBA), Singapore Branch
245                                         ANZ Bank, Singapore Branch
246                      Westpac Banking Corporation, Singapore Branch
247                    National Australia Bank (NAB), Singapore Branch
248                                 CIMB Bank Berhad, Singapore Branch
249   Maybank Singapore Ltd / Malayan Banking Berhad, Singapore Branch
250                                  RHB Bank Berhad, Singapore Branch
251                          Bank of East Asia (BEA), Singapore Branch
252                              State Bank of India, Singapore Branch
253                                       DZ Bank AG, Singapore Branch
254                                 Deutsche Bank AG, Singapore Branch
255                                   Commerzbank AG, Singapore Branch
256                             Citibank N.A. / Citi, Singapore Branch
257                                    Goldman Sachs, Singapore Branch
258                              JPMorgan Chase Bank, Singapore Branch
259                                             BBVA, Singapore Branch
260                                  Bank of America, Singapore Branch
261                                                            Ossiano
262                                                              Copap
263                                                  Tradeflow Capital
264                                                            Mercore
265                                                           Audentia
266                                                   ED&F Man Capital
267                                                          Czarnikow
268                                                   Sucden Financial
269                                                       Drip Capital
270                                                Incomlend Pte. Ltd.
271                     GXS Capital Pte. Ltd. (f.k.a. Validus Capital)
272                           FS Capital Pte. Ltd. (Funding Societies)
273                                                    IFS Capital Ltd
274                               Straits Financial Services Pte. Ltd.
275           GB Helios Pte. Ltd. (f.k.a. Goldbell Financial Services)
276                            Nomura Securities (Singapore) Pte. Ltd.
277                                                        ADM Capital
278                                             Hong Leong Finance Ltd
279                                           EASTvine Capital Pte Ltd

In [ ]:
# entity resolution on this column