In [ ]:
# p1[['Company Name', 'Legal Name / ACRA UEN', 'Commodity Focus', 'HQ Country','APAC Offices','Notes']]
# pillar2['Known Client Base'], names from p2['Notable Cases / Disputes'], url in pillar2['Notes']
# pillar3['Known Clients'], url in p3['Notes']

In [1]:
import pandas as pd

# display columns without truncation
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

# display rows without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.expand_frame_repr", False)

In [266]:
# read 3 pillars
p1 = pd.read_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar1.csv", encoding="utf-8")
p2 = pd.read_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar2.csv", encoding="utf-8")
p3 = pd.read_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar3.csv", encoding="utf-8")

In [267]:
# pillar 1 legal names
import re
df1 = p1['Legal Name / ACRA UEN'].copy()
# remove brackets from legal name col
df1= df1.str.replace(r"[\(\[].*?[\)\]]", "", regex=True).str.strip()
# remove the UEN
import re
def strip_uen(cell):
    if not isinstance(cell, str) or not cell.strip():
        return cell
    # remove everything from the slash onward (the UEN number/code)
    # handles inconsistent spacing before/after the slash
    return re.sub(r"\s*/\s*[A-Za-z0-9]+\s*", "", cell).strip()

df1 = df1.apply(strip_uen)
# convert to dataframe
df1 = df1.rename("Firm Name").to_frame() #after running this, df1['Firm Name'] works

#index 90 is pacific minerals
df1.loc[90, 'Firm Name'] = 'Pacific Minerals'
# index 91 is trimax group
df1.loc[91, 'Firm Name'] = "Trimex Group"

df1

                                                      Firm Name
0                                     TRAFIGURA GROUP PTE. LTD.
1                                           VITOL ASIA PTE LTD.
2                                  MERCURIA HOLDINGS  PTE. LTD.
3                                    GUNVOR SINGAPORE PTE. LTD.
4                          LOUIS DREYFUS COMPANY ASIA PTE. LTD.
5                                  WILMAR INTERNATIONAL LIMITED
6                                            OLAM GROUP LIMITED
7                       COFCO INTERNATIONAL SINGAPORE PTE. LTD.
8                       CARGILL ASIA PACIFIC HOLDINGS PTE. LTD.
9                                  GLENCORE SINGAPORE PTE. LTD.
10                   ARCHER-DANIELS-MIDLAND SINGAPORE PTE. LTD.
11                                         BUNGE ASIA PTE. LTD.
12                                         MARUBENI CORPORATION
13                                      MITSUI & CO.  PTE. LTD.
14                          PTT INTERNATIONAL TRADING PTE. LTD.
15                                   SHELL EASTERN TRADING  LTD
16                                      BP ASIA PACIFIC PTE LTD
17   TOTALENERGIES MARKETING ASIA-PACIFIC MIDDLE EAST PTE. LTD.
18                          SINOCHEM INTERNATIONAL OIL  PTE LTD
19                               AGROCORP INTERNATIONAL PTE LTD
20                            GOLDEN AGRI INTERNATIONAL PTE LTD
21                                 MUSIM MAS HOLDINGS PTE. LTD.
22                                      FIRST RESOURCES LIMITED
23                                 AAVANTI INDUSTRIES PTE. LTD.
24                                   OLAM AGRI HOLDINGS LIMITED
25                                   GERALD SINGAPORE PTE. LTD.
26                                   PACIFIC BASIN SG PTE. LTD.
27                                       WILMAR SUGAR PTE. LTD.
28                        SAHARA ENERGY INTERNATIONAL PTE. LTD.
29                              SOCAR Trading Singapore Pte Ltd
30                              WOGEN SOUTH EAST ASIA PTE. LTD.
31                                   TRAXYS SINGAPORE PTE. LTD.
32                           TRAFIGURA CARBON TRADING PTE. LTD.
33                                                IXM PTE. LTD.
34                       Aditya Birla Global Trading  Pte. Ltd.
35                        Tata International Singapore Pte Ltd.
36                                     VINMAR OVERSEAS  PTE LTD
37                                          HELM ASIA Pte. Ltd.
38                               SINO GAS HOLDINGS PTE. LIMITED
39                      POSCO INTERNATIONAL SINGAPORE PTE. LTD.
40                                         OILMAR SGP PTE. LTD.
41                                 NALA RENEWABLES PTE. LIMITED
42                                 Straits Energy Resources Bhd
43                                 INDOFOOD AGRI RESOURCES LTD.
44                               ADARO INTERNATIONAL  PTE. LTD.
45                               HG METAL MANUFACTURING LIMITED
46                             SD Guthrie International Limited
47                                         AGREX ASIA PTE. LTD.
48                                  LX_INTERNATIONAL  PTE. LTD.
49                      HYUNDAI CORPORATION SINGAPORE PTE. LTD.
50            WOODSIDE ENERGY AUSTRALIA ASIA HOLDINGS PTE. LTD.
51                              SAMSUNG C&T SINGAPORE PTE. LTD.
52                                  SINOPEC FUEL OIL  PTE. LTD.
53                                        SOJITZ ASIA PTE. LTD.
54                SUMITOMO CORPORATION ASIA & OCEANIA PTE. LTD.
55                                  CITIC COMMODITIES PTE. LTD.
56                          PETROCHINA INTERNATIONAL  PTE. LTD.
57                                   UNIPEC SINGAPORE PTE. LTD.
58                             Sinopec International  Pte. Ltd.
59                            SK ENERGY INTERNATIONAL PTE. LTD.
60                                     ITOCHU Singapore Pte Ltd
61                                GS GLOBAL SINGAPORE PTE. LTD.
62                            CIPTA COMMODITY TRADING PTE. LTD.
63                                  DAVIS COMMODITIES PTE. LTD.
64                                        OM MATERIALS  PTE LTD
65            BANPU MINERALS  PTE LTD, BANPU SINGAPORE PTE LTD.
66                           HD HYUNDAI OIL SINGAPORE PTE. LTD.
67                         TOYOTA TSUSHO ASIA PACIFIC PTE. LTD.
68                           CHALCO TRADING SINGAPORE PTE. LTD.
69                                    SHELL SINGAPORE PTE. LTD.
70                          SUMMIT ENERGY & RESOURCES PTE. LTD.
71    Pertamina International Marketing & Distribution Pte. Ltd
72                            Idemitsu International  Pte. Ltd.
73                            ENEOS OIL & ENERGY ASIA PTE. LTD.
74                            COSMO OIL INTERNATIONAL PTE. LTD.
75                                        JFE SHOJI CORPORATION
76                       CENTURY COMMODITIES SOLUTION PTE. LTD.
77                                 RAWSTEEL MINMETALS PTE. LTD.
78                           GCE Agri; GCE BUSINESS CONSULTANTS
79                                 DKC STEEL SINGAPORE PTE LTD.
80                                           MRI Group Pte. Ltd
81                                     UNIFOOD INT'L  PTE. LTD.
82                      NOBLE RESOURCES INTERNATIONAL PTE. LTD.
83                                      Cemcoa Energy Pte. Ltd.
84                            INTERCHEM MANUFACTURING PTE. LTD.
85            Mitsubishi Corporation RtM International Pte Ltd.
86                                    AAA OILS & FATS PTE. LTD.
87                           TRILAND METALS SINGAPORE PTE. LTD.
88                                   GINGA PETROLEUM  PTE LTD /
89                                       CONCORD ENERGY PTE LTD
90                                             Pacific Minerals
91                                                 Trimex Group
92                               KZ TRADING SINGAPORE PTE. LTD.
93                                 PETRACO OIL COMPANY PTE LTD.
94                          THE STRAITS INTERNATIONAL PTE. LTD.
95                                  STRAITS BUNKERING PTE. LTD.
96                                     PACIFIC ENERGY PTE. LTD.
97                                    QUANTUM GLOBAL  PTE. LTD.
98                                  MERIDIAN EQUITIES PTE. LTD.
99                         SWAN INTERNATIONAL HOLDING PTE. LTD.
100                                       Bary Chemical Pte Ltd
101         ORIENTAL ENERGY PTE LTD& ORIENTAL RESOURCES PTE LTD
102                                     BARY CHEMICAL PTE. LTD.
103                               MAHKOTA OILS & FATS PTE. LTD.

In [268]:
# p2 known client base
df2 = p2[['Firm Name','Known Client Base', 'Notable Cases / Disputes']].copy()
df2

# 0: Uniper Global Commodities SE Singapore Branch, China Merchants Energy Shipping (Singapore) Holding Pte. Ltd., Sinopec
# 1: BGN Energy, Gunvor Group, Uniserve Pte. Ltd, Technip Energies Singapore Pte. Ltd, Abu Dhabi Commercial Bank
# 2: ED&F Man Capital Markets (Singapore) Pte. Ltd., Lendlease Singapore Pte Ltd / Lendlease REIT, Citigroup / Citi Singapore, Jaguar Land Rover Singapore Pte. Ltd.
# 3: Trafigura, PSA International, Olam International, ICICI Bank Singapore Branch
# 4: Trafigura, BW Energy Holdings Pte Ltd, HSBC Singapore entities
# 5: Glory Bulk Carriers Pte Ltd, TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd., Trafigura Group Pte. Ltd, Seacon Shipping’s Singapore entities, Clearlake Shipping
# 6: Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore
# 7: Shell Singapore Pte. Ltd
# 8: nan
# 9: Star Academies
# 10: nan
# 11: Ocean Network Express Pte. Ltd.
# 12: Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd, Neptune Associated Shipping Pte Ltd
# 13: JSW International Tradecorp Pte Ltd (JSW), ST Telemedia Global Data Centres (Telemedia Global Data Centres), BTS Tankers Pte Ltd, DBS Bank, United Overseas Bank (UOB), Oversea-Chinese Banking Corporation (OCBC)
# 14: Resources Prima Group Ltd, Metro Holdings Limited, Razer, Eagle Hospitality Trust, ST Marine Ltd (Singapore Technologies Marine), O.W. Bunker Far East (Pte) Ltd, Dynamic Oil Trading (Singapore) Pte Ltd
# 15: First Resources Limited, First Sponsor Group Limited, DBS, Seatrium
# 16: United Overseas Bank (UOB), Straits Bunkering Pte Ltd
# 17: Avani Resources Pte. Ltd, Alvari Pte. Ltd.
# 18: BAFCO Singapore Pte. Ltd, The Singapore Medical Council (SMC)
# 19: FTI Consulting (Singapore) Pte. Ltd.
# 20: Oversea-Chinese Banking Corporation (OCBC), Boustead Projects Limited, Thomson Medical Group (TMG)
# 21: OCBC Bank (Oversea-Chinese Banking Corporation Limited), Winson Oil Trading Pte Ltd
# 22: Louis Dreyfus Company Asia Pte. Ltd.
# 23: Standard Chartered Bank (Singapore) Limited (SCB)
# 24: Halcyon Agri Corporation Limited, Seraya Energy, Century Holdings Pte. Ltd, KPMG, Mizuho Bank, Perennial Real Estate Holdings, Ho Lee Construction, WestBridge Ventures II Investment Holdings
# 25: Standard Chartered Bank (Singapore) Limited
# 26: Atlantic Navigation Holdings (Singapore) Limited, Royal Global Exports Pte Ltd
# 27: Louis Dreyfus Asia Pte Ltd / Louis Dreyfus Company Asia Pte. Ltd., Sunlight Mercantile Pte. Ltd., Bhavani Stores Pte Ltd (Bhavani Stores Private Limited)
# 28: nan
# 29: nan
# 30: Marina Offshore Pte Ltd, Keppel Shipyard
# 31: nan
# 32: Maybank Singapore (Maybank Singapore Limited), Petrochina International (Singapore) Pte. Ltd, World Fuel Services (Singapore) Pte Ltd
# 33: PricewaterhouseCoopers (PwC Singapore), GTP Advisory (GTP Advisory PAC)
# 34: MS First Capital Insurance (Limited), United Overseas Bank (UOB), Unipec Singapore Pte. Ltd., GrabTaxi Holdings Pte Ltd, Lendlease Singapore Pte Ltdv
# 35: ArgoGlobal Underwriting Asia Pacific Pte Ltd, Oversea-Chinese Banking Corporation (OCBC)
# 36: nan
# 37: Maersk Tankers Singapore
# 38: nan

# active SG clients that law firm acted for
df2.loc[0, 'Known Client Base'] = 'Uniper Global Commodities SE Singapore Branch, China Merchants Energy Shipping (Singapore) Holding Pte. Ltd., Sinopec'
df2.loc[1, 'Known Client Base'] = 'BGN Energy'
df2.loc[2, 'Known Client Base'] = 'ED&F Man Capital Markets (Singapore) Pte. Ltd.'
df2.loc[3, 'Known Client Base'] = 'Trafigura, Olam International, ICICI Bank Singapore Branch'
df2.loc[4, 'Known Client Base'] = 'Trafigura, BW Energy Holdings Pte Ltd, HSBC Singapore entities'
df2.loc[5, 'Known Client Base'] = 'Glory Bulk Carriers Pte Ltd, TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd.'
df2.loc[6, 'Known Client Base'] = 'Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore'
df2.loc[7, 'Known Client Base'] = 'Shell Singapore Pte. Ltd, Shell Eastern Trading (Pte) Ltd'
df2.loc[[8,9], 'Known Client Base'] = pd.NA
df2.loc[10, 'Known Client Base'] = pd.NA
df2.loc[11, 'Known Client Base'] = 'Ocean Network Express Pte. Ltd.'
df2.loc[12, 'Known Client Base'] = 'Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd'
df2.loc[13, 'Known Client Base'] = 'JSW International Tradecorp Pte Ltd (JSW), ST Telemedia Global Data Centres (Telemedia Global Data Centres), BTS Tankers Pte Ltd, DBS Bank, United Overseas Bank (UOB), Oversea-Chinese Banking Corporation (OCBC)'
df2.loc[14, 'Known Client Base'] = 'Metro Holdings Limited, Razer'
df2.loc[15, 'Known Client Base'] = 'First Resources Limited, First Sponsor Group Limited, DBS'
df2.loc[16, 'Known Client Base'] = 'United Overseas Bank (UOB), Straits Bunkering Pte Ltd'
df2.loc[17, 'Known Client Base'] = 'Avani Resources Pte. Ltd, Alvari Pte. Ltd.'
df2.loc[18, 'Known Client Base'] = 'BAFCO Singapore Pte. Ltd, The Singapore Medical Council (SMC)' 
df2.loc[19, 'Known Client Base'] = 'FTI Consulting (Singapore) Pte. Ltd.'
df2.loc[20, 'Known Client Base'] = 'Oversea-Chinese Banking Corporation (OCBC), Boustead Projects Limited, Thomson Medical Group (TMG)'
df2.loc[21, 'Known Client Base'] = 'OCBC Bank (Oversea-Chinese Banking Corporation Limited), Winson Oil Trading Pte Ltd'
df2.loc[22, 'Known Client Base'] = 'Louis Dreyfus Company Asia Pte. Ltd.'
df2.loc[23, 'Known Client Base'] = 'Standard Chartered Bank (Singapore) Limited (SCB)'
df2.loc[24, 'Known Client Base'] = 'Halcyon Agri Corporation Limited, Seraya Energy, KPMG, Mizuho Bank, Perennial Real Estate Holdings, Ho Lee Construction, WestBridge Ventures II Investment Holdings'
df2.loc[25, "Known Client Base"] = "Standard Chartered Bank (Singapore) Limited (SCB)"
df2.loc[26, 'Known Client Base'] = 'Atlantic Navigation Holdings (Singapore) Limited, Royal Global Exports Pte Ltd'
df2.loc[27, 'Known Client Base'] = 'Louis Dreyfus Asia Pte Ltd / Louis Dreyfus Company Asia Pte. Ltd.'
df2.loc[28, 'Known Client Base'] = pd.NA
df2.loc[29, 'Known Client Base'] = pd.NA
df2.loc[30, 'Known Client Base'] = 'Marina Offshore Pte Ltd'
df2.loc[31, 'Known Client Base'] = pd.NA
df2.loc[32, 'Known Client Base'] = 'Maybank Singapore (Maybank Singapore Limited), Petrochina International (Singapore) Pte. Ltd'
df2.loc[33, 'Known Client Base'] = 'PricewaterhouseCoopers (PwC Singapore), GTP Advisory (GTP Advisory PAC)'
df2.loc[34, 'Known Client Base'] = 'MS First Capital Insurance (Limited), United Overseas Bank (UOB), Unipec Singapore Pte. Ltd., GrabTaxi Holdings Pte Ltd'
df2.loc[35, "Known Client Base"] = "Argoglobal Underwriting Asia Pacific Pte Ltd, China Taiping Insurance (Singapore) Pte Ltd, Great American Insurance Company, MS First Capital Insurance Limited, QBE Insurance (Singapore) Pte Ltd"
df2.loc[36, 'Known Client Base'] = pd.NA
df2.loc[37, 'Known Client Base'] = 'Maersk Tankers Singapore'
df2.loc[38, 'Known Client Base'] = pd.NA

df2

                       Firm Name                                                                                                                                                                                                   Known Client Base                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Notable Cases / Disputes
0                     Reed Smith                                                                                               Uniper Global Commodities SE Singapore Branch, China Merchants Energy Shipping (Singapore) Holding Pte. Ltd., Sinopec                                                                                                                                                                                                                                              RTI Ltd v MUR Shipping BV [2024] UKSC 18, Sharp Corp Ltd v Viterra BV [2024] UKSC 14, The Aquafreedom [2024] EWHC 255 (Comm), The Ever Given – SMIT Salvage BV and Others v Luster Maritime SA [2024] EWCA Civ 260, Maersk Guiné-Bissau v Almar-Hum Bubacar Baldé [2024] EWHC 993 (Comm) (reedsmith.com)
1    HFW (Holman Fenwick Willan)                                                                                                                                                                                                          BGN Energy                                                                                                                                                                                                                                                                                                            The "Rena" Grounding, OW Bunker Bankruptcy, The "Prestige" Oil Spill, The "Ocean Victory" Case (https://www.studocu.com/en-gb/messages/question/5472340/what-are-some-famous-cases-that-were-advised-by-hfw-and-how-were-they-influential)
2                     Clyde & Co                                                                                                                                                                      ED&F Man Capital Markets (Singapore) Pte. Ltd.                                                                                                                                      The 'Brillante Virtuoso' Case, Precedent setting FOSFA sale of goods arbitration (switzerland), Appealing the Refined Sugar Associations Arbitration Award (UK), Collision of VLCC "ALEXANDRA 1" and "EVER SMART" (UK), Penglai 19-3 Oil Field Pollution (China/USA),  COSCO BUSAN Allision with San Francisco-Oakland Bay Bridge (USA), Agarwal Coal High Court Appeal (UK) (claude + clydeco.com + perplexity)
3             Stephenson Harwood                                                                                                                                                          Trafigura, Olam International, ICICI Bank Singapore Branch                                                                                                                                                                                                         former Yukos Oil Company shareholders v The Russian Federation, Trafigura Pte Ltd & Anor v Prateek Gupta & Ors [2026] EWHC 159 (Comm), SLB and others v PAK and others [2026] EWHC 449 (Comm), GAIL (India) Limited v SEFE Marketing & Trading Singapore Pte Limited, Narciso v Nash (ARB 009/2024) (google AI + google  & news + claude AI )
4       Watson Farley & Williams                                                                                                                                                      Trafigura, BW Energy Holdings Pte Ltd, HSBC Singapore entities                                                                                                                                                   The merger between Hapag-Lloyd and the United Arab Shipping Company (UASC), WFW advises Guinea as US$24bn Simandou African mega-project closes, Niko Resources (Bangladesh) Ltd v. Bangladesh Petroleum Exploration & Production Company Limited ("Bapex") and Bangladesh Oil Gas and Mineral Corporation ("Petrobangla"), MRI Trading AG v Erdenet Mining Corp LLC (2013) (perplexity + google AI)
5        Ince & Co Singapore LLP                                                                                                                             Glory Bulk Carriers Pte Ltd, TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd.                                                                                                                                                                                                                                                                                                                  Global Coal Ltd v London Commodity Brokers (vlex.couk),Statoil ASA v Louis Dreyfus Energy Services LP (The Harriette N)(ipsaloquitur.com ), Priyanka Shipping Limited v Glory Bulk Carriers Pte Ltd [2019] EWHC 2804 (Comm) (Gemini)
6          Norton Rose Fulbright                                                                                                                                                             Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore                                                                                                     Suez Fortune Investments Ltd v Talbot(gemini), PD Teesport Ltd v. P&O North Sea Ferries Ltd — Force Majeure / Ferry Operator Dispute (2022–2023), Carnival Corporation v. Fincantieri S.p.A — Shipbuilding Contract / Breach of Guarantee (Ongoing as of 2024–2025), Shell UK v. Greenpeace UK — FPSO Boarding Dispute (2023–2024), KfW IPEX-Bank v. World Dream Limited ("The World Dream") — Ship Mortgage Enforcement (2022–2024) (perplexity)
7                 Baker McKenzie                                                                                                                                                           Shell Singapore Pte. Ltd, Shell Eastern Trading (Pte) Ltd                                                                                                                                                                                                                                                                                      Anaklia Development Consortium (ADC) and Bob Meijer v. Georgia (ICC & ICSID parallel claims), Lakatamia Shipping Co Ltd v Su & Ors,  Lehram Capital Investments Ltd v. Baker McKenzie, Anaklia Development Consortium (ADC) v. Government of Georgia (google ai)
8            Squire Patton Boggs                                                                                                                                                                                                                <NA>                                                                                                                          LG Caltex v CNPC, Triad Shipping Co v Stellar Chartering & Brokerage Inc (The "Island Archon") [1994] 2 Lloyd's Rep 227, Merit Shipping Co Inc v T.K. Boesen A/S (The "Goodpal") [2000] 1 Lloyd's Rep 638, André & Cie S.A. v Orient Shipping (Rotterdam) B.V. (The "Laconian Confidence") [1997] 1 Lloyd's Rep 139, AIC Ltd v ITS Testing Services (UK) Ltd (The "Kriti Palm") [2006] EWCA Civ 1601 (squirepattonboggs.com)
9                 Hill Dickinson                                                                                                                                                                                                                <NA>                                                                                                                                                                                                                                                                             SY Roro 1 Pte Ltd and another v Onorato Armatori S.R.L. and others [2024] EWHC 611 (Comm) (google AI), Trafigura PTE Ltd & Anor v Gupta & Ors [2026] EWHC 159 (Comm) (hilldickinson.com/our-view/articles/commodity-trader-successful-in-fraudulent-nickel-trade-claims/)
10               Mayer Brown LLP                                                                                                                                                                                                                <NA>                                                                                                                                                                                                                                                                                                  Clearlake Shipping Pte Ltd v. Guvnor Shipping & Others, Aabar Holdings v. Glencore plc, The "Reluctant Ship Owner" Mortgages Enforcement Action, In re: Singamas and Container Cartel Litigation, In re: Glencore PLC SFO Investigation (perplexity)
11          Latham & Watkins LLP                                                                                                                                                                                     Ocean Network Express Pte. Ltd.  Latham & Watkins Advises Riverstone in Acquisition of Trailstone by Engelhart Commodities Trading Partners ( https://www.lw.com/ & Gemini), Latham & Watkins Advises Delfin Midstream on First Offshore Floating Vessel LNG Export Facility in the US (https://www.lw.com/ & Gemini), Latham & Watkins Advised Ocean Network Express in the Completion of Atlas’ Going Private Transaction(https://www.lw.com/ & Gemini), Latham & Watkins Advises Macquarie on 15-Year LNG Sale and Purchase Agreement With AMIGO LNG(https://www.lw.com/ & Gemini)
12                  Rajah & Tann                                                                                                                                                Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd                                                                                                           The Mount Apo [2019] 4 SLR 909, BWG v BWF [2020] 1 SLR 1296, PT Adidaya Energy Mandiri v MS First Capital Insurance Ltd [2022] 4 SLR 371, Sumifru Singapore Pte Ltd v Felix Santos Ishizuka and others [2022] SGHC 14, COSCO Shipping Specialized Carriers Co Ltd v PT OKI Pulp & Paper Mills and others [2023] SGHC 149, Sinopec International (Singapore) Pte Ltd v Bank of Communications Co Ltd [2024] 3 SLR 476 (sg.rajahtannasia.com)
13              Allen & Gledhill  JSW International Tradecorp Pte Ltd (JSW), ST Telemedia Global Data Centres (Telemedia Global Data Centres), BTS Tankers Pte Ltd, DBS Bank, United Overseas Bank (UOB), Oversea-Chinese Banking Corporation (OCBC)                                                                                                                          Public Prosecutor v. Captain George Vakirtzis, Public Prosecutor v. Captain Janusz Czubak, Five Ocean Corp v Cingler Ship Pte Ltd (PT Commodities & Energy Resources, intervener) [2016] 1 SLR 1159, Valency International Pte Ltd v JSW International Tradecorp Pte Ltd & Ors, Natixis Singapore Branch v Lim Oon Kuin and Ors, Hai Jiang 1401 Pte Ltd v Singapore Technologies Marine Ltd (allenandgledhill.com, chambers)
14                 Drew & Napier                                                                                                                                                                                       Metro Holdings Limited, Razer                                                                                                                                                                                                                      Suntech Power Holdings Co Ltd v GSF Capital Pte Ltd and Javier Romero, Ng Joo Soon v Dovechem Holdings Pte Ltd Re Brightoil Petroleum (S’pore) Pte Ltd [2022] SGHC 35, Voss Peer v APL Co Pte Ltd [2002] SGHC 81, Hyosung (HK) Ltd v Owners of the Ship or Vessel "Hilal I" [2000] SGHC 268 (drewnapier.com, googleai, chambers)
15               WongPartnership                                                                                                                                                           First Resources Limited, First Sponsor Group Limited, DBS                                                                                                                                                                                                                                                                                                                                                                   Timing Limited v Tay Toh Hin & Anor [2020] 5 SLR 974, Prime Shipping Corp v Public Prosecutor [2018] 4 SLR 795, Hin Leong Trading / Ocean Tankers Interpleader Proceedings (google)
16                  Helmsman LLC                                                                                                                                                               United Overseas Bank (UOB), Straits Bunkering Pte Ltd                                                                                                                                                                                                                                                                                                                                                                                Public Prosecutor v Richard Ouwehand and Others, Orion Shipping and Trading Ltd v Great Asia Maritime Ltd Vasily Trubnikov v Evgeny Volosov [2025] HKCFI 1576 (google)
17             Blackstone & Gold                                                                                                                                                                          Avani Resources Pte. Ltd, Alvari Pte. Ltd.                                                                                                                                                                                                                                                                                                                                  Marketlend Pty Ltd v QBE Insurance (Singapore) Pte Ltd Majestica Enterprises Ltd v Kams Singapore Pte Ltd $60 Million African Oil Project Arbitration (LCIA London), The Hin Leong Trading Collapse Fallout (gemini)
18         Braddell Brothers LLP                                                                                                                                                       BAFCO Singapore Pte. Ltd, The Singapore Medical Council (SMC)                                                                                                                                                                                                                                                                                                                                                                          BASF Intertrade AG Singapore Branch v H&C S Holding Pte Ltd PetroVietnam v PJSC Power Machines, Teunis Eigenraam v Ngng Pte Ltd Vessel Charterer Winding-Up Defense (gemini)
19     Joseph Tan Jude Benny LLP                                                                                                                                                                                FTI Consulting (Singapore) Pte. Ltd.                                                                                                The “Miracle Hope” [2020] SGHCR 3; BNP Paribas v Bandung Shipping Pte Ltd (Shweta International Pte Ltd and another, third parties) [2003] 3 SLR(R) 611; [2003] SGHC 111; Freight Connect (S) Pte Ltd v Paragon Shipping Pte Ltd [2015] SGCA 37; Zim Integrated Shipping Services Ltd and others v Dafni Igal and others [2010] SGCA 45; The “Rainbow Star” [2011] 3 SLR 1; [2011] SGHC 35 (jtjb.com), Paragon Shipping v Freight Connect (perplexity)
20  Dentons Rodyk & Davidson LLP                                                                                                                  Oversea-Chinese Banking Corporation (OCBC), Boustead Projects Limited, Thomson Medical Group (TMG)                                                                                                                                                                                                                                                                                                                   Government of Sri Lanka v Shipowners of Vessel X-Press Pearl and associated persons, Fastfreight Pte Ltd v Bulk Trident Shipping Ltd Case involving vessel GULF DEFFI, UniCredit Bank AG v Hin Leong Trading (Pte) Ltd (perplexity)
21               Oon & Bazul LLC                                                                                                                                 OCBC Bank (Oversea-Chinese Banking Corporation Limited), Winson Oil Trading Pte Ltd                                                                                                                                                                                                                        The Miracle Hope, Standard Chartered Bank (Singapore) Ltd v Maersk Tankers Singapore Pte Ltd (Winson Oil Trading Pte Ltd intervener) [2022] SGHC 242, The “STI Orchard” (Winson Oil Trading Pte Ltd intervener) [2022] SGHCR 6, he “Yue You 902” [2019] SGHC 106, The “Luna” and another appeal [2021] SGCA 84  (oonbazul.com)
22                   PDLegal LLC                                                                                                                                                                                Louis Dreyfus Company Asia Pte. Ltd.                                                                                                                                                                                                                                                                             The Owner and/or Demise Charterer of the Vessel “Marine Honour” v. The Owner and/or Demise Charterer of the Vessel “Vox Maxima” and Others (gemini), Acting for owners of SOV Southern Star (a DP3 vessel), Representing Japanese ship owner Masao Mizobuchi (perplexity)
23           Shook Lin & Bok LLP                                                                                                                                                                   Standard Chartered Bank (Singapore) Limited (SCB)                                                                                                                                                                              Duncan and Cameron Lindsay and another v Diablo Fortune Inc and another matter SGHC 172, Winson Oil Trading Pte Ltd v Oversea-Chinese Banking Corporation and Standard Chartered Bank (Singapore) Limited SGHC 220, Claim of more than USD80 million against OK Lim and his children, founder/ex-directors, and former senior employee of Hin Leong Trading (perplexity)

In [269]:
# p2 notable cases / disputes, then later check if the law firm acted for the client in the dispute

# extracting clients
# 0 : Trafigura Maritime Logistics Pte Ltd
# 1:  Golden Island Pte Ltd, Mitsui & Co Energy Trading Singapore (METS), Equatorial Marine Fuel Management Services
# 2:  Olam Global Agri Pte Ltd (subsidiary of olam group)
# 3: Trafigura Pte Ltd, SEFE Marketing & Trading Singapore Pte Limited
# 4: nan
# 5: nan
# 6: nan
# 7: nan
# 8 : nan
# 9: Trafigura Pte Ltd
# 10: glencore
# 11: nan
# 12: Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd
# 13: Valency International Pte Ltd
# 14: nan
# 15: nan
# 16: nan
# 17: nan
# 18: BASF Intertrade AG Singapore Branch
# 19: nan
# 20: nan
# 21: Winson Oil Trading Pte Ltd
# 22: nan
# 23: Winson Oil Trading Pte Ltd
# 24: nan
# 25: Winson Oil Trading Pte Ltd
# 26: nan
# 27: nan
# 28: nan
# 29: Antanium Resources Pte. Ltd.
# 30: Winson Oil Trading Pte Ltd
# 31: nan
# 32: nan
# 33: GP Global APAC Pte. Ltd.
# 34: Winson Oil Trading Pte Ltd, CYE
# 35: nan
# 36: nan
# 37: nan
# 38: nan

df2.rename(columns={'Notable Cases / Disputes': 'Clients'}, inplace=True)

# updated actual clients of the law firm from the notable cases / disputes column
df2.loc[[2,4,5,6,7,8,10,11,13,14,15,16,17,19,20,22,23,24,25,26,27,28,29,31,32,35,36,37,38, 30], 'Clients'] = pd.NA
df2.loc[0, 'Clients'] = 'Trafigura Maritime Logistics Pte Ltd'
df2.loc[1, 'Clients'] = 'Mitsui & Co Energy Trading Singapore (METS), Equatorial Marine Fuel Management Services'
df2.loc[3, "Clients"] = "Trafigura Pte Ltd"
df2.loc[9, "Clients"] = "Trafigura Pte Ltd"
df2.loc[12, "Clients"] = "Sumifru Singapore Pte Ltd"
df2.loc[18, "Clients"] = "BASF Intertrade AG Singapore Branch"
df2.loc[21, "Clients"] = "Winson Oil Trading Pte Ltd"   
df2.loc[33, "Clients"] = "GP Global APAC Pte. Ltd."
df2.loc[34, "Clients"] = "Winson Oil Trading Pte Ltd, CYE"

# concatenate the known clients with the clients from notable cases
def combine(row):
    a = row["Known Client Base"]
    b = row["Clients"]
    parts = []
    if not pd.isna(a):
        parts.append(a)
    if not pd.isna(b):
        parts.append(b)
    return ", ".join(parts) if parts else pd.NA

df2["Combined Clients"] = df2[["Known Client Base", "Clients"]].apply(combine, axis=1)

# keep the combined clients
df2 = df2.drop(columns=['Known Client Base', 'Clients'])
df2.rename(columns={'Combined Clients':'Known Clients'},inplace=True)

df2a = df2['Firm Name']
df2a = df2a.rename("Firm Name").to_frame()

df2b = df2['Known Clients'] #need to split the names before converting to dataframe

df2b

0                                                            Uniper Global Commodities SE Singapore Branch, China Merchants Energy Shipping (Singapore) Holding Pte. Ltd., Sinopec, Trafigura Maritime Logistics Pte Ltd
1                                                                                                                    BGN Energy, Mitsui & Co Energy Trading Singapore (METS), Equatorial Marine Fuel Management Services
2                                                                                                                                                                         ED&F Man Capital Markets (Singapore) Pte. Ltd.
3                                                                                                                                          Trafigura, Olam International, ICICI Bank Singapore Branch, Trafigura Pte Ltd
4                                                                                                                                                         Trafigura, BW Energy Holdings Pte Ltd, HSBC Singapore entities
5                                                                                                                                Glory Bulk Carriers Pte Ltd, TCC Group / Tai Chong Cheang Shipping (Singapore) Pte Ltd.
6                                                                                                                                                                Louis Dreyfus Company Asia Pte. Ltd. / LDC in Singapore
7                                                                                                                                                              Shell Singapore Pte. Ltd, Shell Eastern Trading (Pte) Ltd
8                                                                                                                                                                                                                   <NA>
9                                                                                                                                                                                                      Trafigura Pte Ltd
10                                                                                                                                                                                                                  <NA>
11                                                                                                                                                                                       Ocean Network Express Pte. Ltd.
12                                                                                                                       Sumifru Singapore Pte Ltd, Sinopec International (Singapore) Pte Ltd, Sumifru Singapore Pte Ltd
13    JSW International Tradecorp Pte Ltd (JSW), ST Telemedia Global Data Centres (Telemedia Global Data Centres), BTS Tankers Pte Ltd, DBS Bank, United Overseas Bank (UOB), Oversea-Chinese Banking Corporation (OCBC)
14                                                                                                                                                                                         Metro Holdings Limited, Razer
15                                                                                                                                                             First Resources Limited, First Sponsor Group Limited, DBS
16                                                                                                                                                                 United Overseas Bank (UOB), Straits Bunkering Pte Ltd
17                                                                                                                                                                            Avani Resources Pte. Ltd, Alvari Pte. Ltd.
18                                                                                                                    BAFCO Singapore Pte. Ltd, The Singapore Medical Council (SMC), BASF Intertrade AG Singapore Branch
19                                                                                                                                                                                  FTI Consulting (Singapore) Pte. Ltd.
20                                                                                                                    Oversea-Chinese Banking Corporation (OCBC), Boustead Projects Limited, Thomson Medical Group (TMG)
21                                                                                                       OCBC Bank (Oversea-Chinese Banking Corporation Limited), Winson Oil Trading Pte Ltd, Winson Oil Trading Pte Ltd
22                                                                                                                                                                                  Louis Dreyfus Company Asia Pte. Ltd.
23                                                                                                                                                                     Standard Chartered Bank (Singapore) Limited (SCB)
24                                                   Halcyon Agri Corporation Limited, Seraya Energy, KPMG, Mizuho Bank, Perennial Real Estate Holdings, Ho Lee Construction, WestBridge Ventures II Investment Holdings
25                                                                                                                                                                     Standard Chartered Bank (Singapore) Limited (SCB)
26                                                                                                                                        Atlantic Navigation Holdings (Singapore) Limited, Royal Global Exports Pte Ltd
27                                                                                                                                                     Louis Dreyfus Asia Pte Ltd / Louis Dreyfus Company Asia Pte. Ltd.
28                                                                                                                                                                                                                  <NA>
29                                                                                                                                                                                                                  <NA>
30                                                                                                                                                                                               Marina Offshore Pte Ltd
31                                                                                                                                                                                                                  <NA>
32                                                                                                                          Maybank Singapore (Maybank Singapore Limited), Petrochina International (Singapore) Pte. Ltd
33                                                                                                                     PricewaterhouseCoopers (PwC Singapore), GTP Advisory (GTP Advisory PAC), GP Global APAC Pte. Ltd.
34                                                              MS First Capital Insurance (Limited), United Overseas Bank (UOB), Unipec Singapore Pte. Ltd., GrabTaxi Holdings Pte Ltd, Winson Oil Trading Pte Ltd, CYE
35                    Argoglobal Underwriting Asia Pacific Pte Ltd, China Taiping Insurance (Singapore) Pte Ltd, Great American Insurance Company, MS First Capital Insurance Limited, QBE Insurance (Singapore) Pte Ltd
36                                                                                                                                                                                                                  <NA>
37                                                                                                                                                                                              Maersk Tankers Singapore
38                                                                                                                                                                                                                  <NA>
Name: Known Clients, dtype: object

In [270]:
# pillar 3
df3 = p3[['Institution Name', 'Known Clients']].copy()

# 0: Trafigura, Glencore, Gunvor, Vitol
# 1: nan
# 2: nan
# 3: nan
# 4: Marubeni, Trafigura, Glencore, Seatrium
# 5: Agrocorp International, Trafigura, Wilmar International Ltd, Louis Dreyfus Company, Rio Tinto
# 6: nan
# 7: Wilmar International, Musim Mas Group, Cargill, Sinar Mas Group, Barramundi Group
# 8: Trafigura, Gunvor, COFCO International, Bunge, Six One Commodities, Mercuria
# 9: {ok}
# 10: Vitol Group, Trafigura, Mercuria Energy Group, Gunvor Group, COFCO International
# 11: Vitol Group, Glencore, Gunvor Group, Olam Agri / Olam Group, Sinar Mas Group
# 12: Trafigura, Gunvor Group, Vitol Group, COFCO International
# 13: {ok}
# 14: {ok}
# 15: {ok}
# 16: {ok}
# 17: nan
# 18: {ok}
# 19: nan
# 20-41: nan
# 42: nan drop komgo reset index
# 43: nan
# 44: nan
# 45: nan
# 46: nan
# 47: nan
# 48: nan
# 49: The Daily Cut Pte Ltd, New & Novel Engineering Pte Ltd, Vyas Engineering Pte Ltd
# 50: nan
# 51: nan
# 52: nan
# 53: nan
# 54: nan
# 55-65: nan
# 66: nan
# 67: nan
# 68: {ok}

# update the active physical commodity trader clients in SG that the financiers lent to
df3.loc[[0], "Known Clients"] = "Trafigura, Glencore, Gunvor, Vitol"
df3.loc[[1,2,3,6,17,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67], "Known Clients"] = pd.NA
df3.loc[[4], "Known Clients"] = "Marubeni, Trafigura, Glencore, Seatrium"
df3.loc[[5], "Known Clients"] = "Agrocorp International, Trafigura, Wilmar International Ltd, Louis Dreyfus Company, Rio Tinto"
df3.loc[[7], "Known Clients"] = "Wilmar International, Musim Mas Group, Cargill, Sinar Mas Group, Barramundi Group"
df3.loc[[8], "Known Clients"] = 'Trafigura, Gunvor, COFCO International, Bunge, Six One Commodities, Mercuria'
df3.loc[10, 'Known Clients'] = 'Vitol Group, Trafigura, Mercuria Energy Group, Gunvor Group, COFCO International'
df3.loc[11, 'Known Clients'] = 'Vitol Group, Glencore, Gunvor Group, Olam Agri / Olam Group, Sinar Mas Group'
df3.loc[12, 'Known Clients'] = 'Trafigura, Gunvor Group, Vitol Group, COFCO International'
df3.loc[49, 'Known Clients'] = 'The Daily Cut Pte Ltd, New & Novel Engineering Pte Ltd, Vyas Engineering Pte Ltd'

# drop 42 and reset index
df3 = df3.drop(index=42)
df3 = df3.reset_index(drop=True)

df3a = df3['Institution Name']
df3a = df3a.rename('Firm Name').to_frame()

df3b = df3['Known Clients']
df3a

                                                           Firm Name
0                                                                ING
1                                                   Société Générale
2                                                        BNP Paribas
3                                                           Rabobank
4                                                 Standard Chartered
5                                                                DBS
6                                                               OCBC
7                                                                UOB
8                                                               MUFG
9                                                               SMBC
10                                                   Crédit Agricole
11                                                              HSBC
12                                                           Natixis
13                                   Bank of China, Singapore Branch
14                         China Construction Bank, Singapore Branch
15                                            ICBC, Singapore Branch
16                      Agricultural Bank of China, Singapore Branch
17         Shanghai Pudong Development Bank (SPDB), Singapore Branch
18                                       MUFG Bank, Singapore Branch
19                                  Macquarie Bank, Singapore Branch
20            Commonwealth Bank of Australia (CBA), Singapore Branch
21                                        ANZ Bank, Singapore Branch
22                     Westpac Banking Corporation, Singapore Branch
23                   National Australia Bank (NAB), Singapore Branch
24                                CIMB Bank Berhad, Singapore Branch
25  Maybank Singapore Ltd / Malayan Banking Berhad, Singapore Branch
26                                 RHB Bank Berhad, Singapore Branch
27                         Bank of East Asia (BEA), Singapore Branch
28                             State Bank of India, Singapore Branch
29                                      DZ Bank AG, Singapore Branch
30                                Deutsche Bank AG, Singapore Branch
31                                  Commerzbank AG, Singapore Branch
32                            Citibank N.A. / Citi, Singapore Branch
33                                   Goldman Sachs, Singapore Branch
34                             JPMorgan Chase Bank, Singapore Branch
35                                            BBVA, Singapore Branch
36                                 Bank of America, Singapore Branch
37                                                           Ossiano
38                                                             Copap
39                                                 Tradeflow Capital
40                                                           Mercore
41                                                          Audentia
42                                                  ED&F Man Capital
43                                                         Czarnikow
44                                                  Sucden Financial
45                                                      Drip Capital
46                                               Incomlend Pte. Ltd.
47                    GXS Capital Pte. Ltd. (f.k.a. Validus Capital)
48                          FS Capital Pte. Ltd. (Funding Societies)
49                                                   IFS Capital Ltd
50                              Straits Financial Services Pte. Ltd.
51          GB Helios Pte. Ltd. (f.k.a. Goldbell Financial Services)
52                           Nomura Securities (Singapore) Pte. Ltd.
53                                                       ADM Capital
54                                            Hong Leong Finance Ltd
55                                          EASTvine Capital Pte Ltd
56                                    Sing Investments & Finance Ltd
57                                       ZMA Smart Capital Pte. Ltd.
58                                MUFG Trading (Singapore) Pte. Ltd.
59                                        ORIX Leasing Singapore Ltd
60                                  Capital Match Platform Pte. Ltd.
61                                        SeaTown Holdings Pte. Ltd.
62                                             Modifi Asia Pte. Ltd.
63                                        StoneX Financial Pte. Ltd.
64                                Horizon Capital AG (Singapore rep)
65                               Hartree Partners Singapore Pte. Ltd
66                                        Traxys Singapore Pte. Ltd.
67                         Freepoint Commodities Singapore Pte. Ltd.

In [ ]:
# split the df2 Known Clients into its own pd.series
def split_comma_list(cell):
    if not isinstance(cell, str) or not cell.strip():
        return []
    parts = re.split(r",\s*(?![^()]*\))", cell)
    return [p.strip() for p in parts]

# split each row's comma-separated string into a list
split_series = df2b.dropna().apply(split_comma_list)

# explode: each item in the list becomes its own row
exploded = split_series.explode().reset_index(drop=True)

# turn into a DataFrame with one column, one entity name per row
df2_clients_df = pd.DataFrame({"Firm Name": exploded})
df2_clients_df

In [ ]:
# split the df3 Known Clients into its own pd series

# split each row's comma-separated string into a list
split_series = df3b.dropna().apply(split_comma_list)

# explode: each item in the list becomes its own row
exploded = split_series.explode().reset_index(drop=True)

# turn into a DataFrame with one column, one entity name per row
df3_clients_df = pd.DataFrame({"Firm Name": exploded})
df3_clients_df

In [ ]:
# vertically concatenate firms from df1, df2a, df2 clients, df3a, df3 clients
#all df1, df2a, df3a are already dataframes before concat

df123 = pd.concat([df1, df2a, df2_clients_df, df3a, df3_clients_df], ignore_index=True)

# confirm structure before doing anything else
print(df123.columns.tolist())
print(df123.shape)

# df123 contains all the firm names from traders, law firms, lender
# cleaning column
# lower all
df123["Firm Name"] = df123["Firm Name"].str.lower()

# remove regex, multispace, pte, ltd, limited
import re
irrelevant_regex = re.compile(r'[^a-z0-9\s]')
multispace_regex = re.compile(r'\s\s+')
def assign_no_symbols_name(df):
    df['name'] = (df['Firm Name'].str.replace(irrelevant_regex, ' ', regex=True)
                                      .str.replace(multispace_regex, ' ', regex=True)
                                      .str.replace(r"\bpte\b|\bltd\b|\blimited\b", "", regex=True))
    return df

df123 = assign_no_symbols_name(df123)

df123

In [ ]:
# save df123
#df123.to_csv(r"D:\commo\code\entity_resolution\df123_train.csv", index=False)

In [ ]:
# classification method 3: active learning classification using dedupe python library
# ran as script : active_classification.py

In [ ]:
# clustering on trained data
import pandas as pd
import dedupe
import os

# `partition` will return sets of records that dedupe believes are all referring to the same entity.

# format df123 into dict struct {row_id: {field: value}}
df123 = pd.read_csv(r"D:\commo\code\entity_resolution\df123_train.csv") # df134_train is for training
data_d = {}
for idx, row in df123.iterrows():
    if isinstance(row["name"], str) and row["name"].strip():
        data_d[idx] = {"name": row["name"]}

# If a settings file already exists, we'll just load that and skip training
settings_file = r"D:\commo\code\entity_resolution\dedupe_settings"
if os.path.exists(settings_file):
    print("reading from", settings_file)
    with open(settings_file, "rb") as f:
        deduper = dedupe.StaticDedupe(f)
else:
    raise FileNotFoundError(f"No trained settings found at {settings_file}. Run the training script first.")

print("clustering...")
# clustered_dupes = deduper.partition(data_d, 0.5) #284 duplicate sets
clustered_dupes = deduper.partition(data_d, 0.5)  
#clustered_dupes = deduper.partition(data_d, 0.9)  # 349 duplicate sets

print("# duplicate sets", len(clustered_dupes))

In [ ]:
# ## Writing Results
import csv
# Write our original data back out to a CSV with a new column called
# 'Cluster ID' which indicates which records refer to each other.

cluster_membership = {}
for cluster_id, (records, scores) in enumerate(clustered_dupes):
    for record_id, score in zip(records, scores):
        cluster_membership[record_id] = {
            "Cluster ID": cluster_id,
            "confidence_score": score,
        }

df123['Cluster ID'] = df123.index.map(lambda i: cluster_membership.get(i, {}).get('Cluster ID'))
df123['Match Confidence'] = df123.index.map(lambda i: cluster_membership.get(i, {}).get('confidence_score'))

output_file = r"D:\commo\code\entity_resolution\clustering_output.csv"
df123.to_csv(output_file, index=False)
print(f"saved to {output_file}")

In [ ]:
# check out the output
import pandas as pd
clustered_entities = pd.read_csv(r'D:\commo\code\entity_resolution\clustering_output.csv')

print(clustered_entities[clustered_entities["Cluster ID"] == 283].index)
clustered_entities[clustered_entities["Cluster ID"] == 283]

In [ ]:
# cluster: index = standardized name
# checked all the {stays the same}
# input into df123
import pandas as pd
df123 = pd.read_csv(r"D:\commo\code\entity_resolution\df123_train.csv")

# 0: [0, 151, 154, 155, 163, 292, 297, 301, 310, 317, 327, 336, 341, 342] = 'trafigura group'
df123.loc[[0, 151, 154, 155, 163, 292, 297, 301, 310, 317, 327, 336, 341, 342], ['name']] = 'trafigura group'
# 1: [294, 311, 319, 329, 333, 337] = 'gunvor group'
df123.loc[[294, 311, 319, 329, 333, 337], ["name"]] = "gunvor group"
# 2: [295, 316, 326, 331, 338] = 'vitol group'
df123.loc[[295, 316, 326, 331, 338], ["name"]] = "vitol group"
# 3: [315, 318, 328] = 'mercuria energy group'
df123.loc[[315, 318, 328], ["name"]] = "mercuria energy group"
# 4: [4, 160, 193, 205] = 'louis dreyfus company asia'
df123.loc[[4, 160, 193, 205], ["name"]] = "louis dreyfus company asia"
#    [303, 325] = 'louis dreyfus company'
df123.loc[[303, 325], ["name"]] = "louis dreyfus company"
# 5: [5, 302, 305, 322] = 'wilmar international'
df123.loc[[5, 302, 305, 322], ["name"]] = "wilmar international"
# 6: [312, 323, 330, 339] = 'cofco international'
df123.loc[[312, 323, 330, 339], ["name"]] = "cofco international"
#    [7] = 'cofco international singapore'
df123.loc[[7], ["name"]] = "cofco international singapore"
# 9: [293, 298, 332] = 'glencore'
df123.loc[[293, 298, 332], ["name"]] = "glencore"
#    [9] = 'glencore singapore'
df123.loc[[9], ["name"]] = "glencore singapore"
# 11: [12, 296] = 'marubeni corporation'
df123.loc[[12, 296], ["name"]] = "marubeni corporation"
# 12: [15, 162] = 'shell eastern trading'
df123.loc[[15, 162], ["name"]] = "shell eastern trading"
# 13: [69, 161] = 'shell singapore'
df123.loc[[69, 161], ["name"]] = "shell singapore"
# 14: [19, 300] = 'agrocorp international'
df123.loc[[19, 300], ["name"]] = "agrocorp international"
# 15: [22, 176] = 'first resources'
df123.loc[[22, 176], ["name"]] = "first resources"
# 16: [31, 290] = 'traxys singapore'
df123.loc[[31, 290], ["name"]] = "traxys singapore"
# 17: [95, 180] = 'straits bunkering'
df123.loc[[95, 180], ["name"]] = "straits bunkering"
# 18: [57, 214, 340] = 'unipec singapore'
df123.loc[[57, 214, 340], ["name"]] = "unipec singapore"
# 19: [100, 102] = 'bary chemical'
df123.loc[[100, 102], ["name"]] = "bary chemical"
# 20: 150 = 'ed&f man capital markets singapore', 266 = 'ed&f man capital'
df123.loc[[150], ["name"]] = "ed&f man capital markets singapore"
df123.loc[[266], ["name"]] = "ed&f man capital"
# 21: [165, 167] = 'sumifru singapore'
df123.loc[[165, 167], ["name"]] = "sumifru singapore"
# 22: [171, 178, 229] = 'dbs bank'
df123.loc[[171, 178, 229], ["name"]] = "dbs bank"
# 23: [172, 179, 213, 231] = 'united overseas bank uob'
df123.loc[[172, 179, 213, 231], ["name"]] = "united overseas bank uob"
# 24: [173, 187, 190, 230] = 'oversea-chinese banking corporation ocbc'
df123.loc[[173, 187, 190, 230], ["name"]] = "oversea-chinese banking corporation ocbc"
# 25: [191, 192, 216] = 'winson oil trading'
df123.loc[[191, 192, 216], ["name"]] = "winson oil trading"
# 26: [194, 202] = 'standard chartered bank singapore scb', [228] = 'standard chartered'
df123.loc[[194, 202], ["name"]] = "standard chartered bank singapore scb"
df123.loc[[228], ["name"]] = "standard chartered"
# 27: [212, 221] = 'ms first capital insurance'
df123.loc[[212, 221], ["name"]] = "ms first capital insurance"
# 34: 10 = 'archer-daniels-midland singapore'
df123.loc[[10], ["name"]] = "archer-daniels-midland singapore"
# 35: 13 = 'mitsui & co'
df123.loc[[13], ["name"]] = "mitsui & co"
# 69: 51 = 'samsung c&t singapore'
df123.loc[[51], ["name"]] = "samsung c&t singapore"
# 71: 54 = 'sumitomo corporation asia & oceania'
df123.loc[[54], ["name"]] = "sumitomo corporation asia & oceania"
# 81: 65 = 'banpu minerals singapore'
df123.loc[[65], ["name"]] = "banpu minerals singapore"
# 85: 70 = 'summit energy & resources'
df123.loc[[70], ["name"]] = "summit energy & resources"
# 86: 71 = 'pertamina international marketing & distribution'
df123.loc[[71], ["name"]] = "pertamina international marketing & distribution"
# 88: 73 = 'eneos oil & energy asia'
df123.loc[[73], ["name"]] = "eneos oil & energy asia"
# 93: 78 = 'gce agri'
df123.loc[[78], ["name"]] = "gce agri"
# 96: 81 = 'unifood int'l'
df123.loc[[81], ["name"]] = "unifood international"
# 101: 86 = 'aaa oils & fats'
df123.loc[[86], ["name"]] = "aaa oils & fats"
# 114: 101 = 'oriental energy'
df123.loc[[101], ["name"]] = "oriental energy"
# 115: 103 = 'mahkota oils & fats'
df123.loc[[103], ["name"]] = "mahkota oils & fats"
# 117: 105 = 'holman fenwick willan hfw'
df123.loc[[105], ["name"]] = "holman fenwick willan hfw"
# 118: 106 = 'clyde & co'
df123.loc[[106], ["name"]] = "clyde & co"
# 120: 108 = 'watson farley & williams'
df123.loc[[108], ["name"]] = "watson farley & williams"
# 121: 109 = 'ince & co singapore'
df123.loc[[109], ["name"]] = "ince & co singapore"
# 127: 115 = 'latham & watkins llp'
df123.loc[[115], ["name"]] = "latham & watkins llp"
# 128: 116 = 'rajah & tann'
df123.loc[[116], ["name"]] = "rajah & tann"
# 129: 117 = 'allen & gledhill'
df123.loc[[117], ["name"]] = "allen & gledhill"
# 130: 118 = 'drew & napier'
df123.loc[[118], ["name"]] = "drew & napier"
# 133: 121 = 'blackstone & gold'
df123.loc[[121], ["name"]] = "blackstone & gold"
# 136: 124 = 'dentons rodyk & davidson llp'
df123.loc[[124], ["name"]] = "dentons rodyk & davidson llp"
# 137: 125 = 'oon & bazul llc'
df123.loc[[125], ["name"]] = "oon & bazul llc"
# 139: 127 = 'shook lin & bok llp'
df123.loc[[127], ["name"]] = "shook lin & bok llp"
# 145: 133 = 'dunbar & lim chambers llc'
df123.loc[[133], ["name"]] = "dunbar & lim chambers llc"
# 146: 134 = 'haridass ho & partners'
df123.loc[[134], ["name"]] = "haridass ho & partners"
# 148: 136 = 'pk wong & nair llc'
df123.loc[[136], ["name"]] = "pk wong & nair llc"
# 156: 144 = 'china merchants energy shipping holding singapore'
df123.loc[[144], ["name"]] = "china merchants energy shipping holding singapore"
# 159: 148 = 'mitsui & co energy trading singapore (mets)'
df123.loc[[148], ["name"]] = "mitsui & co energy trading singapore (mets)"
# 161: 152 = 'olam group'
df123.loc[[152], ["name"]] = "olam group"
# 166: 159 = 'tai chong cheang shipping singapore'
df123.loc[[159], ["name"]] = "tai chong cheang shipping singapore"
# 169: 168 = 'jsw international tradecorp'
df123.loc[[168], ["name"]] = "jsw international tradecorp"
# 170: 169 = 'st telemedia global data centres'
df123.loc[[169], ["name"]] = "st telemedia global data centres"
# 195: 207 = 'maybank singapore'
df123.loc[[207], ["name"]] = "maybank singapore"
# 198: 210 = 'gtp advisory pac'
df123.loc[[210], ["name"]] = "gtp advisory pac"
# 208: 225 = 'societe generale'
df123.loc[[225], ["name"]] = "societe generale"
# 215: 234 = 'credit agricole'
df123.loc[[234], ["name"]] = "credit agricole"
# 230: 249 = 'malayan banking berhad singapore'
df123.loc[[249], ["name"]] = "malayan banking berhad singapore"
# 237: 256 = 'citibank singapore'
df123.loc[[256], ["name"]] = "citibank singapore"
# 251: 271 = 'gxs capital'
df123.loc[[271], ["name"]] = "gxs capital"
# 252: 272 = 'fs capital'
df123.loc[[272], ["name"]] = "fs capital"
# 255: 275: 'gb helios'
df123.loc[[275], ["name"]] = "gb helios"
# 7, 8, 10, 28, 29, 30, 31, 32, 33, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55
# 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 70, 72, 73, 74, 75, 76, 77, 78, 79, 80, 82, 83, 84, 87, 89, 90, 91
# 92, 94, 95, 97, 98, 99, 100, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 116, 119, 122, 123, 124, 125, 126, 131, 132
# 134, 135, 138, 140, 141, 142, 143, 144, 147, 149, 150, 151, 152, 153, 154, 155, 157, 158, 160, 162, 163, 164, 165, 167, 168, 171
# 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 184, 185, 186, 187, 188, 189, 190, 191, 192, 194, 196, 197, 199, 200, 201, 202
# 203, 204, 205, 206, 207, 209, 210, 213, 214, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 231, 232
# 233, 234, 235, 236, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 253, 254, 256, 257, 258, 259, 260
# 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 279, 280, 281, 282, 283
# 277: 334 = 'olam agri'
df123.loc[[334], ["name"]] = "olam agri"
# 278: 343 = 'trafigura beheer bv'
df123.loc[[343], ["name"]] = "trafigura beheer bv"
# 272: 306: 'musim mas holdings'
df123.loc[[306], ["name"]] = "musim mas holdings"

In [ ]:
# remove 'branch'
df123['Firm Name'] = df123['Firm Name'].str.replace(r'\bbranch\b', '', regex=True)
# remove all duplicates 349 rows
df123.drop(columns=['Firm Name'], inplace = True)
df123.rename({'name':'Firm Name'},inplace=True)
df123 = df123.drop_duplicates() #288

In [ ]:
# save the no duplicates version
df123.to_csv(r"D:\commo\code\entity_resolution\no_dupe_firms.csv", index=False)

In [271]:
# remove duplicates again 
no_dupes = pd.read_csv(r"D:\commo\code\entity_resolution\no_dupe_firms.csv")
no_dupes['name'] = no_dupes['name'].str.strip()
no_dupes = no_dupes.drop_duplicates(subset='name')
no_dupes.to_csv(r"D:\commo\code\entity_resolution\no_dupe_firms.csv", index=False)
no_dupes

                                                       name
0                                           trafigura group
1                                                vitol asia
2                                         mercuria holdings
3                                          gunvor singapore
4                                louis dreyfus company asia
5                                      wilmar international
6                                                olam group
7                             cofco international singapore
8                             cargill asia pacific holdings
9                                        glencore singapore
10                         archer-daniels-midland singapore
11                                               bunge asia
12                                     marubeni corporation
13                                              mitsui & co
14                                ptt international trading
15                                    shell eastern trading
16                                          bp asia pacific
17         totalenergies marketing asia pacific middle east
18                               sinochem international oil
19                                   agrocorp international
20                                golden agri international
21                                       musim mas holdings
22                                          first resources
23                                       aavanti industries
24                                       olam agri holdings
25                                         gerald singapore
26                                         pacific basin sg
27                                             wilmar sugar
28                              sahara energy international
29                                  socar trading singapore
30                                    wogen south east asia
31                                         traxys singapore
32                                 trafigura carbon trading
33                                                      ixm
34                              aditya birla global trading
35                             tata international singapore
36                                          vinmar overseas
37                                                helm asia
38                                        sino gas holdings
39                            posco international singapore
40                                               oilmar sgp
41                                          nala renewables
42                             straits energy resources bhd
43                                  indofood agri resources
44                                      adaro international
45                                   hg metal manufacturing
46                                 sd guthrie international
47                                               agrex asia
48                                         lx international
49                            hyundai corporation singapore
50                  woodside energy australia asia holdings
51                                    samsung c&t singapore
52                                         sinopec fuel oil
53                                              sojitz asia
54                      sumitomo corporation asia & oceania
55                                        citic commodities
56                                 petrochina international
57                                         unipec singapore
58                                    sinopec international
59                                  sk energy international
60                                         itochu singapore
61                                      gs global singapore
62                                  cipta commodity trading
63                                        davis commodities
64                                             om materials
65                                 banpu minerals singapore
66                                 hd hyundai oil singapore
67                               toyota tsusho asia pacific
68                                 chalco trading singapore
69                                          shell singapore
70                                summit energy & resources
71         pertamina international marketing & distribution
72                                   idemitsu international
73                                  eneos oil & energy asia
74                                  cosmo oil international
75                                    jfe shoji corporation
76                             century commodities solution
77                                       rawsteel minmetals
78                                                 gce agri
79                                      dkc steel singapore
80                                                mri group
81                                    unifood international
82                            noble resources international
83                                            cemcoa energy
84                                  interchem manufacturing
85                 mitsubishi corporation rtm international
86                                          aaa oils & fats
87                                 triland metals singapore
88                                          ginga petroleum
89                                           concord energy
90                                         pacific minerals
91                                             trimex group
92                                     kz trading singapore
93                                      petraco oil company
94                                the straits international
95                                        straits bunkering
96                                           pacific energy
97                                           quantum global
98                                        meridian equities
99                               swan international holding
100                                           bary chemical
101                                         oriental energy
102                                     mahkota oils & fats
103                                              reed smith
104                               holman fenwick willan hfw
105                                              clyde & co
106                                      stephenson harwood
107                                watson farley & williams
108                                     ince & co singapore
109                                   norton rose fulbright
110                                          baker mckenzie
111                                     squire patton boggs
112                                          hill dickinson
113                                         mayer brown llp
114                                    latham & watkins llp
115                                            rajah & tann
116                                        allen & gledhill
117                                           drew & napier
118                                         wongpartnership
119                                            helmsman llc
120                                       blackstone & gold
121                                   braddell brothers llp
122                               joseph tan jude benny llp
123                            dentons rodyk & davidson llp
124                                         oon & bazul llc
125                                             pdlegal llc
126                                     shook lin & bok llp
127                                    tsmp law corporation
128                                          virtus law llp
129                                           dennismathiew
130                                           asialegal llc
131                                      christopher lau sc
132                               dunbar & lim chambers llc
133                                  haridass ho & partners
134                               gill arbitration services
135                                      pk wong & nair llc
136                                 providence law asia llc
137                                    lvm law chambers llc
138                                        incisive law llc
139                                        damodara ong llc
140                                      focus law asia llc
141                                        resource law llc
142           uniper global commodities se singapore branch
143       china merchants energy shipping holding singapore
144                                                 sinopec
145                            trafigura maritime logistics
146                                              bgn energy
147             mitsui & co energy trading singapore (mets)
148              equatorial marine fuel management services
149                      ed&f man capital markets singapore
150                             icici bank singapore branch
151                                      bw energy holdings
152                                 hsbc singapore entities
153                                     glory bulk carriers
154                     tai chong cheang shipping singapore
155                                   ocean network express
156                                       sumifru singapore
157                         sinopec international singapore
158                             jsw international tradecorp
159                        st telemedia global data centres
160                                             bts tankers
161                                                dbs bank
162                                united overseas bank uob
163                oversea-chinese banking corporation ocbc
164                                          metro holdings
165                                                   razer
166                                     first sponsor group
167                                         avani resources
168                                                  alvari
169                                         bafco singapore
170                       the singapore medical council smc
171                     basf intertrade ag singapore branch
172                                fti consulting singapore
173                                       boustead projects
174                               thomson medical group tmg
175                                      winson oil trading
176                   standard chartered bank singapore scb
177                                halcyon agri corporation
178                                           seraya energy
179                                                    kpmg
180                                             mizuho bank
181                          perennial real estate holdings
182                                     ho lee construction
183              westbridge ventures ii investment holdings
184                  atlantic navigation holdings singapore
185                                    royal global exports
186                                         marina offshore
187                                       maybank singapore
188                      petrochina international singapore
189                    pricewaterhousecoopers pwc singapore
190                                        gtp advisory pac
191                                          gp global apac
192                              ms first capital insurance
193                                       grabtaxi holdings
194                                                     cye
195                    argoglobal underwriting asia pacific
196                       china taiping insurance singapore
197                        great american insurance company
198                                 qbe insurance singapore
199                                maersk tankers singapore
200                                                     ing
201                                        societe generale
202                                             bnp paribas
203                                                rabobank
204                                      standard chartered
205                                                    mufg
206                                                    smbc
207                                         credit agricole
208                                                    hsbc
209                                                 natixis
210                          bank of china singapore branch
211                china construction bank singapore branch
212                                   icbc singapore branch
213             agricultural bank of china singapore branch
214  shanghai pudong development bank spdb singapore branch
215                              mufg bank singapore branch
216                         macquarie bank singapore branch
217     commonwealth bank of australia cba singapore branch
218                               anz bank singapore branch
219            westpac banking corporation singapore branch
220            national australia bank nab singapore branch
221                       cimb bank berhad singapore branch
222                        malayan banking berhad singapore
223                        rhb bank berhad singapore branch
224                  bank of east asia bea singapore branch
225                    state bank of india singapore branch
226                             dz bank ag singapore branch
227                       deutsche bank ag singapore branch
228                         commerzbank ag singapore branch
229                                      citibank singapore
230                          goldman sachs singapore branch
231                    jpmorgan chase bank singapore branch
232                                   bbva singapore branch
233                        bank of america singapore branch
234                                                 ossiano
235                                                   copap
236                                       tradeflow capital
237                                                 mercore
238                                                audentia
239                                        ed&f man capital
240                                               czarnikow
241                                        sucden financial
242                                            drip capital
243                                               incomlend
244                                             gxs capital
245                                              fs capital
246                                             ifs capital
247                              straits financial services
248                                               gb helios
249                             nomura securities singapore
250                                             adm capital
251                                      hong leong finance
252                                        eastvine capital
253                                sing investments finance
254                                       zma smart capital
255                                  mufg trading singapore
256                                  orix leasing singapore
257                                  capital match platform
258                                        seatown holdings
259                                             modifi asia
260                                        stonex financial
261                        horizon capital ag singapore rep
262                              hartree partners singapore
263                         freepoint commodities singapore
264                                                glencore
265                                            gunvor group
266                                             vitol group
267                                                seatrium
268                                   louis dreyfus company
269                                               rio tinto
270                                                 cargill
271                                         sinar mas group
272                                        barramundi group
273                                     cofco international
274                                                   bunge
275                                     six one commodities
276                                   mercuria energy group
277                                                    vale
278                                   olam food ingredients
279                                               olam agri
280                                     trafigura beheer bv
281                                 mercuria energy trading
282                                           the daily cut
283                                   new novel engineering
284                                        vyas engineering
285                                          the prax group

In [272]:
# p1: replace the commodity firm names with standardized version
p1 = p1[p1["Company Name"] != "Bary Chemical Pte Ltd"]
p1 = p1.reset_index(drop=True)
p1["Company Name"] = no_dupes.iloc[:103]['name'].values
p1
# save p1
p1.to_csv(r"D:\commo\code\cleaned_pillars\standardized_pillar1.csv", index=False)

In [273]:
# p2 replace the law firm names with standardized version
p2["Firm Name"] = no_dupes.iloc[103:142]['name'].values
# p2 replace the law firm clients' with actual clients and standardized version of actual clients
p2["Known Client Base"] = df2b

# for known client base
import re
def split_comma_list(cell):
    if not isinstance(cell, str) or not cell.strip():
        return []
    parts = re.split(r",\s*(?![^()]*\))", cell)
    return [p.strip() for p in parts]

# no_dupes.iloc[142:200]
split_series = p2["Known Client Base"].apply(split_comma_list)
exploded = split_series.explode()

# build the exploded DataFrame with an explicit column for the original p2 index
df2_clients_df = pd.DataFrame({"Known Client Base": exploded})
df2_clients_df['p2_index'] = df2_clients_df.index  # save original row link BEFORE resetting
df2_clients_df = df2_clients_df.reset_index(drop=True)  # now safe to give fresh 0,1,2... index for linkage

# clean the column
df2_clients_df["Known Client Base"] = (
    df2_clients_df["Known Client Base"]
    .str.lower()
    .str.replace(r"\bpte\.?\b|\bltd\.?\b|\blimited\.?\b", "", regex=True)
    .str.replace(r"[()]", "", regex=True)  # remove ( and ) but keep the words inside
    .str.replace(r"\.", "", regex=True)  # remove periods
    .str.replace(r"\s+", " ", regex=True)  # collapse multiple spaces
    .str.strip()
)
# index: standardized names
# 1: china merchants energy shipping holding singapore
df2_clients_df.loc[1, 'Known Client Base'] = 'china merchants energy shipping holding singapore'
# 8: trafigura group
df2_clients_df.loc[8, "Known Client Base"] = "trafigura group"
# 9: olam group
df2_clients_df.loc[9, "Known Client Base"] = "olam group"
# 11,12: trafigura group
df2_clients_df.loc[[11, 12], "Known Client Base"] = "trafigura group"
# 16: tai chong cheang shipping singapore
df2_clients_df.loc[16, "Known Client Base"] = "tai chong cheang shipping singapore"
# 17: louis dreyfus company asia
df2_clients_df.loc[17, "Known Client Base"] = "louis dreyfus company asia"
# 21: trafigura group
df2_clients_df.loc[21, "Known Client Base"] = "trafigura group"
# 28: st telemedia global data centres
df2_clients_df.loc[28, "Known Client Base"] = "st telemedia global data centres"
# 37: dbs bank
df2_clients_df.loc[37, "Known Client Base"] = "dbs bank"
# 49: oversea-chinese banking corporation ocbc
df2_clients_df.loc[49, "Known Client Base"] = "oversea-chinese banking corporation ocbc"
# 64: louis dreyfus company asia
df2_clients_df.loc[64, "Known Client Base"] = "louis dreyfus company asia"
# 69: maybank singapore
df2_clients_df.loc[69, "Known Client Base"] = "maybank singapore"
# 72: gtp advisory pac
df2_clients_df.loc[72, "Known Client Base"] = "gtp advisory pac"

def safe_join(names):
    clean = [n for n in names if isinstance(n, str) and n.strip()]
    return ', '.join(sorted(set(clean))) if clean else None

regrouped = df2_clients_df.groupby('p2_index')['Known Client Base'].apply(safe_join)
# cross check regrouped with p2['known client base'] before replacing p2 with regrouped
p2["Known Client Base"] = regrouped
# save p2
p2.to_csv(r"D:\commo\code\cleaned_pillars\standardized_pillar2.csv", index=False)

In [274]:
# cross check df3a with nodupes
# clean the financier name col
df3a["Firm Name"] = (df3a["Firm Name"].str.lower()
                     .str.replace(r"\,", "", regex=True)  # remove commas
                     .str.replace(r"\bpte\.?\b|\bltd\.?\b|\blimited\.?\b", "", regex=True)
                     .str.replace(r"\.", "", regex=True)  # remove periods
                     .str.replace(r"[()]", "", regex=True)  # remove ( and ) but keep the words inside
                     .str.replace(r"\s+", " ", regex=True)
                     .str.strip())  # collapse multiple spacesstr.strip()
# index: standardized (crosschecked the standardized versino with no dupes)
# 1: societe generale
df3a.loc[1, "Firm Name"] = "societe generale"
# 5: dbs bank
df3a.loc[5, "Firm Name"] = "dbs bank"
# 6: oversea-chinese banking corporation ocbc
df3a.loc[6, "Firm Name"] = "oversea-chinese banking corporation ocbc"
# 7: united overseas bank uob
df3a.loc[7, "Firm Name"] = "united overseas bank uob"
# 10: credit agricole
df3a.loc[10, "Firm Name"] = "credit agricole"
# 25: malayan banking berhad singapore
df3a.loc[25, "Firm Name"] = "malayan banking berhad singapore"
# 32: citibank singapore
df3a.loc[32, "Firm Name"] = "citibank singapore"
# 47: gxs capital
df3a.loc[47, "Firm Name"] = "gxs capital"
# 48: fs capital
df3a.loc[48, "Firm Name"] = "fs capital"
# 51: gb helios
df3a.loc[51, "Firm Name"] = "gb helios"
# drop komgo and reset index
p3 = p3[p3["Institution Name"] != "Komgo"]
p3 = p3.reset_index(drop=True)
# replace p3 firm name with df3a
p3['Institution Name'] = df3a

# cross check df3b with no dupes
# p3 replace the financier firm clients' with actual clients and standardized version of actual clients
p3["Known Clients"] = df3b

# for known client
import re
def split_comma_list(cell):
    if not isinstance(cell, str) or not cell.strip():
        return []
    parts = re.split(r",\s*(?![^()]*\))", cell)
    return [p.strip() for p in parts]
split_series = p3["Known Clients"].apply(split_comma_list)
exploded = split_series.explode() # has indices

# build the exploded DataFrame with an explicit column for the original p2 index
df3_clients_df = pd.DataFrame({"Known Clients": exploded})
df3_clients_df["p3_index"] = (df3_clients_df.index)  # save original row link BEFORE resetting
df3_clients_df = df3_clients_df.reset_index(drop=True)  # now safe to give fresh 0,1,2... index for linkage

# clean the column
df3_clients_df["Known Clients"] = (
    df3_clients_df["Known Clients"]
    .str.lower()
    .str.replace(r"\bpte\.?\b|\bltd\.?\b|\blimited\.?\b", "", regex=True)
    .str.replace(r"[()]", "", regex=True)  # remove ( and ) but keep the words inside
    .str.replace(r"\.", "", regex=True)  # remove periods
    .str.replace(r"\s+", " ", regex=True)  # collapse multiple spaces
    .str.strip()
)
# cross check df3_clients_df james with no dupes
# 2, 23: gunvor group
df3_clients_df.loc[[2, 23], "Known Clients"] = "gunvor group"
# 3: vitol group
df3_clients_df.loc[3, "Known Clients"] = "vitol group"
# 7: marubeni corporation
df3_clients_df.loc[7, "Known Clients"] = "marubeni corporation"
# 8, 12, 22, 29, 39, 48, 54: trafigura group
df3_clients_df.loc[[0,8, 12, 22, 29, 39, 48, 54], "Known Clients"] = "trafigura group"
# 18: musim mas holdings
df3_clients_df.loc[18, "Known Clients"] = "musim mas holdings"
# 37: louis dreyfus company
df3_clients_df.loc[37, "Known Clients"] = "louis dreyfus company"
# 46: olam agri holdings
df3_clients_df.loc[46, "Known Clients"] = "olam agri holdings"
# 55: trafigura beheer bv
df3_clients_df.loc[55, "Known Clients"] = "trafigura beheer bv"
def safe_join(names):
    clean = [n for n in names if isinstance(n, str) and n.strip()]
    return ", ".join(sorted(set(clean))) if clean else None

regrouped = df3_clients_df.groupby("p3_index")["Known Clients"].apply(safe_join)
p3['Known Clients'] = regrouped
# save p3
p3.to_csv(r"D:\commo\code\cleaned_pillars\standardized_pillar3.csv", index=False)

In [ ]:
# no_dupes will be used for assigning unique IDs