In [1]:
import pandas as pd

# display columns without truncation
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

# display rows without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.expand_frame_repr", False)

In [17]:
edge_list = pd.read_csv(r"D:\commo\code\4_kumu_struct\edge_list.csv")
# standardized pillars
node1 = pd.read_csv(r"D:\commo\code\4_kumu_struct\node_list1.csv")
node2 = pd.read_csv(r"D:\commo\code\4_kumu_struct\node_list2.csv")
node3 = pd.read_csv(r"D:\commo\code\4_kumu_struct\node_list3.csv")
others = pd.read_csv(r"D:\commo\code\4_kumu_struct\others.csv")

In [ ]:
"""
The node lists for kumu contain columns such as (Id), Label, Type, Description, (Tags), and other cols according to each entity type. 
In the edge list, it contains columns such as From, To, Direction, Type.
"""

'\nThe node lists for kumu contain columns such as (Id), Label, Type, Description, (Tags), and other cols according to each entity type. \nIn the edge list, it contains columns such as From, To, Direction, Type, Strength, and Description.\n'

In [19]:
node2

                           label    role                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 description            scope                                                                                                                                         sg_address                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       practice_areas                                                                                                                                                   known_clients
0                     reed smith  lawyer                                                                                                                                                                                                                                                                            Notable Cases / Disputes: RTI Ltd v MUR Shipping BV [2024] UKSC 18, Sharp Corp Ltd v Viterra BV [2024] UKSC 14, The Aquafreedom [2024] EWHC 255 (Comm), The Ever Given – SMIT Salvage BV and Others v Luster Maritime SA [2024] EWCA Civ 260, Maersk Guiné-Bissau v Almar-Hum Bubacar Baldé [2024] EWHC 993 (Comm) (reedsmith.com)\n\nNotes: website: https://www.reedsmith.com/    International                                                                   10 Collyer Quay, #18-01 Ocean Financial Centre, Singapore 049315 (Reedsmith.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Dispute Resolution & Litigation | Regulatory & Compliance                         china merchants energy shipping holding singapore, sinopec, trafigura maritime logistics, uniper global commodities se singapore branch
1      holman fenwick willan hfw  lawyer                                                                                                                                                                                                                                                                                                                                                Notable Cases / Disputes: The "Rena" Grounding, OW Bunker Bankruptcy, The "Prestige" Oil Spill, The "Ocean Victory" Case (https://www.studocu.com/en-gb/messages/question/5472340/what-are-some-famous-cases-that-were-advised-by-hfw-and-how-were-they-influential)\n\nNotes: website: https://www.hfw.com/    International                                                                                    30 Raffles Place, #24-01, Bni Tower, Singapore 048622 (Hfw.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation | Regulatory & Compliance                                                               bgn energy, equatorial marine fuel management services, mitsui & co energy trading singapore mets
2                     clyde & co  lawyer                                                                                                                                                                                                    Notable Cases / Disputes: The 'Brillante Virtuoso' Case, Precedent setting FOSFA sale of goods arbitration (switzerland), Appealing the Refined Sugar Associations Arbitration Award (UK), Collision of VLCC "ALEXANDRA 1" and "EVER SMART" (UK), Penglai 19-3 Oil Field Pollution (China/USA),  COSCO BUSAN Allision with San Francisco-Oakland Bay Bridge (USA), Agarwal Coal High Court Appeal (UK) (claude + clydeco.com + perplexity)\n\nNotes: N/A    International                                                    12 Marina Boulevard, #30-03 Marina Bay Financial Centre Tower 3, Singapore 018982 (Clydeco.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation | Regulatory & Compliance | Real Estate & Construction | Employment & Labor                                                                                                                              ed&f man capital markets singapore
3             stephenson harwood  lawyer                                                                                                                                                                                                                                                                       Notable Cases / Disputes: former Yukos Oil Company shareholders v The Russian Federation, Trafigura Pte Ltd & Anor v Prateek Gupta & Ors [2026] EWHC 159 (Comm), SLB and others v PAK and others [2026] EWHC 449 (Comm), GAIL (India) Limited v SEFE Marketing & Trading Singapore Pte Limited, Narciso v Nash (ARB 009/2024) (google AI + google  & news + claude AI )\n\nNotes: N/A    International  Stephenson Harwood (Singapore) Alliance, 8 Marina Boulevard #29-01, Marina Bay Financial Centre Tower 1, Singapore 018981 (Stephensonharwood.Com)                                                                                                                                                                                                                                                                             Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation | Fraud | Investigations & White Collar | Regulatory & Compliance | Real Estate & Construction | Employment & Labor | Intellectual Property | Shipping & Maritime | International Trade & Commodities | Energy & Infrastructure | Private Wealth & Estate Planning | Technology | Data & Cybersecurity | Insurance                                                                                                        icici bank singapore branch, olam group, trafigura group
4       watson farley & williams  lawyer                                                                                                                                                                                                Notable Cases / Disputes: The merger between Hapag-Lloyd and the United Arab Shipping Company (UASC), WFW advises Guinea as US$24bn Simandou African mega-project closes, Niko Resources (Bangladesh) Ltd v. Bangladesh Petroleum Exploration & Production Company Limited ("Bapex") and Bangladesh Oil Gas and Mineral Corporation ("Petrobangla"), MRI Trading AG v Erdenet Mining Corp LLC (2013) (perplexity + google AI)\n\nNotes: https://www.wfw.com/    International                                                                      88 Market Street #31-05, Capitaspring, Singapore, 048948, Singapore (Wfw.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Corporate & M&A | Banking & Finance | Capital Markets | Dispute Resolution & Litigation | Regulatory & Compliance | Competition & Antitrust                                                                                                    bw energy holdings, hsbc singapore entities, trafigura group
5            ince & co singapore  lawyer                                                                                                                                                                                                                                                                                                     Notable Cases / Disputes: Global Coal Ltd v London Commodity Brokers (vlex.couk),Statoil ASA v Louis Dreyfus Energy Services LP (The Harriette N)(ipsaloquitur.com ), Priyanka Shipping Limited v Glory Bulk Carriers Pte Ltd [2019] EWHC 2804 (Comm) (Gemini)\n\nNotes: Rosita Lau (Partner & Head of Shipping), Ince don't have  office in sg(gemini)    International                                                                                              5 Shenton Way, #19-01, Uic Building, Singapore 068808                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Dispute Resolution & Litigation | Shipping & Maritime | International Trade & Commodities | Energy & Infrastructure | Insurance                                                                                                        glory bulk carriers, tai chong cheang shipping singapore
6          norton rose fulbright  lawyer                                                                                                                                                                   Notable Cases / Disputes: Suez Fortune Investments Ltd v Talbot(gemini), PD Teesport Ltd v. P&O North Sea Ferries Ltd — Force Majeure / Ferry Operator Dispute (2022–2023), Carnival Corporation v. Fincantieri S.p.A — Shipbuilding Contract / Breach of Guarantee (Ongoing as of 2024–2025), Shell UK v. Greenpeace UK — FPSO Boarding Dispute (2023–2024), KfW IPEX-Bank v. World Dream Limited ("The World Dream") — Ship Mortgage Enforcement (2022–2024) (perplexity)\n\nNotes: N/A    International                                                       Norton Rose Fulbright (Asia) Llp ,9 Straits Viewmarina One West Tower#09-09 Singapore 018937                                                                                                                                                                                                                                                                                                                               Corporate & M&A | Banking & Finance | Capital Markets | Private Equity & Venture Capital | Dispute Resolution & Litigation | Restructuring & Insolvency | Fraud | Investigations & White Collar | Real Estate & Construction | Employment & Labor | Intellectual Property | Energy & Infrastructure | Private Wealth & Estate Planning                                                                                                                                      louis dreyfus company asia
7                 baker mckenzie  lawyer                                                                                                                                                                                                                                                                                                                                      Notable Cases / Disputes: Anaklia Development Consortium (ADC) and Bob Meijer v. Georgia (ICC & ICSID parallel claims), Lakatamia Shipping Co Ltd v Su & Ors,  Lehram Capital Investments Ltd v. Baker McKenzie, Anaklia Development Consortium (ADC) v. Government of Georgia (google ai)\n\nNotes: bakermckenzie.com    International                                                                        38 Beach Road #23-11 South Beach Tower Singapore 189767 (Bakermckenzie.Com)                                                                                                                                      Corporate & M&A | Banking & Finance | Capital Markets | Private Equity & Venture Capital | Funds & Investment Management | Dispute Resolution & Litigation | Restructuring & Insolvency | Fraud | Investigations & White Collar | Regulatory & Compliance | Competition & Antitrust | Real Estate & Construction | Employment & Labor | Intellectual Property | Tax | International Trade & Commodities | Energy & Infrastructure | Private Wealth & Estate Planning | Technology | Data & Cybersecurity | ESG & Sustainability                                                                                                                          shell eastern trading, shell singapore
8            squire patton boggs  lawyer                                                                                                                                                                      Notable Cases / Disputes: LG Caltex v CNPC, Triad Shipping Co v Stellar Chartering & Brokerage Inc (The "Island Archon") [1994] 2 Lloyd's Rep 227, Merit Shipping Co Inc v T.K. Boesen A/S (The "Goodpal") [2000] 1 Lloyd's Rep 638, André & Cie S.A. v Orient Shipping (Rotterdam) B.V. (The "Laconian Confidence") [1997] 1 Lloyd's Rep 139, AIC Ltd v ITS Testing Services (UK) Ltd (The "Kriti Palm") [2006] EWCA Civ 1601 (squirepattonboggs.com)\n\nNotes: squirepattonboggs.com    International                                                      1 Marina Boulevard, #21-01 One Marina Boulevard, Singapore 018989 (Www.Squirepattonboggs.Com)                                                                                                                                                                                                                                                                                                                                                   Corporate & M&A | Banking & Finance | Private Equity & Venture Capital | International Arbitration | Real Estate & Construction | Shipping & Maritime | International Trade & Commodities | Energy & Infrastructure | Private Wealth & Estate Planning | Technology | Data & Cybersecurity | Hospitality & Leisure                                                                                                                                                             NaN
9                 hill dickinson  lawyer                                                                                                                                                                                                                                                                                                                Notable Cases / Disputes: SY Roro 1 Pte Ltd and another v Onorato Armatori S.R.L. and others [2024] EWHC 611 (Comm) (google AI), Trafigura PTE Ltd & Anor v Gupta & Ors [2026] EWHC 159 (Comm) (hilldickinson.com/our-view/articles/commodity-trader-successful-in-fraudulent-nickel-trade-claims/)\n\nNotes: https://www.hilldickinson.com/    International                                                        3 Anson Road, Springleaf Tower, 24-03, Singapore, 079909, Sg ( Hill Dickinson Llp Linkedin)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation | Regulatory & Compliance | Real Estate & Construction | Private Wealth & Estate Planning                                                                                                                                                 trafigura group
10               mayer brown llp  lawyer                                                                                                                                                                                                                                                                                                                                      Notable Cases / Disputes: Clearlake Shipping Pte Ltd v. Guvnor Shipping & Others, Aabar Holdings v. Glencore plc, The "Reluctant Ship Owner" Mortgages Enforcement Action, In re: Singamas and Container Cartel Litigation, In re: Glencore PLC SFO Investigation (perplexity)\n\nNotes: https://www.mayerbrown.com/en    International                                                        6 Battery Road, #10-01, Singapore 049909 (Https://Www.Mayerbrown.Com/En/About-Us/Locations)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation                                                                                                                                                             NaN

In [20]:
node1.rename(columns={
    'label':'Label',
    'role':'Type',
    'description':'Description',
}, inplace=True)
node2.rename(columns={
    'label':'Label',
    'role':'Type',
    'description':'Description'
}, inplace=True)
node3.rename(columns={
    'label':'Label',
    'role':'Type',
    'description':'Description'
}, inplace=True)
others.rename(columns={
    'label':'Label',
    'role':'Type'}, inplace=True)

In [21]:
others

                                                Label    Type
0                                              amaroq  others
1                argoglobal underwriting asia pacific  others
2              atlantic navigation holdings singapore  others
3                                     bafco singapore  others
4                                    barramundi group  others
5                                   boustead projects  others
6                                         bts tankers  others
7                                  bw energy holdings  others
8   china merchants energy shipping holding singapore  others
9                   china taiping insurance singapore  others
10                                                cye  others
11                                     develop global  others
12                                first sponsor group  others
13                           fti consulting singapore  others
14                                glory bulk carriers  others
15                                  grabtaxi holdings  others
16                   great american insurance company  others
17                                ho lee construction  others
18                                     katanga mining  others
19                             kipushi corporation sa  others
20                                               kpmg  others
21                           maersk tankers singapore  others
22                                    marina offshore  others
23                                     metro holdings  others
24                         ms first capital insurance  others
25                            new & novel engineering  others
26                              ocean network express  others
27                     perennial real estate holdings  others
28               pricewaterhousecoopers pwc singapore  others
29                            qbe insurance singapore  others
30                                              razer  others
31                                          rio tinto  others
32                                           seatrium  others
33                                      seraya energy  others
34                   st telemedia global data centres  others
35                tai chong cheang shipping singapore  others
36                                  tarago operations  others
37                                      the daily cut  others
38                  the singapore medical council smc  others
39                          thomson medical group tmg  others
40                                trafigura beheer bv  others
41                       trafigura maritime logistics  others
42                                               vale  others
43                                     vast resources  others
44         westbridge ventures ii investment holdings  others
45                             woodlawn mine holdings  others
46                                   gtp advisory pac  others
47                                   vyas engineering  others

In [ ]:
# save the 4 node lists  and edge listi
node1.to_csv(r"D:\commo\code\4_kumu_struct\node_list1.csv", index=False)
node2.to_csv(r"D:\commo\code\4_kumu_struct\node_list2.csv", index=False)
node3.to_csv(r"D:\commo\code\4_kumu_struct\node_list3.csv", index=False)
others.to_csv(r"D:\commo\code\4_kumu_struct\others.csv", index=False)
edge_list.to_csv(r"D:\commo\code\4_kumu_struct\edge_list.csv", index=False)

In [4]:
node_list1 = pd.read_csv(r"D:\commo\code\4_kumu_struct\node_list1.csv")
node_list2 = pd.read_csv(r"D:\commo\code\4_kumu_struct\node_list2.csv")
node_list3 = pd.read_csv(r"D:\commo\code\4_kumu_struct\node_list3.csv")
edge_list = pd.read_csv(r"D:\commo\code\4_kumu_struct\edge_list.csv")

In [32]:
node_list1
node_list1[node_list1["Label"].str.contains("jsw")]

                               Label    Type Description  tier commodity_type commodity_focus acra_uen hq_country est_revenue global_headcount est_trade_volume ownership_struct exchange                                                sg_address
110  jsw international tradecorp jsw  trader         NaN   NaN    hard/metals             NaN      NaN      India         NaN              NaN              NaN          private      NaN  9 Raffles Place, #20-01 Republic Plaza, Singapore 048619

In [33]:
node_list2
node_list2[node_list2["Label"].str.contains("helmsman llc")]

           Label    Type                                                                                                                                                                                                                              Description            scope                                                                                           sg_address                                                                                                                                                                practice_areas                                known_clients
16  helmsman llc  lawyer  Notable Cases / Disputes: Public Prosecutor v Richard Ouwehand and Others, Orion Shipping and Trading Ltd v Great Asia Maritime Ltd Vasily Trubnikov v Evgeny Volosov [2025] HKCFI 1576 (google)\n\nNotes: https://www.helmsmanlaw.com/  Singapore Local  21A Duxton Hill (Reception: 19 Duxton Hill), Singapore 089604 (Https://Www.Helmsmanlaw.Com/Contact)  Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation | Employment & Labor | Intellectual Property | Shipping & Maritime | International Trade & Commodities  straits bunkering, united overseas bank uob

In [32]:
node_list3

                                                     Label    Type                                                                                                                                                                                                                                                                                                                     Description         financier_type                                             commodity_type                                                                                                                                                                                                          geographic_reach                                                                                                                                                                known_clients
0                                                      ing  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                                                      EMEA, APAC, Americas                                                                                                                         glencore, gunvor group, trafigura group, vitol group
1                                         societe generale  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                      Primary base , North America, APAC, emerging markets                                                                                                                                                                          NaN
2                                              bnp paribas  lender                                                                                                                                                                                sep 2020: BNP Paribas Suisse discontinued financing commodity trading and announced restructuring affecting 120 employees in Geneva (perplexity)       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                 Europe , Americas , APAC, Africa. Global network spans over 100 countries                                                                                                                                                                          NaN
3                                                 rabobank  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                       EU, Americas, Asia, Africa, ~38 countries across Europe, North America, South America, Asia, Australia, New Zealand                                                                                                                                                                          NaN
4                                       standard chartered  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank        energy | hard/metals | soft/agricultural | emerging                                                                                                                                               Asia-Pacific , China & India , Africa , Middle East , Latin America, UK, US                                                                                                                    glencore, marubeni corporation, seatrium, trafigura group
5                                                 dbs bank  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                      Southeast Asia , Greater China , South Asia , Australia, Europe , Africa, Middle East, Latin America                                                                              agrocorp international, louis dreyfus company, rio tinto, trafigura group, wilmar international
6                 oversea-chinese banking corporation ocbc  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                             Southeast Asia , Greater China , Asia , Europe, Australia, US                                                                                                                                                                          NaN
7                                 united overseas bank uob  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                         Australia, brunei, canada, mainland china, france, hong kong, india, indonesia, japan, malaysia, myanmar, philippines, singapore, south korea, taiwan, thailand, uk, usa, vietnam                                                                                         barramundi group, cargill, musim mas holdings, sinar mas group, wilmar international
8                                                     mufg  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                               ~50 countries, ~3,000 locations globally; strong in Asia Pacific , EMEA , and North America                                                                                     bunge, cofco international, gunvor group, mercuria, six one commodities, trafigura group
9                                                     smbc  lender                                                                                                                                                                                                                                                                 SMBC remains fully active in commodity trade finance as of 2026       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                            Japan , SEA, China, South Asia, Middle East, Africa, EU, North America, Latin America, Oceania  cofco international, gunvor group, louis dreyfus company, mercuria energy group, olam food ingredients, rio tinto, trafigura group, vale, vitol group, wilmar international
10                                         credit agricole  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                            Switzerland/Western EU , Americas, APAC, SEA, Middle East, Greater China, Korea, Japan, Africa                                                                                       cofco international, gunvor group, mercuria energy group, trafigura group, vitol group
11                                                    hsbc  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                       APAC, North America, Latin America, EMEA, MENAT, Sub-saharan africa                                                                                                     glencore, gunvor group, olam agri holdings, sinar mas group, vitol group
12                                                 natixis  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                        France / EU , Americas, APAC, Middle East / Africa                                                                                                              cofco international, gunvor group, trafigura group, vitol group
13                          bank of china singapore branch  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                                     energy                                                                                                                                                                                                               APAC, ASEAN                                                                                                                                                             unipec singapore
14                china construction bank singapore branch  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                                     others                                                                                                                                                                              Singapore, China, South Asia, Southeast Asia                                                                                                                                                              trafigura group
15                                   icbc singapore branch  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                       energy | hard/metals                                                                                                                                                                                            Global with Asia-Pacific focus                                                                                                                                                              trafigura group
16             agricultural bank of china singapore branch  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                       energy | hard/metals                                                                                                                                                                                                                   SG, SEA                                                                                                                                                          trafigura beheer bv
17  shanghai pudong development bank spdb singapore branch  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                                     others                                                                                                                                                                                                                   SG, SEA                                                                                                                                                                          NaN
18                              mufg bank singapore branch  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                                        Global with emerging markets focus                                                                                                                                                      mercuria energy trading
19                         macquarie bank singapore branch  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                       energy | hard/metals                                                                                                                                                                                                                      ASIA                                                                                                                                                                          NaN
20     commonwealth bank of australia cba singapore branch  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                                   emerging                                                                                                                                                                                                                      APAC                                                                                                                                                                          NaN
21                               anz bank singapore branch  lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                                                                    global                                                                                                                                                                          NaN

In [33]:
others

                                                Label    Type
0                                              amaroq  others
1                argoglobal underwriting asia pacific  others
2              atlantic navigation holdings singapore  others
3                                     bafco singapore  others
4                                    barramundi group  others
5                                   boustead projects  others
6                                         bts tankers  others
7                                  bw energy holdings  others
8   china merchants energy shipping holding singapore  others
9                   china taiping insurance singapore  others
10                                                cye  others
11                                     develop global  others
12                                first sponsor group  others
13                           fti consulting singapore  others
14                                glory bulk carriers  others
15                                  grabtaxi holdings  others
16                   great american insurance company  others
17                                ho lee construction  others
18                                     katanga mining  others
19                             kipushi corporation sa  others
20                                               kpmg  others
21                           maersk tankers singapore  others
22                                    marina offshore  others
23                                     metro holdings  others
24                         ms first capital insurance  others
25                            new & novel engineering  others
26                              ocean network express  others
27                     perennial real estate holdings  others
28               pricewaterhousecoopers pwc singapore  others
29                            qbe insurance singapore  others
30                                              razer  others
31                                          rio tinto  others
32                                           seatrium  others
33                                      seraya energy  others
34                   st telemedia global data centres  others
35                tai chong cheang shipping singapore  others
36                                  tarago operations  others
37                                      the daily cut  others
38                  the singapore medical council smc  others
39                          thomson medical group tmg  others
40                                trafigura beheer bv  others
41                       trafigura maritime logistics  others
42                                               vale  others
43                                     vast resources  others
44         westbridge ventures ii investment holdings  others
45                             woodlawn mine holdings  others
46                                   gtp advisory pac  others
47                                   vyas engineering  others

In [27]:
edge_list

                                            From                                                 To Direction          Type
0                            trafigura beheer bv                                    trafigura group  directed          owns
1                                trafigura group                           trafigura carbon trading  directed          owns
2                                trafigura group                       trafigura maritime logistics  directed          owns
3                                    vitol group                                         vitol asia  directed          owns
4                          mercuria energy group                            mercuria energy trading  directed          owns
5                          mercuria energy group                                  mercuria holdings  directed          owns
6                                   gunvor group                                   gunvor singapore  directed          owns
7                                     olam group                              olam food ingredients  directed          owns
8                                     olam group                                 olam agri holdings  directed          owns
9                          louis dreyfus company                         louis dreyfus company asia  directed          owns
10                           cofco international                      cofco international singapore  directed          owns
11                                      glencore                                 glencore singapore  directed          owns
12                                   mitsui & co          mitsui & co energy trading singapore mets  directed          owns
13                               shell singapore                              shell eastern trading  directed          owns
14                                       sinopec                                   unipec singapore  directed          owns
15                                       sinopec                              sinopec international  directed          owns
16                                       sinopec                    sinopec international singapore  directed          owns
17                                       sinopec                                   sinopec fuel oil  directed          owns
18                      petrochina international                 petrochina international singapore  directed          owns
19                               sinar mas group                          golden agri international  directed          owns
20                            standard chartered              standard chartered bank singapore scb  directed          owns
21                              ed&f man capital                 ed&f man capital markets singapore  directed          owns
22                          wilmar international                                       wilmar sugar  directed          owns
23                                       cargill                      cargill asia pacific holdings  directed          owns
24                                         bunge                                         bunge asia  directed          owns
25                               trafigura group                                            lex oil  directed      lends_to
26                               trafigura group                                     develop global  directed      lends_to
27                               trafigura group                             woodlawn mine holdings  directed      lends_to
28                               trafigura group                                  tarago operations  directed      lends_to
29                                  gunvor group                                             amaroq  directed      lends_to
30                                   vitol group                           uganda national oil unoc  directed      lends_to
31                                      glencore                                     katanga mining  directed      lends_to
32                       mercuria energy trading                             kipushi corporation sa  directed      lends_to
33                       mercuria energy trading                                     vast resources  directed      lends_to
34                                    reed smith  china merchants energy shipping holding singapore  directed  counsels_for
35                                    reed smith                                            sinopec  directed  counsels_for
36                                    reed smith                       trafigura maritime logistics  directed  counsels_for
37                                    reed smith      uniper global commodities se singapore branch  directed  counsels_for
38                     holman fenwick willan hfw                                         bgn energy  directed  counsels_for
39                     holman fenwick willan hfw         equatorial marine fuel management services  directed  counsels_for
40                     holman fenwick willan hfw          mitsui & co energy trading singapore mets  directed  counsels_for
41                                    clyde & co                 ed&f man capital markets singapore  directed  counsels_for
42                            stephenson harwood                        icici bank singapore branch  directed  counsels_for
43                            stephenson harwood                                         olam group  directed  counsels_for
44                            stephenson harwood                                    trafigura group  directed  counsels_for
45                      watson farley & williams                                 bw energy holdings  directed  counsels_for
46                      watson farley & williams                            hsbc singapore entities  directed  counsels_for
47                      watson farley & williams                                    trafigura group  directed  counsels_for
48                           ince & co singapore                                glory bulk carriers  directed  counsels_for
49                           ince & co singapore                tai chong cheang shipping singapore  directed  counsels_for
50                         norton rose fulbright                         louis dreyfus company asia  directed  counsels_for
51                                baker mckenzie                              shell eastern trading  directed  counsels_for
52                                baker mckenzie                                    shell singapore  directed  counsels_for
53                                hill dickinson                                    trafigura group  directed  counsels_for
54                          latham & watkins llp                              ocean network express  directed  counsels_for
55                                  rajah & tann                    sinopec international singapore  directed  counsels_for
56                                  rajah & tann                                  sumifru singapore  directed  counsels_for
57                              allen & gledhill                                        bts tankers  directed  counsels_for
58                              allen & gledhill                                           dbs bank  directed  counsels_for
59                              allen & gledhill                    jsw international tradecorp jsw  directed  counsels_for
60                              allen & gledhill           oversea-chinese banking corporation ocbc  directed  counsels_for
61                              allen & gledhill                   st telemedia global data centres  directed  counsels_for
62                              allen & gledhill                           united overseas bank uob  directed  counsels_for
63                                 drew & napier                                     metro holdings  directed  counsels_for
64                                 drew & napier                                              razer  directed  counsels_for
65                               wongpartnership                                           dbs bank  directed  counsels_for
66                               wongpartnership                                    first resources  directed  counsels_for
67                               wongpartnership                                first sponsor group  directed  counsels_for
68                                  helmsman llc                                  straits bunkering  directed  counsels_for
69                                  helmsman llc                           united overseas bank uob  directed  counsels_for
70                             blackstone & gold                                             alvari  directed  counsels_for
71                             blackstone & gold                                    avani resources  directed  counsels_for
72                         braddell brothers llp                                    bafco singapore  directed  counsels_for
73                         braddell brothers llp                basf intertrade ag singapore branch  directed  counsels_for
74                         braddell brothers llp                  the singapore medical council smc  directed  counsels_for
75                     joseph tan jude benny llp                           fti consulting singapore  directed  counsels_for
76                  dentons rodyk & davidson llp                                  boustead projects  directed  counsels_for
77                  dentons rodyk & davidson llp           oversea-chinese banking corporation ocbc  directed  counsels_for
78                  dentons rodyk & davidson llp                          thomson medical group tmg  directed  counsels_for
79                               oon & bazul llc           oversea-chinese banking corporation ocbc  directed  counsels_for
80                               oon & bazul llc                                 winson oil trading  directed  counsels_for
81                                   pdlegal llc                         louis dreyfus company asia  directed  counsels_for
82                           shook lin & bok llp              standard chartered bank singapore scb  directed  counsels_for
83                          tsmp law corporation                           halcyon agri corporation  directed  counsels_for
84                          tsmp law corporation                                ho lee construction  directed  counsels_for
85                          tsmp law corporation                                               kpmg  directed  counsels_for
86                          tsmp law corporation                                        mizuho bank  directed  counsels_for
87                          tsmp law corporation                     perennial real estate holdings  directed  counsels_for
88                          tsmp law corporation                                      seraya energy  directed  counsels_for
89                          tsmp law corporation         westbridge ventures ii investment holdings  directed  counsels_for
90                                virtus law llp              standard chartered bank singapore scb  directed  counsels_for
91                                 dennismathiew             atlantic navigation holdings singapore  directed  counsels_for
92                                 dennismathiew                               royal global exports  directed  counsels_for
93                                 asialegal llc                         louis dreyfus company asia  directed  counsels_for
94                        haridass ho & partners                                    marina offshore  directed  counsels_for
95                            pk wong & nair llc                                  maybank singapore  directed  counsels_for
96                            pk wong & nair llc                 petrochina international singapore  directed  counsels_for
97                       providence law asia llc                                     gp global apac  directed  counsels_for
98                       providence law asia llc                                   gtp advisory pac  directed  counsels_for
99                       providence law asia llc               pricewaterhousecoopers pwc singapore  directed  counsels_for
100                         lvm law chambers llc                                                cye  directed  counsels_for
101                         lvm law chambers llc                                  grabtaxi holdings  directed  counsels_for
102                         lvm law chambers llc                         ms first capital insurance  directed  counsels_for
103                         lvm law chambers llc                                   unipec singapore  directed  counsels_for
104                         lvm law chambers llc                           united overseas bank uob  directed  counsels_for
105                         lvm law chambers llc                                 winson oil trading  directed  counsels_for
106                             incisive law llc               argoglobal underwriting asia pacific  directed  counsels_for
107                             incisive law llc                  china taiping insurance singapore  directed  counsels_for
108                             incisive law llc                   great american insurance company  directed  counsels_for
109                             incisive law llc                         ms first capital insurance  directed  counsels_for
110                             incisive law llc                            qbe insurance singapore  directed  counsels_for
111                           focus law asia llc                           maersk tankers singapore  directed  counsels_for
112                                          ing                                           glencore  directed      lends_to
113                                          ing                                       gunvor group  directed      lends_to
114                                          ing                                    trafigura group  directed      lends_to
115                                          ing                                        vitol group  directed      lends_to
116                           standard chartered                                           glencore  directed      lends_to
117                           standard chartered                               marubeni corporation  directed      lends_to
118                           standard chartered                                           seatrium  directed      lends_to
119                           standard chartered                                    trafigura group  directed      lends_to
120                                     dbs bank                             agrocorp international  directed      lends_to
121                                     dbs bank                              louis dreyfus company  directed      lends_to
122                                     dbs bank                                          rio tinto  directed      lends_to
123                                     dbs bank                                    trafigura group  directed      lends_to
124                                     dbs bank                               wilmar international  directed      lends_to
125                     united overseas bank uob                                   barramundi group  directed      lends_to
126                     united overseas bank uob                                            cargill  directed      lends_to
127                     united overseas bank uob                                 musim mas holdings  directed      lends_to
128                     united overseas bank uob                                    sinar mas group  directed      lends_to
129                     united overseas bank uob                               wilmar international  directed      lends_to
130                                         mufg                                              bunge  directed      lends_to
131                                         mufg                                cofco international  directed      lends_to
132                                         mufg                                       gunvor group  directed      lends_to
133                                         mufg                                           mercuria  directed      lends_to
134                                         mufg                                six one commodities  directed      lends_to
135                                         mufg                                    trafigura group  directed      lends_to
136                                         smbc                                cofco international  directed      lends_to
137                                         smbc                                       gunvor group  directed      lends_to
138                                         smbc                              louis dreyfus company  directed      lends_to
139                                         smbc                              mercuria energy group  directed      lends_to
140                                         smbc                              olam food ingredients  directed      lends_to
141                                         smbc                                          rio tinto  directed      lends_to
142                                         smbc                                    trafigura group  directed      lends_to
143                                         smbc                                               vale  directed      lends_to
144                                         smbc                                        vitol group  directed      lends_to
145                                         smbc                               wilmar international  directed      lends_to
146                              credit agricole                                cofco international  directed      lends_to
147                              credit agricole                                       gunvor group  directed      lends_to
148                              credit agricole                              mercuria energy group  directed      lends_to
149                              credit agricole                                    trafigura group  directed      lends_to
150                              credit agricole                                        vitol group  directed      lends_to
151                                         hsbc                                           glencore  directed      lends_to
152                                         hsbc                                       gunvor group  directed      lends_to
153                                         hsbc                                 olam agri holdings  directed      lends_to
154                                         hsbc                                    sinar mas group  directed      lends_to
155                                         hsbc                                        vitol group  directed      lends_to
156                                      natixis                                cofco international  directed      lends_to
157                                      natixis                                       gunvor group  directed      lends_to
158                                      natixis                                    trafigura group  directed      lends_to
159                                      natixis                                        vitol group  directed      lends_to