In [53]:
import pandas as pd

# display columns without truncation
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

# display rows without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.expand_frame_repr", False)

In [54]:
roles_only = pd.read_csv(r"D:\commo\code\id_role_assignment\assigned_only_roles.csv")
# standardized pillars
node_list1 = pd.read_csv(r"D:\commo\code\cleaned_pillars\standardized_pillar1.csv")
node_list2 = pd.read_csv(r"D:\commo\code\cleaned_pillars\standardized_pillar2.csv")
node_list3 = pd.read_csv(r"D:\commo\code\cleaned_pillars\standardized_pillar3.csv")

In [ ]:
"""
The node lists for kumu contain columns such as (Id), Label, Type, Description, (Tags), and other cols according to each entity type. 
In the edge list, it contains columns such as From, To, Direction, Type, Strength, and Description.
"""

In [55]:
# re order the columns in node_list1

node_list1.rename(columns={'Company Name': 'Label'}, inplace=True)
# move the label col to index 0
# Get the name of the label column at index 0
label_col = node_list1.columns[1]
# Pop the column and insert it at index 0, run one time
node_list1.insert(0, 'Label', node_list1.pop(label_col))

# insert the Type col, which is the role(s)
role_map = roles_only.set_index("name")["role(s)"]
node_list1.insert(1, "Type", pd.NA) # run one time
node_list1["Type"] = node_list1["Label"].map(role_map) 

# move the Notes to index 2 as description
desc_col = node_list1.columns[-1]
node_list1.insert(2, 'Description', node_list1.pop(desc_col))
# save node_list1

In [56]:
# re order the columns in node_list2

# rename the firm name as label
node_list2.rename(columns={'Firm Name': 'Label'}, inplace=True)

# insert the Type col, which is the role(s)
role_map = roles_only.set_index("name")["role(s)"]
node_list2.insert(1, "Type", pd.NA)  # run one time
node_list2["Type"] = node_list2["Label"].map(role_map)

# rename the Type (intl/local)
node_list2.rename(columns={'Type (Intl / Local)': 'Scope'}, inplace=True)

# move the notable cases + notes to description col at index 2
col1 = "Notable Cases / Disputes"
col2 = "Notes"
def build_description(row):
    val1 = row[col1] if isinstance(row[col1], str) and row[col1].strip() else "N/A"
    val2 = row[col2] if isinstance(row[col2], str) and row[col2].strip() else "N/A"
    return f"{col1}: {val1}\n\n{col2}: {val2}"
node_list2["Description"] = node_list2.apply(build_description, axis=1)
node_list2.insert(2, "Description", node_list2.pop("Description"))
# drop the last 2 columns
node_list2 = node_list2.drop(columns=["Notable Cases / Disputes", "Notes"])
# save node_list2

In [57]:
# re order the columns in node_list3
node_list3.rename(columns={'Institution Name': 'Label', 'Category':'Financier Type'}, inplace=True)

# insert the Type col, which is the role(s) at index 1
role_map = roles_only.set_index("name")["role(s)"]
node_list3.insert(1, "Type", pd.NA)  # run one time
node_list3["Type"] = node_list3["Label"].map(role_map)

# move the Notes to index 2 as description
node_list3.insert(2, "Description", node_list3.pop('Notes'))
# save node_list3

In [ ]:
# In the edge list, it contains columns such as From, To, Direction, Type
edge_list = pd.DataFrame(columns=['From', 'To', 'Direction', 'Type'])

# note the node_list2 Label (edge type: counsels_for) Known Client Base
# explode node_list2 known client base into individual rows
import re
def split_names(row):
    if not isinstance(row, str) or not row.strip(): # if not row.strip() = True > not real content
        return []
    parts = re.split(r',\s*(?![^()]*\))', row)
    return [p.strip() for p in parts]
node_list2_exploded = node_list2[['Label', 'Known Client Base']].copy()
node_list2_exploded['Known Client Base'] = node_list2_exploded['Known Client Base'].apply(split_names) # each client row has list of comma-separated str
node_list2_exploded = node_list2_exploded.explode('Known Client Base').reset_index(drop=True) # each row has one client but same law firm
# change Label to 'From', known client base to 'to'
node_list2_exploded.rename(columns={'Label': 'From', 'Known Client Base': 'To'}, inplace=True)
# add Direction column
node_list2_exploded['Direction'] = 'directed'
# add edge type column
node_list2_exploded['Type'] = 'counsels_for'
# node_list2_exploded is ready for concat

# note the node_list3 Label (edge type: lends_to) Known Clients
# explode node_list3 known clients into individual rows
node_list3_exploded = node_list3[['Label', 'Known Clients']].copy()
node_list3_exploded['Known Clients'] = node_list3_exploded['Known Clients'].apply(split_names)
node_list3_exploded = node_list3_exploded.explode('Known Clients').reset_index(drop=True) #before reset_index, the exploded rows still have their original row index
# rename Label to from, Known Clients to to
node_list3_exploded.rename(columns={'Label':'From', 'Known Clients':'To'}, inplace=True)
node_list3_exploded['Direction'] = 'directed'
node_list3_exploded['Type'] = 'lends_to'
#node_list3_exploded is ready for concat

# node_list1 lends_to? owns?
# trafigura group owns trafigura carbon trading, trafigura maritime logistics
# vitol group owns vitol asia
# mercuria energy group owns mercuria holdings
# gunvor group owns gunvor singapore
# olam group owns olam food ingredients, olam agri holdings
# louis dreyfus company owns louis dreyfus company asia
# cofco international owns cofco international singapore
# glencore owns glencore singapore
# mitsui & co owns mitsui & co energy trading singapore (mets)
# shell singapore owns shell eastern trading
# sinopec owns unipec singapore, sinopec international, sinopec international singapore, sinopec fuel oil
# petrochina international owns petrochina international singapore
# sinar mas group owns golden agri international
# standard chartered owns standard chartered bank singapore scb
# ed&f man capital owns ed&f man capital markets singapore
# wilmar international owns wilmar sugar
# cargill owns cargill asia pacific holdings
# bunge owns bunge asia
# trafigura group lends to lex oil, develop global, woodlawn mine holdings, tarago operations
# gunvor group lends to amaroq
# vitol group lends to uganda national oil unoc
# glencore lends to katanga mining
# mercuria energy group / mercuria energy trading lends to kipushi corporation sa, vast resources

                                                       From                       To Direction      Type
0                                                       ing                 glencore  directed  lends_to
1                                                       ing             gunvor group  directed  lends_to
2                                                       ing          trafigura group  directed  lends_to
3                                                       ing              vitol group  directed  lends_to
4                                          societe generale                      NaN  directed  lends_to
5                                               bnp paribas                      NaN  directed  lends_to
6                                                  rabobank                      NaN  directed  lends_to
7                                        standard chartered                 glencore  directed  lends_to
8                                        standard chartered     marubeni corporation  directed  lends_to
9                                        standard chartered                 seatrium  directed  lends_to
10                                       standard chartered          trafigura group  directed  lends_to
11                                                 dbs bank   agrocorp international  directed  lends_to
12                                                 dbs bank    louis dreyfus company  directed  lends_to
13                                                 dbs bank                rio tinto  directed  lends_to
14                                                 dbs bank          trafigura group  directed  lends_to
15                                                 dbs bank     wilmar international  directed  lends_to
16                 oversea-chinese banking corporation ocbc                      NaN  directed  lends_to
17                                 united overseas bank uob         barramundi group  directed  lends_to
18                                 united overseas bank uob                  cargill  directed  lends_to
19                                 united overseas bank uob       musim mas holdings  directed  lends_to
20                                 united overseas bank uob          sinar mas group  directed  lends_to
21                                 united overseas bank uob     wilmar international  directed  lends_to
22                                                     mufg                    bunge  directed  lends_to
23                                                     mufg      cofco international  directed  lends_to
24                                                     mufg             gunvor group  directed  lends_to
25                                                     mufg                 mercuria  directed  lends_to
26                                                     mufg      six one commodities  directed  lends_to
27                                                     mufg          trafigura group  directed  lends_to
28                                                     smbc      cofco international  directed  lends_to
29                                                     smbc             gunvor group  directed  lends_to
30                                                     smbc    louis dreyfus company  directed  lends_to
31                                                     smbc    mercuria energy group  directed  lends_to
32                                                     smbc    olam food ingredients  directed  lends_to
33                                                     smbc                rio tinto  directed  lends_to
34                                                     smbc          trafigura group  directed  lends_to
35                                                     smbc                     vale  directed  lends_to
36                                                     smbc              vitol group  directed  lends_to
37                                                     smbc     wilmar international  directed  lends_to
38                                          credit agricole      cofco international  directed  lends_to
39                                          credit agricole             gunvor group  directed  lends_to
40                                          credit agricole    mercuria energy group  directed  lends_to
41                                          credit agricole          trafigura group  directed  lends_to
42                                          credit agricole              vitol group  directed  lends_to
43                                                     hsbc                 glencore  directed  lends_to
44                                                     hsbc             gunvor group  directed  lends_to
45                                                     hsbc       olam agri holdings  directed  lends_to
46                                                     hsbc          sinar mas group  directed  lends_to
47                                                     hsbc              vitol group  directed  lends_to
48                                                  natixis      cofco international  directed  lends_to
49                                                  natixis             gunvor group  directed  lends_to
50                                                  natixis          trafigura group  directed  lends_to
51                                                  natixis              vitol group  directed  lends_to
52                           bank of china singapore branch         unipec singapore  directed  lends_to
53                 china construction bank singapore branch          trafigura group  directed  lends_to
54                                    icbc singapore branch          trafigura group  directed  lends_to
55              agricultural bank of china singapore branch      trafigura beheer bv  directed  lends_to
56   shanghai pudong development bank spdb singapore branch                      NaN  directed  lends_to
57                               mufg bank singapore branch  mercuria energy trading  directed  lends_to
58                          macquarie bank singapore branch                      NaN  directed  lends_to
59      commonwealth bank of australia cba singapore branch                      NaN  directed  lends_to
60                                anz bank singapore branch                      NaN  directed  lends_to
61             westpac banking corporation singapore branch                      NaN  directed  lends_to
62             national australia bank nab singapore branch                      NaN  directed  lends_to
63                        cimb bank berhad singapore branch                      NaN  directed  lends_to
64                         malayan banking berhad singapore                      NaN  directed  lends_to
65                         rhb bank berhad singapore branch                      NaN  directed  lends_to
66                   bank of east asia bea singapore branch                      NaN  directed  lends_to
67                     state bank of india singapore branch                      NaN  directed  lends_to
68                              dz bank ag singapore branch                      NaN  directed  lends_to
69                        deutsche bank ag singapore branch                      NaN  directed  lends_to
70                          commerzbank ag singapore branch                      NaN  directed  lends_to
71                                       citibank singapore                      NaN  directed  lends_to
72                           goldman sachs singapore branch                      NaN  directed  lends_to
73                     jpmorgan chase bank singapore branch                      NaN  directed  lends_to
74                                    bbva singapore branch                      NaN  directed  lends_to
75                         bank of america singapore branch                      NaN  directed  lends_to
76                                                  ossiano                      NaN  directed  lends_to
77                                                    copap                      NaN  directed  lends_to
78                                        tradeflow capital                      NaN  directed  lends_to
79                                                  mercore                      NaN  directed  lends_to
80                                                 audentia                      NaN  directed  lends_to
81                                         ed&f man capital                      NaN  directed  lends_to
82                                                czarnikow                      NaN  directed  lends_to
83                                         sucden financial                      NaN  directed  lends_to
84                                             drip capital                      NaN  directed  lends_to
85                                                incomlend                      NaN  directed  lends_to
86                                              gxs capital                      NaN  directed  lends_to
87                                               fs capital  new & novel engineering  directed  lends_to
88                                               fs capital            the daily cut  directed  lends_to
89                                               fs capital         vyas engineering  directed  lends_to
90                                              ifs capital                      NaN  directed  lends_to
91                               straits financial services                      NaN  directed  lends_to
92                                                gb helios                      NaN  directed  lends_to
93                              nomura securities singapore                      NaN  directed  lends_to
94                                              adm capital                      NaN  directed  lends_to
95                                       hong leong finance                      NaN  directed  lends_to
96                                         eastvine capital                      NaN  directed  lends_to
97                               sing investments & finance                      NaN  directed  lends_to
98                                        zma smart capital                      NaN  directed  lends_to
99                                   mufg trading singapore                      NaN  directed  lends_to
100                                  orix leasing singapore                      NaN  directed  lends_to
101                                  capital match platform                      NaN  directed  lends_to
102                                        seatown holdings                      NaN  directed  lends_to
103                                             modifi asia                      NaN  directed  lends_to
104                                        stonex financial                      NaN  directed  lends_to
105                        horizon capital ag singapore rep                      NaN  directed  lends_to
106                              hartree partners singapore                      NaN  directed  lends_to
107                                        traxys singapore                      NaN  directed  lends_to
108                         freepoint commodities singapore           the prax group  directed  lends_to

In [63]:
node_list3_exploded

                                                       From                       To Direction      Type
0                                                       ing                 glencore  directed  lends_to
1                                                       ing             gunvor group  directed  lends_to
2                                                       ing          trafigura group  directed  lends_to
3                                                       ing              vitol group  directed  lends_to
4                                          societe generale                      NaN  directed  lends_to
5                                               bnp paribas                      NaN  directed  lends_to
6                                                  rabobank                      NaN  directed  lends_to
7                                        standard chartered                 glencore  directed  lends_to
8                                        standard chartered     marubeni corporation  directed  lends_to
9                                        standard chartered                 seatrium  directed  lends_to
10                                       standard chartered          trafigura group  directed  lends_to
11                                                 dbs bank   agrocorp international  directed  lends_to
12                                                 dbs bank    louis dreyfus company  directed  lends_to
13                                                 dbs bank                rio tinto  directed  lends_to
14                                                 dbs bank          trafigura group  directed  lends_to
15                                                 dbs bank     wilmar international  directed  lends_to
16                 oversea-chinese banking corporation ocbc                      NaN  directed  lends_to
17                                 united overseas bank uob         barramundi group  directed  lends_to
18                                 united overseas bank uob                  cargill  directed  lends_to
19                                 united overseas bank uob       musim mas holdings  directed  lends_to
20                                 united overseas bank uob          sinar mas group  directed  lends_to
21                                 united overseas bank uob     wilmar international  directed  lends_to
22                                                     mufg                    bunge  directed  lends_to
23                                                     mufg      cofco international  directed  lends_to
24                                                     mufg             gunvor group  directed  lends_to
25                                                     mufg                 mercuria  directed  lends_to
26                                                     mufg      six one commodities  directed  lends_to
27                                                     mufg          trafigura group  directed  lends_to
28                                                     smbc      cofco international  directed  lends_to
29                                                     smbc             gunvor group  directed  lends_to
30                                                     smbc    louis dreyfus company  directed  lends_to
31                                                     smbc    mercuria energy group  directed  lends_to
32                                                     smbc    olam food ingredients  directed  lends_to
33                                                     smbc                rio tinto  directed  lends_to
34                                                     smbc          trafigura group  directed  lends_to
35                                                     smbc                     vale  directed  lends_to
36                                                     smbc              vitol group  directed  lends_to
37                                                     smbc     wilmar international  directed  lends_to
38                                          credit agricole      cofco international  directed  lends_to
39                                          credit agricole             gunvor group  directed  lends_to
40                                          credit agricole    mercuria energy group  directed  lends_to
41                                          credit agricole          trafigura group  directed  lends_to
42                                          credit agricole              vitol group  directed  lends_to
43                                                     hsbc                 glencore  directed  lends_to
44                                                     hsbc             gunvor group  directed  lends_to
45                                                     hsbc       olam agri holdings  directed  lends_to
46                                                     hsbc          sinar mas group  directed  lends_to
47                                                     hsbc              vitol group  directed  lends_to
48                                                  natixis      cofco international  directed  lends_to
49                                                  natixis             gunvor group  directed  lends_to
50                                                  natixis          trafigura group  directed  lends_to
51                                                  natixis              vitol group  directed  lends_to
52                           bank of china singapore branch         unipec singapore  directed  lends_to
53                 china construction bank singapore branch          trafigura group  directed  lends_to
54                                    icbc singapore branch          trafigura group  directed  lends_to
55              agricultural bank of china singapore branch      trafigura beheer bv  directed  lends_to
56   shanghai pudong development bank spdb singapore branch                      NaN  directed  lends_to
57                               mufg bank singapore branch  mercuria energy trading  directed  lends_to
58                          macquarie bank singapore branch                      NaN  directed  lends_to
59      commonwealth bank of australia cba singapore branch                      NaN  directed  lends_to
60                                anz bank singapore branch                      NaN  directed  lends_to
61             westpac banking corporation singapore branch                      NaN  directed  lends_to
62             national australia bank nab singapore branch                      NaN  directed  lends_to
63                        cimb bank berhad singapore branch                      NaN  directed  lends_to
64                         malayan banking berhad singapore                      NaN  directed  lends_to
65                         rhb bank berhad singapore branch                      NaN  directed  lends_to
66                   bank of east asia bea singapore branch                      NaN  directed  lends_to
67                     state bank of india singapore branch                      NaN  directed  lends_to
68                              dz bank ag singapore branch                      NaN  directed  lends_to
69                        deutsche bank ag singapore branch                      NaN  directed  lends_to
70                          commerzbank ag singapore branch                      NaN  directed  lends_to
71                                       citibank singapore                      NaN  directed  lends_to
72                           goldman sachs singapore branch                      NaN  directed  lends_to
73                     jpmorgan chase bank singapore branch                      NaN  directed  lends_to
74                                    bbva singapore branch                      NaN  directed  lends_to
75                         bank of america singapore branch                      NaN  directed  lends_to
76                                                  ossiano                      NaN  directed  lends_to
77                                                    copap                      NaN  directed  lends_to
78                                        tradeflow capital                      NaN  directed  lends_to
79                                                  mercore                      NaN  directed  lends_to
80                                                 audentia                      NaN  directed  lends_to
81                                         ed&f man capital                      NaN  directed  lends_to
82                                                czarnikow                      NaN  directed  lends_to
83                                         sucden financial                      NaN  directed  lends_to
84                                             drip capital                      NaN  directed  lends_to
85                                                incomlend                      NaN  directed  lends_to
86                                              gxs capital                      NaN  directed  lends_to
87                                               fs capital  new & novel engineering  directed  lends_to
88                                               fs capital            the daily cut  directed  lends_to
89                                               fs capital         vyas engineering  directed  lends_to
90                                              ifs capital                      NaN  directed  lends_to
91                               straits financial services                      NaN  directed  lends_to
92                                                gb helios                      NaN  directed  lends_to
93                              nomura securities singapore                      NaN  directed  lends_to
94                                              adm capital                      NaN  directed  lends_to
95                                       hong leong finance                      NaN  directed  lends_to
96                                         eastvine capital                      NaN  directed  lends_to
97                               sing investments & finance                      NaN  directed  lends_to
98                                        zma smart capital                      NaN  directed  lends_to
99                                   mufg trading singapore                      NaN  directed  lends_to
100                                  orix leasing singapore                      NaN  directed  lends_to
101                                  capital match platform                      NaN  directed  lends_to
102                                        seatown holdings                      NaN  directed  lends_to
103                                             modifi asia                      NaN  directed  lends_to
104                                        stonex financial                      NaN  directed  lends_to
105                        horizon capital ag singapore rep                      NaN  directed  lends_to
106                              hartree partners singapore                      NaN  directed  lends_to
107                                        traxys singapore                      NaN  directed  lends_to
108                         freepoint commodities singapore           the prax group  directed  lends_to