In [16]:
import pandas as pd

# display columns without truncation
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

# display rows without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.expand_frame_repr", False)

In [17]:
p3 = pd.read_csv(
    r"D:\commo\code\Pillar 3 - Financing Data(Active_sheet).csv", encoding="utf-8"
)

# drop columns
p3 = p3.drop(
    columns=[
        "Amount of money they give to traders (Min – Max)",  # important but undisclosed
        "Transaction Volume (number of transaction per year)",  # important but undisclosed
        "Key Contact Name SG",
        "Key Contact Title",
        "Key Contact Email",
        "Key Contact Phone",
        "Insurance Gap / Opportunity",
        "Relationship Status",
        "Priority (H/M/L)", 'Done By'
    ]
)
# rename columns
p3.rename(
    columns={"Category (Bank / Alt. / ECA / Fund)":'Category', 'Known Clients / Portfolio': 'Known Clients', 'Strategic Notes':'Notes'},
    inplace=True,
)
# drop empty rows
p3 = p3.dropna(subset=['Category'])
#fill in missing val with Unknown
p3.fillna({
    'Commodity Focus': 'Unknown',
    'Known Clients': 'Unknown',
    'Notes': ''
}, inplace=True)
# fill in missing val with Unknown

p3

                                                    Institution Name               Category                                                                                                                                                                                                                                                              Commodity Focus                                                                                                                                                                                                                              Geographic Reach                                                                                                                                                                                                                                         Known Clients                                                                                                                                                                                                                                                                                                                                                                                                                                     Notes
1                                                                ING       Traditional Bank                                                                                                                                                                                                                         energy, hard commo (metals), soft commo (perplexity)                                                                                                                                                                               EMEA, APAC, Americas (https://www.ingwb.com/en/service/contact)                                                                                                                                                    Trafigura, Glencore, Gunvor, Vitol, Mercuria Energy, Auramet, Agritrade International (perplexity)
2                                                   Société Générale       Traditional Bank                                                                                                                                                                                                                                             energy, metal, soft (perplexity)                                                                                                       Primary base (Paris, Geneva, Western Europe), North America, APAC, emerging markets (Africa, parts of Asia, Latin America) (perplexity)                                                                                                                               n/a; Traders, Producers, Processors, Refiners, Distributors, and Corporates with commodity financing needs (perplexity)
3                                                        BNP Paribas       Traditional Bank                                                                                                                           Metals & Mining (base metals, precious metals), Agribusiness (agricultural materials, soft commodities), and Energy (petroleum, oil)  (perplexity)                                                                                                                         Europe (Paris hq), Americas (North/South America), APAC, Africa. Global network spans over 100 countries (perplexity)                                                                                                                                                                                                           Phoenix Commodities, GP Global (perplexity)                                                                                                                                                                                                                                                                                          sep 2020: BNP Paribas Suisse discontinued financing commodity trading and announced restructuring affecting 120 employees in Geneva (perplexity)
4                                                           Rabobank       Traditional Bank                                                                                                                                                                                                                                             energy, metal, soft (perplexity)                                                                                                              EU, Americas, Asia, Africa, ~38 countries across Europe, North America, South America, Asia, Australia, New Zealand (perplexity)                                                                                                                                                                                           Concord Resources Limited, GP Global, Sucafina (perplexity)
5                                                 Standard Chartered       Traditional Bank  copper, aluminum, oil, gas, petroleum, energy, metals, base metals, precious metals, agriculture, agribusiness, agricultural materials, soft commodities, energy transition commodities, critical metals, sustainable commodities, decarbonisation commodities (perplexity)  Asia-Pacific (Hong Kong, Singapore – major hubs), China & India (key drivers), Africa (12+ markets: Nigeria, Kenya, Ghana, South Africa, Tanzania, Botswana, etc.), Middle East (UAE, Dubai as Gulf hub), Latin America, UK, US (perplexity)                                                                                                                   Marubeni, Serenditpity International Trading ltd, Trafigura, glencore, seatrium, ducab, posco, walton hi-tech (sc.com + perplexity)
6                                                                DBS       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)              Southeast Asia (Singapore, Indonesia), Greater China (China, Hong Kong, Taiwan), South Asia (India), Australia, Europe (London office), Africa, Middle East, Latin America (via IFC-GTLP emerging markets program)  (perplexity)                                 Hin Leong Trading Pte Ltd, Agrocorp International, Maptrasco, Trafigura, Wilmar International Limited, Louis Dreyfus Company, Nanjing Iron & Steel, Singapore Jinteng International, Baosteel, Rio Tinto (perplexity)
7                                                               OCBC       Traditional Bank                                                                           Energy (oil, petroleum), Metals (base metals, precious metals), Agriculture (agricultural materials, soft commodities). OCBC also covers commodities in both vanillas and derivatives (perplexity)                                                        Southeast Asia (Singapore, Indonesia, Malaysia, Myanmar, Thailand, Vietnam), Greater China (China, Hong Kong, Taiwan), Asia (Asean: 340+ branches), Europe, Australia, US (perplexity)                                                                                                                                                                                                                                               Unknown
8                                                                UOB       Traditional Bank                                                                                                                                                                       energy, metals, soft commodities, hedging products (FX, price, interest rate derivatives) (perplexity)                                              Australia, brunei, canada, mainland china, france, hong kong, india, indonesia, japan, malaysia, myanmar, philippines, singapore, south korea, taiwan, thailand, uk, usa, vietnam (uobgroup.com)                                                                                           Wilmar International, Musim Mas Group, Cargill, Sinar Mas Group, Sinar Mas Group, Barramundi Group, Hin Leong Trading, Agritrade International (perplexity)
9                                                               MUFG       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)                                                                         ~50 countries, ~3,000 locations globally; strong in Asia Pacific (18 markets), EMEA (Europe, Middle East, Africa with Amsterdam desk), and North America (perplexity)                                                                                                 Trafigura, Gunvor, Cofco International, Bunge, Six One Commodities, Mercuria, Gold Fields (SSL Loan), Norilsk Nickel (Swiss trading arm) (perplexity)
10                                                              SMBC       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)                                                                                                                               Japan (HQ), SEA, China, South Asia, Middle East, Africa, EU, North America, Latin America, Oceania (perplexity)                                                                            Vitol Group, Trafigura, Mercuria Energy Group, Gunvor Group, Vale, Rio Tinto, Wilmar International, COFCO International, Olam Food Ingredients, Louis Dreyfus (perplexity)                                                                                                                                                                                                                                                                                                                                                                           SMBC remains fully active in commodity trade finance as of 2026
11                                                   Crédit Agricole       Traditional Bank                                                                                                                                                                                                          Energy, Ferrous & Non-Ferrous Metals, Soft Commodities (perplexity)                                                                                                                               Switzerland/Western EU (HQ), Americas, APAC, SEA, Middle East, Greater China, Korea, Japan, Africa (perplexity)                                                                                         Vitol Group, Trafigura, Mercuria Energy Group, Gunvor Group, Vale, Glencore, Louis Dreyfus Company (LDC), COFCO International, IFC (World Bank)  (perplexity)
12                                                              HSBC       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)                                                                                                                                                              APAC, North America, Latin America, EMEA, MENAT, Sub-saharan africa (perplexity)                                               Vitol Group, Glencore, Gunvor Group, Hin Leong Trading, ZenRock Commodities Trading, Olam Agri / Olam Group, Cargill, Sinar Mas / APRIL Group, IFC Global Trade Liquidity Programme (GTLP) (perplexity)
13                                                           Natixis       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)                                                                                                                                                                           France / EU (hq), Americas, APAC, Middle East / Africa (perplexity)                                                                                                             Trafigura, Mercuria Energy, Gunvor Group, Vitol Group, Glencore Energy UK, COFCO International, Addax Energy (Oryx Energies) (perplexity)
14                                   Bank of China, Singapore Branch                   Bank                                                                                                                                                                                                                                          energy/oil commodities (perplexity)                                                                                                                                                                                                                      APAC, ASEAN (perplexity)                                                                                                                                                                                                                         Unipec Singapore (perplexity)
15                         China Construction Bank, Singapore Branch                   Bank                                                                                                                                                                                                                              General commodity trade financing  (perplexity)                                                                                                                                                                                     Singapore, China, South Asia, Southeast Asia (perplexity)                                                                                                                                                                                                                Trafigura Group Pte. Ltd. (perplexity)
16                                            ICBC, Singapore Branch                   Bank                                                                                                                                                                                                                                           energy and hard commo (perplexity)                                                                                                                                                                                                   Global with Asia-Pacific focus (perplexity)                                                                                                                                                                                                                                Trafigura (perplexity)
17                      Agricultural Bank of China, Singapore Branch                   Bank                                                                                                                                                                                                                                                 Metals and Oil  (perplexity)                                                                                                                                                                                                                          SG, SEA (perplexity)                                                                                                                                                                                         Trafigura Beheer BV / Trafigura Group Pte. Ltd.  (perplexity)
18         Shanghai Pudong Development Bank (SPDB), Singapore Branch                   Bank                                                                                                                                                                                                                              General commodity trade financing  (perplexity)                                                                                                                                                                                                                          SG, SEA (perplexity)                                                                                                                                                                                                                                               Unknown
19                                       MUFG Bank, Singapore Branch                   Bank                                                                                                                                                                                                                                 Energy, Hard & Soft Commodities (perplexity)                                                                                                                                                                                              Global with emerging markets focus  (perplexity)                                                                                                                                                                                                                 Mercuria Energy Trading  (perplexity)
20                                  Macquarie Bank, Singapore Branch                   Bank                                                                                                                                                                                                                                                  energy, metals (perplexity)                                                                                                                                                                                                                             ASIA (perplexity)                                                                                                                                                                                                                                               Unknown
21            Commonwealth Bank of Australia (CBA), Singapore Branch                   Bank                                                                                                                                                                                                                                    carbon and trade commodities (perplexity)                                                                                                                                                                                                                             APAC (perplexity)                                                                                                                                                        The bank primarily serves Australian and New Zealand businesses operating in Asia (perplexity)

In [18]:
p3.info()

<class 'pandas.DataFrame'>
Index: 69 entries, 1 to 72
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Institution Name  69 non-null     str
 1   Category          69 non-null     str
 2   Commodity Focus   69 non-null     str
 3   Geographic Reach  69 non-null     str
 4   Known Clients     69 non-null     str
 5   Notes             69 non-null     str
dtypes: str(6)
memory usage: 3.8 KB

In [19]:
p3.isna().sum()

Institution Name    0
Category            0
Commodity Focus     0
Geographic Reach    0
Known Clients       0
Notes               0
dtype: int64

In [20]:
# check institution name

# pte. ltd. > pte ltd
# limited > ltd
p3["Institution Name"] = p3["Institution Name"].str.replace(r'\bpte|private\b', 'Pte', regex=True, case=False)
p3["Institution Name"] = p3["Institution Name"].str.replace(r'\bltd|limited\b', 'Ltd', regex=True, case=False)
p3["Institution Name"] = p3["Institution Name"].str.strip()
p3['Institution Name'].unique()

<StringArray>
[                                                             'ING',
                                                 'Société Générale',
                                                      'BNP Paribas',
                                                         'Rabobank',
                                               'Standard Chartered',
                                                              'DBS',
                                                             'OCBC',
                                                              'UOB',
                                                             'MUFG',
                                                             'SMBC',
                                                  'Crédit Agricole',
                                                             'HSBC',
                                                          'Natixis',
                                  'Bank of China, Singapore Branch',
                        'China Construction Bank, Singapore Branch',
                                           'ICBC, Singapore Branch',
                     'Agricultural Bank of China, Singapore Branch',
        'Shanghai Pudong Development Bank (SPDB), Singapore Branch',
                                      'MUFG Bank, Singapore Branch',
                                 'Macquarie Bank, Singapore Branch',
           'Commonwealth Bank of Australia (CBA), Singapore Branch',
                                       'ANZ Bank, Singapore Branch',
                    'Westpac Banking Corporation, Singapore Branch',
                  'National Australia Bank (NAB), Singapore Branch',
                               'CIMB Bank Berhad, Singapore Branch',
 'Maybank Singapore Ltd / Malayan Banking Berhad, Singapore Branch',
                                'RHB Bank Berhad, Singapore Branch',
                        'Bank of East Asia (BEA), Singapore Branch',
                            'State Bank of India, Singapore Branch',
                                     'DZ Bank AG, Singapore Branch',
                               'Deutsche Bank AG, Singapore Branch',
                                 'Commerzbank AG, Singapore Branch',
                           'Citibank N.A. / Citi, Singapore Branch',
                                  'Goldman Sachs, Singapore Branch',
                            'JPMorgan Chase Bank, Singapore Branch',
                                           'BBVA, Singapore Branch',
                                'Bank of America, Singapore Branch',
                                                          'Ossiano',
                                                            'Copap',
                                                'Tradeflow Capital',
                                                          'Mercore',
                                                         'Audentia',
                                                            'Komgo',
                                                 'ED&F Man Capital',
                                                        'Czarnikow',
                                                 'Sucden Financial',
                                                     'Drip Capital',
                                              'Incomlend Pte. Ltd.',
                   'GXS Capital Pte. Ltd. (f.k.a. Validus Capital)',
                         'FS Capital Pte. Ltd. (Funding Societies)',
                                                  'IFS Capital Ltd',
                             'Straits Financial Services Pte. Ltd.',
         'GB Helios Pte. Ltd. (f.k.a. Goldbell Financial Services)',
                          'Nomura Securities (Singapore) Pte. Ltd.',
                                                      'ADM Capital',
                                           'Hong Leong Finance Ltd',
                                         'EASTvine Capital Pte Ltd',
                                   'Sing Investments & Finance Ltd',
                                      'ZMA Smart Capital Pte. Ltd.',
                               'MUFG Trading (Singapore) Pte. Ltd.',
                                       'ORIX Leasing Singapore Ltd',
                                 'Capital Match Platform Pte. Ltd.',
                                       'SeaTown Holdings Pte. Ltd.',
                                            'Modifi Asia Pte. Ltd.',
                                       'StoneX Financial Pte. Ltd.',
                               'Horizon Capital AG (Singapore rep)',
                              'Hartree Partners Singapore Pte. Ltd',
                                       'Traxys Singapore Pte. Ltd.',
                        'Freepoint Commodities Singapore Pte. Ltd.']
Length: 69, dtype: str

In [21]:
# check category
cat_map = {"Bank": "Traditional Bank"}
p3["Category"] = p3["Category"].replace(cat_map).str.strip()
p3["Category"].unique()

<StringArray>
['Traditional Bank', 'Alternative Financier']
Length: 2, dtype: str

In [33]:
# check commo focus
import re

# make a copy
if "Commodity Focus copy" not in p3.columns:
    p3["Commodity Focus copy"] = p3["Commodity Focus"].copy()

# remove brackets
copy = p3['Commodity Focus copy'].str.replace(r'\(.*?\)','', regex=True).str.strip()
# remove double spacing
copy = p3['Commodity Focus copy'].str.replace(r'\s+',' ', regex=True).str.strip()

# 'hard/metals': hard commo (metals), metal, Metals & Mining (base metals, precious metals), copper, aluminum, metals, base metals, precious metals, critic metals, Metals (base metals, precious metals), Ferrous & Non-Ferrous Metals, Base & Precious Metals (copper, aluminum, zinc, gold), Metals & Minerals, base/precious metals, coal, iron ore, base metals industrial metals, and precious metals, and metals, metals & minerals,
# 'soft/agricultural': soft commo, soft, agribusiness (agricultural materals, soft commodities), agriculture, agribusiness, agricultural materials, soft commodities, Agriculture (agricultural materials, soft commodities). , and Agribusiness (wheat, barley, cotton, sugar, soy, palm oil), and agricultural commodities, Food & Agribusiness, agricultural products, soft commodities, forest products (pulp, paper), bulk physical commodities like cocoa, coffee, grains, rice, soft commodities (biofuels, agricultural),  agricultural products, agriculture/softs
# 'energy': energy, and Energy (petroleum, oil), oil, gas, petroleum, energy transition commodities, Energy (oil, petroleum), energy/oil commodities, Energy (crude oil, fuel oil, LNG), crude oil, petroleum products (major crude oil distillates), iron ore, fuel oil, gas oil, crude oil, oil products, and US/European natural gas, oil, natural gas, power, European power, gas, coal, and North American gas/power, electricity, liquefied natural gas, Energy/oil, general, energy(oil, gas, electricity), Energy (incl. coal, selectively), Energy (biofuels), Energy commo
# 'others': OCBC also covers commodities in both vanillas and derivatives, hedging products (FX, price, interest rate derivatives), General commodity trade financing, fixed income, currencies & commodities services under corporate and institutional banking, specialize in trade banking, corporate banking, investment banking, and international banking services, foreign exchange and fixed income, fx and fixed income, trade finance for a broad range of cross‑border physical commodity trades executed on Zall / CIC B2B platforms
# 'petrochemicals': Chemicals,  petrochemical, polymer,  chemicals & plastics
# 'emerging': sustainable commodities, decarbonisation commodities, and carbon markets
# 'Unknown': n/a; , product agnostic, agnostic, sector‑agnostic SME lender

# ['energy', hard/metals']: energy and hard commo, Metals and Oil, Energy/hard commodity primarily coal trading, hard commodities – non‑ferrous metals, ferro‑alloys, minerals, industrial raw materials and related energy products
# ['energy', hard/metals', 'soft/agriculture']: primarily energy and hard commodities – oil and refined products (crude, fuel oil, middle distillates), gas, coal, emissions, plus metals and some agricultural products
# ['hard/metals','soft/agricultural']: Hard & Soft Commodities

# idk: carbon and trade commodities, conducted trade finance for dairy products, emissions, refined products, refinery products, textiles & apparel, industrial goods & machinery, handicrafts, home furnishings & consumer goods, apparel
# delete: freight, in line with the Traxys group mandate

import re

if "Commodity Focus copy" not in p3.columns:
    p3["Commodity Focus copy"] = p3["Commodity Focus"].copy()

category_patterns = {
    "energy": [
        r"\blng\b", r"liqu[ei]fied natural gas", r"\bcrude\b", r"fuel oil",
        r"natural gas", r"\bcoal\b", r"\bpower\b", r"electricity", r"gas oil",
        r"biofuels?", r"refined products?", r"refinery products?",
        r"middle distillates?", r"\boil\b", r"\bpetroleum\b", r"\bgas\b",
        r"energy transition", r"\benergy\b",
    ],
    "hard/metals": [
        r"base metals?", r"precious metals?", r"industrial metals?",
        r"ferrous", r"non-ferrous", r"ferro-alloys?", r"\bcopper\b", r"\baluminum\b",
        r"\bzinc\b", r"\bgold\b", r"iron ore", r"critic\w* metals?",
        r"\bminerals?\b", r"industrial raw materials?", r"\bmining\b",
        r"\bmetals?\b", r"hard commo\w*",
    ],
    "soft/agricultural": [
        r"agribusiness", r"agricultur\w*", r"soft commodit\w*", r"\bsofts?\b",
        r"\bwheat\b", r"\bbarley\b", r"\bcotton\b", r"\bsugar\b", r"\bsoy\b",
        r"palm oil", r"\bcocoa\b", r"\bcoffee\b", r"\bgrains?\b", r"\brice\b",
        r"\bdairy\b", r"forest products?", r"\bpulp\b", r"\bpaper\b", r"\bfood\b",
    ],
    "petrochemicals": [
        r"petrochemical", r"\bpolymer\b", r"\bplastics?\b", r"\bchemicals?\b",
    ],
    "emerging": [
        r"sustainable commodit\w*", r"decarbonisation", r"decarbonization",
        r"carbon markets?", r"emissions?", r"\bcarbon\b",
    ],
}

def expand_slash_compounds(text):
    return re.sub(
        r"\b([\w-]+)\s*(?:/|&|,?\s+and)\s*([\w-]+)\s+(metals?|commodities|natural gas|banking)\b",
        r"\1 \3, \2 \3", text, flags=re.IGNORECASE,
    )

def classify_row(raw):
    if not isinstance(raw, str) or not raw.strip():
        return ["Unknown"]

    text = re.sub(r"\s*\(([^()]*)\)\s*$", "", raw).strip()  # drop trailing (source citation)

    # only a bare "n/a" / "n/a;" with nothing else -> Unknown
    if re.match(r"^n/a\s*;?\s*$", text, flags=re.IGNORECASE):
        return ["Unknown"]
    if re.search(r"\bagnostic\b", text, flags=re.IGNORECASE):
        return ["Unknown"]

    text_l = expand_slash_compounds(text).lower()

    matched = [cat for cat, patterns in category_patterns.items()
               if any(re.search(p, text_l) for p in patterns)]

    return matched if matched else ["others"]

p3["Commodity Focus"] = copy.apply(classify_row)
p3["Commodity Focus"] = p3["Commodity Focus"].apply(
    lambda x: ", ".join(x) if isinstance(x, list) else x
)
p3["Commodity Focus"]

0                     energy, hard/metals, soft/agricultural
1                     energy, hard/metals, soft/agricultural
2                     energy, hard/metals, soft/agricultural
3                     energy, hard/metals, soft/agricultural
4           energy, hard/metals, soft/agricultural, emerging
5                     energy, hard/metals, soft/agricultural
6                     energy, hard/metals, soft/agricultural
7                     energy, hard/metals, soft/agricultural
8                     energy, hard/metals, soft/agricultural
9                     energy, hard/metals, soft/agricultural
10                    energy, hard/metals, soft/agricultural
11                    energy, hard/metals, soft/agricultural
12                    energy, hard/metals, soft/agricultural
13                                                    energy
14                                                    others
15                                       energy, hard/metals
16                                       energy, hard/metals
17                                                    others
18                    energy, hard/metals, soft/agricultural
19                                       energy, hard/metals
20                                                  emerging
21                    energy, hard/metals, soft/agricultural
22                    energy, hard/metals, soft/agricultural
23                                                    others
24                                         soft/agricultural
25                    energy, hard/metals, soft/agricultural
26                                                    others
27    energy, hard/metals, soft/agricultural, petrochemicals
28                    energy, hard/metals, soft/agricultural
29                                                    energy
30                             energy, hard/metals, emerging
31                                                    others
32                                       energy, hard/metals
33          energy, hard/metals, soft/agricultural, emerging
34                                         soft/agricultural
35                                                    others
36                                       energy, hard/metals
37                         soft/agricultural, petrochemicals
38                         soft/agricultural, petrochemicals
39                    energy, hard/metals, soft/agricultural
40                                                    others
41                                                    energy
42                    energy, hard/metals, soft/agricultural
43                    energy, hard/metals, soft/agricultural
44                                                   Unknown
45                    energy, hard/metals, soft/agricultural
46                         soft/agricultural, petrochemicals
47                            hard/metals, soft/agricultural
48                                                   Unknown
49                                                   Unknown
50                                                   Unknown
51                    energy, hard/metals, soft/agricultural
52                                                    energy
53                    energy, hard/metals, soft/agricultural
54                                         soft/agricultural
55                                                   Unknown
56                    energy, hard/metals, soft/agricultural
57                                                   Unknown
58                                                    others
59                                       energy, hard/metals
60                                                   Unknown
61                                                   Unknown
62                                                    others
63                                                   Unknown
64                    energy, hard/metals, soft/agricultural
65                    energy, hard/metals, soft/agricultural
66                                       energy, hard/metals
67                                       energy, hard/metals
68          energy, hard/metals, soft/agricultural, emerging
Name: Commodity Focus, dtype: str

In [23]:
# drop the copy
p3 = p3.drop(columns=["Commodity Focus copy"])

In [24]:
p3.isna().sum()

Institution Name    0
Category            0
Commodity Focus     0
Geographic Reach    0
Known Clients       0
Notes               0
dtype: int64

In [25]:
# geographic reach standardization
# remove brackets and whitespace
p3["Geographic Reach"] = p3["Geographic Reach"].str.replace(r'\(.*?\)','',regex=True).str.strip()
p3["Geographic Reach"].unique()

<StringArray>
[                                                                                                                                                                                                    'EMEA, APAC, Americas',
                                                                                                                                                                     'Primary base , North America, APAC, emerging markets',
                                                                                                                                                'Europe , Americas , APAC, Africa. Global network spans over 100 countries',
                                                                                                      'EU, Americas, Asia, Africa, ~38 countries across Europe, North America, South America, Asia, Australia, New Zealand',
                                                                                                                                              'Asia-Pacific , China & India , Africa , Middle East , Latin America, UK, US',
                                                                                                                     'Southeast Asia , Greater China , South Asia , Australia, Europe , Africa, Middle East, Latin America',
                                                                                                                                                            'Southeast Asia , Greater China , Asia , Europe, Australia, US',
                                        'Australia, brunei, canada, mainland china, france, hong kong, india, indonesia, japan, malaysia, myanmar, philippines, singapore, south korea, taiwan, thailand, uk, usa, vietnam',
                                                                                                                              '~50 countries, ~3,000 locations globally; strong in Asia Pacific , EMEA , and North America',
                                                                                                                           'Japan , SEA, China, South Asia, Middle East, Africa, EU, North America, Latin America, Oceania',
                                                                                                                           'Switzerland/Western EU , Americas, APAC, SEA, Middle East, Greater China, Korea, Japan, Africa',
                                                                                                                                                      'APAC, North America, Latin America, EMEA, MENAT, Sub-saharan africa',
                                                                                                                                                                       'France / EU , Americas, APAC, Middle East / Africa',
                                                                                                                                                                                                              'APAC, ASEAN',
                                                                                                                                                                             'Singapore, China, South Asia, Southeast Asia',
                                                                                                                                                                                           'Global with Asia-Pacific focus',
                                                                                                                                                                                                                  'SG, SEA',
                                                                                                                                                                                       'Global with emerging markets focus',
                                                                                                                                                                                                                     'ASIA',
                                                                                                                                                                                                                     'APAC',
                                                                                                                                                                                                                   'global',
                                                                                                                                                         'Asia, New Zealand, Europe, North America, and the Pacific region',
                                                                                                                         'Asia , UK, and US, with Singapore serving as a preferred regional center after exiting Hong Kong',
                                                                                                                                                                                                                    'ASEAN',
 'Malaysia, Singapore, Indonesia as home markets, plus Philippines, Brunei Darussalam, Vietnam, Cambodia, Thailand, Hong Kong SAR, China, Bahrain, Pakistan, Papua New Guinea, Uzbekistan, Saudi Arabia, UK, US, and India',
                                                                                               'Malaysia, Singapore, Indonesia, Thailand, Cambodia, Vietnam, China, Myanmar, Brunei, Laos, Hong Kong, Pakistan, and the UK',
                                                                                                                               'Greater China plus branches in New York, Los Angeles, Great Britain, Labuan, and Singapore',
                                                                                                                                                                                                                'SG, India',
                                                                                                  'Southeast Asia, India, and the broader Asia/Pacific region, serving as a hub for German, Swiss, and Austrian corporates',
                                                                                                                                                                                                             'ASIA, global',
                                                                                                                                                                                                              'ASIA, ASEAN',
                                                                                                                                               'APAC, China, SEA, AUS, NZ, New York, Houston, London, Singapore, and Tokyo',
                                                                                                                                                                                                                'APAC, SEA',
                                                                                                                                        'Asia, APAC, latin america, Spain, Mexico, South America, United States and Turkey',
                                                                                                                                                                                                               'Asia, APAC',
                                                                                                                                                                                                                   'Global',
                                                                                                                                       'Global, 18+ countries served; particularly in developing-economy rural communities',
                                                                                                                                                                                                          'UK & EU, Africa',
                                                                                                                                                              'Geneva, London, Paris, Singapore, Australia, Miami, Toronto',
                                                                                                                                                                                   'EMEA, North America, APAC, Middle East',
                                                                                                                       'Thailand, Mexico, Dubai, USA, China, Kenya, Vietnam, UK, Brazil, Philippines, SG, Colombia, Israel',
                                                                                                                                                                            'london , hong kong, new york, moscow, hamburg',
                                                                                                                                                                                'India, USA, Mexico, global buyers/sellers',
                                                                                                                                                                          'SEA, East/North Asia, Middle East, EU, Americas',
                                                                                                                                                                                                                'Singapore',
                                                                                                                  'Southeast Asia, with a focus on the ASEAN core of Singapore, Indonesia, Malaysia, Thailand, and Vietnam',
                                                                                                                                                                             'SG, Thailand, Malaysia, Indonesia, Hong Kong',
                                                                                                                                                                                           'SG, USA, Indonesia, China, UAE',
                                                                                                                                                                                                                       'SG',
                                                                                                                                                                                          'APAC, EU, Middle East, Americas',
                                                                                                                                                                         'Indonesia, SEA, APAC, North America, EU, AUS, NZ',
                                                                                                                                                                                                                 'SG, Asia',
                                                                                                                                                                                                               'SG, Global',
                                                                                                                                                                          'Europe, Asia, the Middle East and North America',
                                                                                                                                                                                          'APAC, Americas, EU, Middle East',
                                                                                                                                                                                           'Europe, Asia and North America']
Length: 56, dtype: str

In [30]:
# check 'Known Clients'
p3["Known Clients"].unique()

# delete the sources because they are all perplexity and the only one from an official source don't mention any names. All are officially undisclosed.
# any row that includes 'n/a' or nan > replace the whole row with 'Unkown'
#  'SMEs in bulk commodity markets (https://tradeflow.capital/esg)' = no names = replace with 'Unkown'
# 'P.T Kebun Tebu Mas (KTM), commodity producers, processors, and buyers along its supply chain (e.g., sugar mills, food ingredient suppliers, energy product buyers) (perplexity)' = replace with 'P.T Kebun Tebu Mas (KTM)
# keep brackets but no split if inside brackets
#'SMEs (annual revenues typically below USD 50m); Exporters of plastic products, frozen foods,  red chillies, Basmati rice, shrimp and rice, avocados, Textiles and industrial equipment  (perplexity)' = no names = replace with 'Unknown'
# 'Fashion Tex Asia Ltd, Sadat Apparels Ltd, SafeFlex Limited International, Pan-European metal trading firm, US-based apparel trading company, China-based apparel manufacturer, China-based apparel manufacturer (perplexity)' =  'Fashion Tex Asia Ltd, Sadat Apparels Ltd, SafeFlex Limited International'
# Limited or ltd or ltd. becomes Ltd
# pte. becomes pte
# all names have to be capitalized the first letter
#'A Singapore-based marine-sector supplier, A leading bottled-drink manufacturer in Thailand (perplexity)' = 'Unknown'
#'PT Bening Big Tree Farms (BTFI), ACLF portfolio SMEs, Square Yards (India),  India Cements, Bangkok Mass Transit System, Rizal Commercial Banking Corporation (perplexity)' = 'PT Bening Big Tree Farms (BTFI), ACLF portfolio SMEs, Square Yards (India), Rizal Commercial Banking Corporation (perplexity)'
# 'InMobi (India‑based adtech firm) received US$350m loan (perplexity)' = 'Unknown'
#  'a Swiss commodities trading firm active in biofuels (perplexity)' = 'Unknown'
# 'The Prax Group (USD 350 million inventory financing facility), various energy/clean-fuels structures (e.g. Green Plains 45Z credits), and equity/project investments such as Nostromo (perplexity)' =  'The Prax Group (perplexity)'
# GP, SSL, COFCO, LDC, IFC, GTLP, APRIL, UK, BV, ABN AMRO, BNP, CA, TOTSA, ING, MUFG, C2G2, PT , PLC  ,
# IncuBaker, MoneySmart, xSquare
import re

def normalize_key(s):
    if not isinstance(s, str):
        return s
    return (s.replace('\u2011', '-').replace('\u2013', '-')
             .replace('\u2019', "'").strip())

manual_overrides = {
    normalize_key('n/a; Traders, Producers, Processors, Refiners, Distributors, and Corporates with commodity financing needs (perplexity)'): ['Unknown'],
    normalize_key('SMEs in bulk commodity markets (https://tradeflow.capital/esg)'): ['Unknown'],
    normalize_key('P.T Kebun Tebu Mas (KTM), commodity producers, processors, and buyers along its supply chain (e.g., sugar mills, food ingredient suppliers, energy product buyers) (perplexity)'):
        ['P.T Kebun Tebu Mas'],
    normalize_key('n/a; banks, proprietary trading firms, hedge funds, pension funds, asset managers, and large corporations seeking execution/clearing, liquidity, and prime brokerage. (perplexity)'): ['Unknown'],
    normalize_key('SMEs (annual revenues typically below USD 50m); Exporters of plastic products, frozen foods,  red chillies, Basmati rice, shrimp and rice, avocados, Textiles and industrial equipment  (perplexity)'): ['Unknown'],
    normalize_key('Fashion Tex Asia Ltd, Sadat Apparels Ltd, SafeFlex Limited International, Pan-European metal trading firm, US-based apparel trading company, China-based apparel manufacturer, China-based apparel manufacturer (perplexity)'):
        ['Fashion Tex Asia Ltd', 'Sadat Apparels Ltd', 'SafeFlex Limited International'],
    normalize_key('A Singapore-based marine-sector supplier, A leading bottled-drink manufacturer in Thailand (perplexity)'): ['Unknown'],
    normalize_key('PT Bening Big Tree Farms (BTFI), ACLF portfolio SMEs, Square Yards (India),  India Cements, Bangkok Mass Transit System, Rizal Commercial Banking Corporation (perplexity)'):
        ['PT Bening Big Tree Farms', 'Square Yards', 'Rizal Commercial Banking Corporation'],
    normalize_key('InMobi (India\u2011based adtech firm) received US$350m loan (perplexity)'): ['Unknown'],
    normalize_key('a Swiss commodities trading firm active in biofuels (perplexity)'): ['Unknown'],
    normalize_key('The Prax Group (USD 350 million inventory financing facility), various energy/clean-fuels structures (e.g. Green Plains 45Z credits), and equity/project investments such as Nostromo (perplexity)'):
        ['The Prax Group'],
    normalize_key('The bank primarily serves Australian and New Zealand businesses operating in Asia (perplexity)'): ['Unknown'],
    normalize_key('InMobi (India‑based adtech firm) received US$350m loan (perplexity)'):['Unknown'],
    normalize_key('The Prax Group (USD 350 million inventory financing facility), various energy/clean-fuels structures (e.g. Green Plains 45Z credits), and equity/project investments such as Nostromo (perplexity)'): ['The Prax Group']

}

# --- Acronyms that must always render in full uppercase, regardless of source casing ---
ACRONYMS = ['ABN AMRO', 'GP', 'SSL', 'COFCO', 'LDC', 'IFC', 'GTLP', 'APRIL',
            'UK', 'BV', 'BNP', 'CA', 'TOTSA', 'ING', 'MUFG', 'C2G2', 'PT', 'PLC']

def force_acronym_case(text):
    for acr in ACRONYMS:
        pattern = r'\b' + re.escape(acr) + r'\b'
        text = re.sub(pattern, acr, text, flags=re.IGNORECASE)
    return text

# --- Brand names with intentional non-standard casing that must be preserved exactly ---
BRAND_WHITELIST = ['IncuBaker', 'MoneySmart', 'xSquare']

def remove_brackets(text):
    text = re.sub(r'\(.*?\)', '', text)
    return re.sub(r'\s+', ' ', text).strip()

def standardize_suffixes(name):
    name = re.sub(r'\b(limited|ltd)\b\.?,?', 'Ltd', name, flags=re.IGNORECASE)
    name = re.sub(r'\bpte\b\.?,?', 'pte', name, flags=re.IGNORECASE)
    return re.sub(r'\s+', ' ', name).strip()

def capitalize_first(name):
    if not name:
        return name
    if name.isupper():
        return name  # e.g. "ABN AMRO", "ING" alone
    for brand in BRAND_WHITELIST:
        if name.lower().startswith(brand.lower()):
            return brand + name[len(brand):]  # preserve exact brand casing, e.g. "xSquare"
    return name[0].upper() + name[1:]

def is_generic_descriptor(clause):
    c = clause.strip()
    if re.match(r'^(a|an)\s', c, flags=re.IGNORECASE):
        return True
    if re.search(r'\b\w+-based\b', c, flags=re.IGNORECASE):
        return True
    return False

def clean_row(raw):
    if not isinstance(raw, str) or not raw.strip():
        return ['Unknown']

    key = normalize_key(raw)
    if key in manual_overrides:
        return manual_overrides[key]

    text = normalize_key(raw)
    if re.match(r'^n/a\s*;?\s*$', text, flags=re.IGNORECASE):
        return ['Unknown']

    text = remove_brackets(text)
    clauses = [c.strip() for c in text.split(',') if c.strip()]

    kept = []
    for c in clauses:
        if is_generic_descriptor(c):
            continue
        c = standardize_suffixes(c)
        c = force_acronym_case(c)
        c = capitalize_first(c)
        kept.append(c)

    return kept if kept else ['Unknown']

p3["Known Clients"] = p3["Known Clients"].apply(clean_row)
p3["Known Clients"] = p3["Known Clients"].apply(
    lambda x: ", ".join(x) if isinstance(x, list) else x
)

In [31]:
# check Notes
p3.fillna({'Notes': ''}, inplace=True)
p3["Notes"] = p3["Notes"].str.strip()

In [32]:
p3

                                                    Institution Name               Category                                                                                                                                                                                                                                                              Commodity Focus                                                                                                                                                                                                          Geographic Reach                                                                                                                                                                                                                    Known Clients                                                                                                                                                                                                                                                                                                                                                                                                                                     Notes
0                                                                ING       Traditional Bank                                                                                                                                                                                                                         energy, hard commo (metals), soft commo (perplexity)                                                                                                                                                                                                      EMEA, APAC, Americas                                                                                                                                            Trafigura, Glencore, Gunvor, Vitol, Mercuria Energy, Auramet, Agritrade International
1                                                   Société Générale       Traditional Bank                                                                                                                                                                                                                                             energy, metal, soft (perplexity)                                                                                                                                                                      Primary base , North America, APAC, emerging markets                                                                                                                                                                                                                          Unknown
2                                                        BNP Paribas       Traditional Bank                                                                                                                           Metals & Mining (base metals, precious metals), Agribusiness (agricultural materials, soft commodities), and Energy (petroleum, oil)  (perplexity)                                                                                                                                                 Europe , Americas , APAC, Africa. Global network spans over 100 countries                                                                                                                                                                                                   Phoenix Commodities, GP Global                                                                                                                                                                                                                                                                                          sep 2020: BNP Paribas Suisse discontinued financing commodity trading and announced restructuring affecting 120 employees in Geneva (perplexity)
3                                                           Rabobank       Traditional Bank                                                                                                                                                                                                                                             energy, metal, soft (perplexity)                                                                                                       EU, Americas, Asia, Africa, ~38 countries across Europe, North America, South America, Asia, Australia, New Zealand                                                                                                                                                                                       Concord Resources Ltd, GP Global, Sucafina
4                                                 Standard Chartered       Traditional Bank  copper, aluminum, oil, gas, petroleum, energy, metals, base metals, precious metals, agriculture, agribusiness, agricultural materials, soft commodities, energy transition commodities, critical metals, sustainable commodities, decarbonisation commodities (perplexity)                                                                                                                                               Asia-Pacific , China & India , Africa , Middle East , Latin America, UK, US                                                                                                                    Marubeni, Serenditpity International Trading Ltd, Trafigura, Glencore, Seatrium, Ducab, Posco, Walton hi-tech
5                                                                DBS       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)                                                                                                                      Southeast Asia , Greater China , South Asia , Australia, Europe , Africa, Middle East, Latin America                             Hin Leong Trading pte Ltd, Agrocorp International, Maptrasco, Trafigura, Wilmar International Ltd, Louis Dreyfus Company, Nanjing Iron & Steel, Singapore Jinteng International, Baosteel, Rio Tinto
6                                                               OCBC       Traditional Bank                                                                           Energy (oil, petroleum), Metals (base metals, precious metals), Agriculture (agricultural materials, soft commodities). OCBC also covers commodities in both vanillas and derivatives (perplexity)                                                                                                                                                             Southeast Asia , Greater China , Asia , Europe, Australia, US                                                                                                                                                                                                                          Unknown
7                                                                UOB       Traditional Bank                                                                                                                                                                       energy, metals, soft commodities, hedging products (FX, price, interest rate derivatives) (perplexity)                                         Australia, brunei, canada, mainland china, france, hong kong, india, indonesia, japan, malaysia, myanmar, philippines, singapore, south korea, taiwan, thailand, uk, usa, vietnam                                                                                   Wilmar International, Musim Mas Group, Cargill, Sinar Mas Group, Sinar Mas Group, Barramundi Group, Hin Leong Trading, Agritrade International
8                                                               MUFG       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)                                                                                                                               ~50 countries, ~3,000 locations globally; strong in Asia Pacific , EMEA , and North America                                                                                                                        Trafigura, Gunvor, COFCO International, Bunge, Six One Commodities, Mercuria, Gold Fields, Norilsk Nickel
9                                                               SMBC       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)                                                                                                                            Japan , SEA, China, South Asia, Middle East, Africa, EU, North America, Latin America, Oceania                                                                    Vitol Group, Trafigura, Mercuria Energy Group, Gunvor Group, Vale, Rio Tinto, Wilmar International, COFCO International, Olam Food Ingredients, Louis Dreyfus                                                                                                                                                                                                                                                                                                                                                                           SMBC remains fully active in commodity trade finance as of 2026
10                                                   Crédit Agricole       Traditional Bank                                                                                                                                                                                                          Energy, Ferrous & Non-Ferrous Metals, Soft Commodities (perplexity)                                                                                                                            Switzerland/Western EU , Americas, APAC, SEA, Middle East, Greater China, Korea, Japan, Africa                                                                                                     Vitol Group, Trafigura, Mercuria Energy Group, Gunvor Group, Vale, Glencore, Louis Dreyfus Company, COFCO International, IFC
11                                                              HSBC       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)                                                                                                                                                       APAC, North America, Latin America, EMEA, MENAT, Sub-saharan africa                                              Vitol Group, Glencore, Gunvor Group, Hin Leong Trading, ZenRock Commodities Trading, Olam Agri / Olam Group, Cargill, Sinar Mas / APRIL Group, IFC Global Trade Liquidity Programme
12                                                           Natixis       Traditional Bank                                                                                                                                                                                                                                Energy, Metals, Soft Commodities (perplexity)                                                                                                                                                                        France / EU , Americas, APAC, Middle East / Africa                                                                                                                     Trafigura, Mercuria Energy, Gunvor Group, Vitol Group, Glencore Energy UK, COFCO International, Addax Energy
13                                   Bank of China, Singapore Branch       Traditional Bank                                                                                                                                                                                                                                          energy/oil commodities (perplexity)                                                                                                                                                                                                               APAC, ASEAN                                                                                                                                                                                                                 Unipec Singapore
14                         China Construction Bank, Singapore Branch       Traditional Bank                                                                                                                                                                                                                              General commodity trade financing  (perplexity)                                                                                                                                                                              Singapore, China, South Asia, Southeast Asia                                                                                                                                                                                                          Trafigura Group pte Ltd
15                                            ICBC, Singapore Branch       Traditional Bank                                                                                                                                                                                                                                           energy and hard commo (perplexity)                                                                                                                                                                                            Global with Asia-Pacific focus                                                                                                                                                                                                                        Trafigura
16                      Agricultural Bank of China, Singapore Branch       Traditional Bank                                                                                                                                                                                                                                                 Metals and Oil  (perplexity)                                                                                                                                                                                                                   SG, SEA                                                                                                                                                                                    Trafigura Beheer BV / Trafigura Group pte Ltd
17         Shanghai Pudong Development Bank (SPDB), Singapore Branch       Traditional Bank                                                                                                                                                                                                                              General commodity trade financing  (perplexity)                                                                                                                                                                                                                   SG, SEA                                                                                                                                                                                                                          Unknown
18                                       MUFG Bank, Singapore Branch       Traditional Bank                                                                                                                                                                                                                                 Energy, Hard & Soft Commodities (perplexity)                                                                                                                                                                                        Global with emerging markets focus                                                                                                                                                                                                          Mercuria Energy Trading
19                                  Macquarie Bank, Singapore Branch       Traditional Bank                                                                                                                                                                                                                                                  energy, metals (perplexity)                                                                                                                                                                                                                      ASIA                                                                                                                                                                                                                          Unknown
20            Commonwealth Bank of Australia (CBA), Singapore Branch       Traditional Bank                                                                                                                                                                                                                                    carbon and trade commodities (perplexity)                                                                                                                                                                                                                      APAC                                                                                                                                                                                                                          Unknown
21                                        ANZ Bank, Singapore Branch       Traditional Bank                                                                                                            Energy (crude oil, fuel oil, LNG), Base & Precious Metals (copper, aluminum, zinc, gold), and Agribusiness (wheat, barley, cotton, sugar, soy, palm oil) (gemini)                                                                                                                                                                                                                    global                                                                                                                                                                                                                          Unknown

In [29]:
# reset index and save
p3 = p3.reset_index(drop=True)
p3
p3.to_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar3.csv", index=False)