In [1]:
import pandas as pd

# display columns without truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# display rows without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.expand_frame_repr", False)

In [2]:
p1 = pd.read_csv(r"D:\commo\code\Pillar 1 - Commodities Trading Data(Active_sheet).csv", encoding='utf-8', low_memory=False)

# drop columns
p1 = p1.drop(columns=['Known Insurance Broker', 'Singapore Presence', 'Trade Finance Relationships', 'Priority Score (1-5)', 'Done By', 'Contact Email', 'Contact Phone', 'Recent News / Expansion / Incidents', 'Key Executive (CEO/CFO/Treasurer/Risk) (SG)'])
p1 = p1.dropna(subset=["Company Name", "Commodity Focus"])
p1.fillna({"Legal Name / ACRA UEN": "Unknown", 
           "Estimated Revenue": "Unknown", 
           "Headcount (Global)": "Unknown",
           "Trade Volume (Est.)": "Unknown",
           'Listed / Exchange': "Unknown",
           'Key Executive (CEO/CFO/Treasurer/Risk) (SG)': "Unknown"}, inplace=True)
p1.rename(columns={'Notes / Next Action': 'Notes', 'Listed / Exchange': 'Exchange', 'HQ Location': 'HQ Country'}, inplace=True)
p1.fillna({}, inplace=True)
p1.head(5)

     Tier           Company Name       Commodity Type                                                                                                                                         Commodity Focus                                             Legal Name / ACRA UEN                                      HQ Country                                                                                 APAC Offices                                               Estimated Revenue Headcount (Global)                                                                                                    Trade Volume (Est.) Ownership Structure Exchange                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Notes
0  TIER 1              Trafigura                Multi                                                                  Multi-commodity (Oil & Petroleum Products, Natural Gas & LNG, Metals & Minerals, Agri)                TRAFIGURA GROUP PTE. LTD. / 201017488D (recordowl)                                       Singapore  10 Collyer Quay, #29-01/05, Ocean Financial Centre, Singapore 049315, Singapore (recordowl)            Trafigura Group: 240.3 USD bn FY2025 (trafigura.com)    5011 (linkedin)                                                          approx. 462 million metric tons (2025 annual report + claude)             Private                                                                                                                                                                                                                                                                                                                                                                               Latest acquisition (after Sep 2025): Greenergy that is owned by trafigura, acquired France's Armorine Group (trafigura 2025 annual report)
1  TIER 1                  Vitol  Energy - Hard Commo  Crude Oil, Petroleum Products, LNG, Natural gas, Biogas/BioLNG, thermal coal, metcoke, metals, power/electricity, plastics recycling (company website)                      VITOL ASIA PTE LTD. / 199001917Z (recordowl)  Switzerland (perplexity: world economic forum)                                \n128 BEACH ROAD #28-01 GUOCO MIDTOWN OFFICE SINGAPORE 189773               Turnover of $343 billion FY2025 (company website)    1990 (linkedin)                              total energy trade volume: 605 million tonnes of oil equivalent (mTOE ) (company website)             Private                                                                                                                                                                                                                                                                                                                                                                                                                              Its largest operations are in Geneva, Houston, London and Singapore. (world economic forum)
2  TIER 1               Mercuria                Multi                                                                                                                                    Energy, Metals, Agri  MERCURIA HOLDINGS (SINGAPORE) PTE. LTD. / 201808173Z (recordowl)                         Switzerland (recordowl)                 12 Marina View, #26-01, Asia Square Tower 2, Singapore 018961 (mercuria.com)                                      $618.7 Million (zoom.info)    1380 (linkedin)                                                          6M+ barrels of oil equivalent (BOE) per day (company website)             Private                                                                                                                                                                                                                             Mercuria Holdings (Singapore) Pte. Ltd. is a global commodity trader connecting essential resources to energy markets, operating globally and at scale. The company operates in over 50 countries across 5 continents and has a main trading hub located in Geneva, Switzerland. (recordowl)
3  TIER 1                 Gunvor  Energy - Hard Commo                                    Crude oil, refined petroleum products, natural gas and liquefied natural gas, biofuels, power, and carbon emissions.            GUNVOR SINGAPORE PTE. LTD. / 200606959K (acra bizfile)                       Switzerland (weforum.org)               128 Beach Road, #29-01, Guoco Midtown Office, Singapore 189773 (recordowl.com)                               US $144 billion (company website)    1035 (linkedin)                                                                                       253 million MT (company website)             Private                                                                                                                                                                                                                                                                                                                                                                       one of the world's largest independent commodities trading houses by turnover. It has trading offices in Geneva, Singapore, the Bahamas and Dubai.
4  TIER 1  Louis Dreyfus Company     Soft Commodities                                            Agri, Soft Commodities, Grains, Oilseeds, coffee, cotton, sugar, rice, juice, food & feed solutions, freight  LOUIS DREYFUS COMPANY ASIA PTE. LTD. / 199306551Z (acra bizfile)                           Netherlands (ldc.com)    12 MARINA BOULEVARD #33-03 MARINA BAY FINANCIAL CENTRE SINGAPORE 018982 (company website)  Net Sales: US$ 53.2bn FY2025 (2025.12 LDC - Integrated Report)  13,359 (linkedin)  ~100 million tonnes of products shipped annually, with volumes up 10.6% YoY in 2025 (2025.12 LDC - Integrated Report)    Private (Family)           LDC is purely agricultural, no energy commodity trading, heavily weighted towards grains & oilseeds, Profitability declined slightly in 2025 vs. 2024 (EBITDA -2.8%, Net Income -10%) despite higher revenues, due to tariff headwinds, geopolitical uncertainty, and higher finance costs, Aggressive capex cycle: capital expenditure nearly doubled to US$2.0 billion in 2025 (from US$1.0 billion in 2024), reflecting major processing and logistics expansion (2025.12 LDC - Integrated Report + claude)

In [3]:
# update existing tiers based on est. revenue
"""
Reference for the tiers:
https://sbr.com.sg/economy/in-focus/only-1-firms-exceed-100m-enterprises-cluster-below-1m-revenue

Reference for the 4 tiers which is then used to modify into 3 tiers:
- Above S$100 Mil — 4,300 firms (1%) → Tier 1
- Between S$10 Mil and S$100 Mil — 16,500 firms (5%) → Tier 2
- Between S$1 Mil and S$10 Mil — 61,100 firms (17%) → Tier 3
- Less than or equal to S$1 Mil — 276,500 firms (77%) → Tier 3

Current exchange rate (late July 2026): 1 SGD ≈ 0.775 USD

Tiers with USD equivalents:
- Tier 1: Above S$100 Mil (≈ above US$77.5 million)
- Tier 2: S$10 Mil – S$100 Mil (≈ US$7.75 million – US$77.5 million)
- Tier 3: Less than S$10 Mil (≈ less than US$7.75 million)
"""

'\nReference for the tiers:\nhttps://sbr.com.sg/economy/in-focus/only-1-firms-exceed-100m-enterprises-cluster-below-1m-revenue\n\nReference for the 4 tiers which is then used to modify into 3 tiers:\n- Above S$100 Mil — 4,300 firms (1%) → Tier 1\n- Between S$10 Mil and S$100 Mil — 16,500 firms (5%) → Tier 2\n- Between S$1 Mil and S$10 Mil — 61,100 firms (17%) → Tier 3\n- Less than or equal to S$1 Mil — 276,500 firms (77%) → Tier 3\n\nCurrent exchange rate (late July 2026): 1 SGD ≈ 0.775 USD\n\nTiers with USD equivalents:\n- Tier 1: Above S$100 Mil (≈ above US$77.5 million)\n- Tier 2: S$10 Mil – S$100 Mil (≈ US$7.75 million – US$77.5 million)\n- Tier 3: Less than S$10 Mil (≈ less than US$7.75 million)\n'

In [4]:

# Tier 1: Above S$100 Mil (≈ above US$77.5 million)
# Tier 2: S$10 Mil – S$100 Mil (≈ US$7.75 million – US$77.5 million)
# Tier 3: Less than S$10 Mil (≈ less than US$7.75 million)

# tier 1: 19, 20, 21, 22, 23, 27, 28,29, 31, 32, 33, 41, 43, 44, 45,
#          48, 50, 53, 54, 58, 60, 63, 64, 65, 66, 67, 70, 71, 72, 74, 78, 79, 80, 81, 82, 83
#            ,84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105,
# tier 2: 46, 56, 106
# tier 3: 25, 40, 42, 68, 69, 73, 89


tier1 = [19, 20, 21, 22, 23, 27, 28,29, 31, 32, 33, 41, 43, 44, 45,
         48, 50, 53, 54, 58, 60, 63, 64, 65, 66, 67, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83
        ,84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105]
tier1_companies = p1.loc[tier1, "Company Name"].tolist()

tier2 = [46, 56, 57, 61, 62, 106]
tier2_companies = p1.loc[tier2, "Company Name"].tolist()

tier3 = [25, 40, 42, 68, 69, 73, 89]
tier3_companies = p1.loc[tier3, "Company Name"].tolist()

for index, row in p1.iterrows():
    if row["Company Name"] in tier1_companies:
        p1.at[index, "Tier"] = 'TIER 1'
    elif row["Company Name"] in tier2_companies:
        p1.at[index, "Tier"] = 'TIER 2'
    elif row["Company Name"] in tier3_companies:
        p1.at[index, "Tier"] = 'TIER 3'
        
#check the changes        
p1.loc[tier3]

      Tier                   Company Name                                              Commodity Type                                                                                                                               Commodity Focus                                                                       Legal Name / ACRA UEN                      HQ Country                                                                         APAC Offices                     Estimated Revenue    Headcount (Global)                                                    Trade Volume (Est.) Ownership Structure Exchange                                                                                                                                                                                                                                                                          Notes
25  TIER 3                  Straits Grain                                            Soft Commodities                                                                                                                                  Grains, Feed                                THE STRAITS INTERNATIONAL PTE. LTD. / 201025898Z (recordowl)  Singapore (straitsintl.com.sg)   4008 Ang Mo Kio Avenue 1, Techplace 1 #02-15 Singapore 569625 (straitsintl.com.sg)  $2M – $5M USD  (2024-26) (google AI)     8 (2024) (tracxn)                                                                Unknown             Private                                                                                                                            originate and buy physical agri-commodities, focus industries are animal and aqua feeds, flour milling, food manufacturing, and oils and fats manufacturing.
40  TIER 3                    Straits Oil                                         Energy - Hard Commo                                                                                                                            Petroleum Products                                        STRAITS BUNKERING PTE. LTD. / 201415157M (recordowl)          Singapore (perplexity)  9 RAFFLES PLACE, #17-20, REPUBLIC PLAZA II, SINGAPORE 048619 (straitsbunkering.com)                <$5 Million (zoominfo)         46 (linkedin)               approx. 6,700-10,000 metric tonnes annually (perplexity)             Private           straits oil pte ltd is struck off (recordowl). Straits Bunkering Pte Ltd trades petroleum products. Straits bunkering pte ltd is a leading provider of bunkering services in Singapore and Malaysian waters, specialized in the supply of Marine Fuel Oil and Marine Gas Oil.
42  TIER 3                    Petraco Oil                                         Energy - Hard Commo                                                                                                                 Crude Oil, Petroleum Products                                       PETRACO OIL COMPANY PTE LTD. / 201321047N (recordowl)   Switzerland (petraco-oil.com)      8 Temasek Boulevard, #15-05A Suntec Tower 3, Singapore 038988 (petraco-oil.com)              $5 million (rocketreach)         38 (linkedin)  approx. 182.5 million barrels per year (perplexity + petraco-oil.com)             Private
68  TIER 3          Bary Chemical Pte Ltd                                                       Multi                                                                                Coal, Fertlizers, Bauxite, Iron Products, Nickel Ore (bary.sg)                                            BARY CHEMICAL PTE. LTD. / 200700627M (recordowl)             Singapore (bary.sg)                             114 LAVENDER STREET,SINGAPORE 338729,SINGAPORE (bary.sg)          < $5 million USD (google ai)  11 to 50 (google ai)                                         annual ave. > 10 Mmt (bary.sg)             Private  Unknown                                                                                                                                                                                                    Bary Chemical has established a subsidiary Bary Commodity. https://bary.sg/
69  TIER 3  Mahkota Oils & Fats Pte. Ltd.                                            Soft Commodities                                                Palm Oil Products (Crude Palm Oil, RBD Palm Olein, and Palm Fatty Acid Distillate) (google ai)                                      MAHKOTA OILS & FATS PTE. LTD. / 202320748R (recordowl)           Indonesia (google ai)       491B RIVER VALLEY ROAD,, #11-03 VALLEY POINT, SINGAPORE, 248373, SG (linkedin)                ~$342,220 (prospeo.io)  1 to 10 (prospeo.io)                                                                Unknown             Private  Unknown                                                                                                                                 The parent company of Mahkota Oils & Fats Pte. Ltd. is the Indonesian palm oil processing company PT Mahkota Group Tbk (IDX: MGRO) (google ai)
73  TIER 3    Oriental Energy & Resources                                                       Multi                           Mineral Resources (Copper, Nickel, Aluminum, etc.), CPO (Crude Palm Oil) and Refined Palm Oil (oriental-energy.com)  ORIENTAL ENERGY PTE LTD / 200808445C & ORIENTAL RESOURCES PTE LTD / 202100630W (recordowl)            Singapore (linkedin)           7500A Beach Road #08-312 The Plaza, Singapore 199591 (oriental-energy.com)                      ~$3.5M (prospeo)         28 (linkedin)                                                                Unknown             Private  Unknown                                                                                                                                                                                                                                                        www.oriental-energy.com
89  TIER 3     Bary Commodities Pte. Ltd.  Energy and Petrochemicals Commodities (gemini) & (bary.sg)  Coal (Energy),Ores & Minerals (Industrial Mining): Nickel Ore, Brucite, Bauxite, Iron Products,Fertilizers (Agricultural Chemicals) (gemini)                                     Bary Chemical Pte Ltd/ 201807001W (recordowl) (bary.sg)  Republic of Singapore (Gemini)                             114 LAVENDER STREET,SINGAPORE 338729,SINGAPORE (bary.sg)     under $5 million USD  (google ai)     10 to 50 (Gemini)                       average of over 10 Million metric tons (bary.sg)             private  Unknown                                                                                                                                Bary doesn't has their personal profile : linkedin, facebook,..(Google AI), for legal name in recordowl and their website have difference name.

In [5]:
#can only be run after fixing the tiers
p1 = p1[p1["Company Name"] != "New companies"]

In [6]:
p1.shape

(104, 13)

In [7]:
p1.info()

<class 'pandas.DataFrame'>
Index: 104 entries, 0 to 106
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tier                   104 non-null    str
 1   Company Name           104 non-null    str
 2   Commodity Type         104 non-null    str
 3   Commodity Focus        104 non-null    str
 4   Legal Name / ACRA UEN  104 non-null    str
 5   HQ Country             104 non-null    str
 6   APAC Offices           104 non-null    str
 7   Estimated Revenue      104 non-null    str
 8   Headcount (Global)     104 non-null    str
 9   Trade Volume (Est.)    104 non-null    str
 10  Ownership Structure    104 non-null    str
 11  Exchange               104 non-null    str
 12  Notes                  104 non-null    str
dtypes: str(13)
memory usage: 11.4 KB

In [8]:
p1.isnull().sum() # 0 null values

Tier                     0
Company Name             0
Commodity Type           0
Commodity Focus          0
Legal Name / ACRA UEN    0
HQ Country               0
APAC Offices             0
Estimated Revenue        0
Headcount (Global)       0
Trade Volume (Est.)      0
Ownership Structure      0
Exchange                 0
Notes                    0
dtype: int64

In [9]:
# change all tier from str to int
tier_mapping = {'TIER 1': 1, 'TIER 2': 2, 'TIER 3': 3}
if p1['Tier'].dtype == 'object' or p1['Tier'].dtype == 'str':
    p1['Tier'] = p1['Tier'].str.strip()
    p1['Tier'] = p1['Tier'].map(tier_mapping)
p1['Tier'].dtype
p1["Tier"].unique()  # 1,2,3

array([1, 2, 3])

In [10]:
# CHECK 'Company Name'
unique_names = p1['Company Name'].unique().tolist()
len(unique_names) #104
len(p1["Company Name"].tolist())  # 104

#'Trafigura' parent of 'Trafigura Carbon Trading'
#'Bary Chemical Pte Ltd' parent of 'Bary Commodities Pte. Ltd.'

# update company names to match the names in the other datasets
p1.loc[p1["Company Name"] == "Olam International", 'Company Name'] = 'Olam Group'
p1.loc[p1["Company Name"] == "HD HYUNDAI MARINE SOLUTION SINGAPORE PTE LTD HD", "Company Name"] = "HD HYUNDAI MARINE SOLUTION SINGAPORE PTE LTD"
p1.loc[p1["Company Name"] == "olam agri (spun off)", "Company Name"] = "olam agri"
p1.loc[p1["Company Name"] == "noble group (restructured)", "Company Name"] = "noble group"
p1.loc[p1["Company Name"] == "century commodities solution pte ltd (formerly china coal solution singapore)", "Company Name"] = "century commodities solution pte ltd"

p1['Company Name'] = p1['Company Name'].str.replace('.', '', regex=False).str.strip()
# p1["Company Name"].tolist()
len(unique_names)

104

In [11]:
# check 'Commodity Type'
# create a copy
if "Commodity Type copy" not in p1.columns:
    p1["Commodity Type copy"] = p1["Commodity Type"].copy()

In [12]:
# check 'Commodity Type'
# remove brackets and their contents
p1["Commodity Type copy"] = p1["Commodity Type copy"].str.replace(r"\(.*?\)", "", regex=True)
# remove whitespace and convert to lowercase
p1["Commodity Type copy"] = p1["Commodity Type copy"].str.lower().str.strip()

# update the unique values
commodity_mapping = {
    "energy and petrochemicals commodities  &": "energy and petrochemicals",
    "energy and petrochemicals commodities": "energy and petrochemicals",
    "energy and petrochemical commodities": "energy and petrochemicals",
    "energy - hard commo": "energy or hard/metals",
    "soft commodities": "soft/agricultural",
    "hard commo": "hard/metals",
    "energy commo": "energy",
    "energy and soft commodities": "energy and soft/agricultural",
    "multi": "multi (>2 types)",
}

p1["Commodity Type copy"] = p1["Commodity Type copy"].replace(commodity_mapping)

unique_commo_types = p1["Commodity Type copy"].unique().tolist()
unique_commo_types

# energy or hard/metals become ['energy', 'hard/metals']
# energy and petrochemicals become ['energy', 'petrochemicals']
# energy and soft/agricultural become ['energy', 'soft/agricultural']
import re
def split_commodity_types(commodity_type_str):
    if pd.isna(commodity_type_str):
        return [] 
    elif commodity_type_str in ['multi (>2 types)', 'petrochemicals', 'soft/agricultural', 'emerging', 'hard/metals', 'energy']:
        return [commodity_type_str]
    else:
        parts = re.split(r'\s+and\s+|\s+or\s+', commodity_type_str)
        return [p.strip() for p in parts]

p1['Commodity Type'] = p1['Commodity Type copy'].apply(split_commodity_types) #can run only once, comment out after running

# get the unique values of the updated column where each row is a list of str, update() use with set() to append only unique values
unique_values2 = set()
for list in p1['Commodity Type']:
    unique_values2.update(list)
print(unique_values2)

{'hard/metals', 'soft/agricultural', 'energy', 'multi (>2 types)', 'petrochemicals', 'emerging'}

In [13]:
# drop the copy column
p1 = p1.drop(columns={"Commodity Type copy"})

In [14]:
#strip whitespace from commodity focus
p1['Commodity Focus'] = p1['Commodity Focus'].str.strip()
p1['Commodity Focus'].tail()

102    alumina, electrolytic aluminum, coking coal, thermal coal, copper, lead, zinc, rare and precious metals, bauxite, copper concentrate, iron ore (https://www.chalco.com.cn/en/sctxen/cpjyen/)
103                                                                                                   manganese ore, manganese alloys, Ferrosilicon, Silicon Metal (OMH 2024 annual report +claude)
104                                                                                                                    thermal coal, petroleum products, fuels, transition energy products (google)
105                                                                                                                      crude oil, feedstocks, refined petroleum products, petrochemicals (google)
106                                                     Stainless steel plates, stainless steel coils, stainless steel sheets, hot-rolled steel, cold-rolled steel, metals, and metal ores (gemini)
Name: Commodity Focus, dtype: str

In [15]:
# update the commodity type based on the commodity focus
focus_type = p1[['Commodity Focus','Commodity Type']]
focus_type #for checking only
# {'energy', 'emerging', 'multi (>2 types)', 'petrochemicals', 'soft/agricultural', 'hard/metals'}

# use .loc because indices are not in order
# energy: [3, 15, 16, 17, 38, 40, 41, 42, 43, 48, 49, 50, 51, 52, 53, 54]
p1.loc[[3, 15, 16, 17, 38, 40, 41, 42, 43, 48, 49, 50, 51, 52, 53, 54],'Commodity Type'] = p1.iloc[[3, 15, 16, 17, 38, 40, 41, 42, 43, 48, 49, 50, 51, 52, 53, 54]]['Commodity Type'].apply(lambda lst: [type for type in lst if type != 'hard/metals'])

# multi: [1, 8, 9, 39, 76, 89]
p1.loc[[1, 8, 9, 39, 76, 89], 'Commodity Type'] = p1.loc[[1, 8, 9, 39, 76, 89], 'Commodity Type'].apply(lambda list: 'multi (>2 types)')

# energy & petrochemical: [14, 72, 75]
p1.loc[[14, 72, 75], "Commodity Type"] = p1.loc[[14, 72, 75], "Commodity Type"].apply(lambda lst: ["energy", "petrochemicals"])

# engery & soft: [18, 57, 92]
p1.loc[[18, 57, 92], "Commodity Type"] = p1.loc[[18, 57, 92], "Commodity Type"].apply(lambda lst: ['energy','soft/agricultural'])

# hard: [31, 32, 33, 34, 56, 60]
p1.loc[[31, 32, 33, 34, 56, 60], 'Commodity Type'] = p1.loc[[31, 32, 33, 34, 56, 60], 'Commodity Type'].apply(lambda lst: [item for item in lst if item != 'energy'])

# hard & soft: [36, 63, 64, 73]
p1.loc[[36, 63, 64, 73], "Commodity Type"] = p1.loc[[36, 63, 64, 73], "Commodity Type"].apply(lambda lst: ["hard/metals", 'soft/agricultural'])

# hard & petrochemicals: 82
p1.loc[[82], "Commodity Type"] = p1.loc[[82], "Commodity Type"].apply(lambda lst: ["hard/metals", "petrochemicals"])

# petrochemicals & soft: 45
p1.loc[[45], "Commodity Type"] = p1.loc[[45], "Commodity Type"].apply(lambda lst: ["petrochemicals", 'soft/agricultural'])

# energy & hard: [68, 74, 90]
p1.loc[[68, 74, 90], "Commodity Type"] = p1.loc[[68, 74, 90], "Commodity Type"].apply(lambda lst: ['energy', "hard/metals"])

# check
#p1.loc[[68, 74, 90], "Commodity Type"]

In [16]:
# clean up 'Legal Name / ACRA UEN
# strip whitespace
p1["Legal Name / ACRA UEN"] = p1["Legal Name / ACRA UEN"].str.strip()
p1["Legal Name / ACRA UEN"].head()

0                  TRAFIGURA GROUP PTE. LTD. / 201017488D (recordowl)
1                        VITOL ASIA PTE LTD. / 199001917Z (recordowl)
2    MERCURIA HOLDINGS (SINGAPORE) PTE. LTD. / 201808173Z (recordowl)
3              GUNVOR SINGAPORE PTE. LTD. / 200606959K (acra bizfile)
4    LOUIS DREYFUS COMPANY ASIA PTE. LTD. / 199306551Z (acra bizfile)
Name: Legal Name / ACRA UEN, dtype: str

In [17]:
# strip whitespace from HQ Country, remove brackets and lowercase
p1["HQ Country"].unique()
p1["HQ Country"] = p1["HQ Country"].str.replace(r"\(.*?\)", "", regex=True).str.strip()
HQ_mapping = {
    "Geneva, Switzerland": "Switzerland",
    "Bombay House in Mumbai, India.": "India",
    "Tokyo,Osaka": "Japan",
    "Seoul, South Korea.": "South Korea",
    "Singapore , parent in Japan": "Singapore, Japan",
    "London, England": "UK",
    "Tokyo, Japan": "Japan",
    "Petaling Jaya, Selangor": "Malaysia",
    "United Kingdom": "UK",
    "Singapore, global hq: Hong Kong": "Singapore, Hong Kong",
    "Hong Kong , Singapore": "Singapore, Hong Kong",
    "United States": "USA",
    "London, UK": "UK",
    "Mumbai, India.": "India",
    "Seoul, South Korea": "South Korea",
    "Beijing, China.": "China",
    "Republic of Singapore": "Singapore",
    "Jakarta, Indonesia": "Indonesia",
    "Nagoya, Japan": "Japan",
    "Singapore; UK": "Singapore, UK",
    "Singapore; India": "Singapore, India",
    "Singapore , Switzerland": "Singapore, Switzerland",
    "Korea": "South Korea",
    "Dubai, UAE": "UAE",  
    "Dubai": "UAE",
}

p1["HQ Country"] = p1["HQ Country"].replace(HQ_mapping)
p1["HQ Country"].unique()
p1["HQ Country"][:10]

0      Singapore
1    Switzerland
2    Switzerland
3    Switzerland
4    Netherlands
5      Singapore
6      Singapore
7          China
8            USA
9    Switzerland
Name: HQ Country, dtype: str

In [18]:
# check apac offices
#trim whitespace
p1["APAC Offices"] = p1["APAC Offices"].str.strip()
p1['APAC Offices']

0                                                                                                                                10 Collyer Quay, #29-01/05, Ocean Financial Centre, Singapore 049315, Singapore (recordowl)
1                                                                                                                                                                128 BEACH ROAD #28-01 GUOCO MIDTOWN OFFICE SINGAPORE 189773
2                                                                                                                                               12 Marina View, #26-01, Asia Square Tower 2, Singapore 018961 (mercuria.com)
3                                                                                                                                             128 Beach Road, #29-01, Guoco Midtown Office, Singapore 189773 (recordowl.com)
4                                                                                                                                  12 MARINA BOULEVARD #33-03 MARINA BAY FINANCIAL CENTRE SINGAPORE 018982 (company website)
5                                                                                                                                                              28 Biopolis Road, Singapore 138568 (wilmar-international.com)
6                                                                                                                                            7 Straits View, #20-01, Marina One East Tower, Singapore 018936 (olamgroup.com)
7                                                                                                                                        150 Beach Rd, #23-01/08 The Gateway West\nSingapore 189720 (cofcointernational.com)
8                                                                                                                                                     138 Market Street, #17-01, CapitaGreen, Singapore 048946 (cargill.com)
9                                                                                                                                                        1 TEMASEK AVENUE #34-01 MILLENIA TOWER SINGAPORE 039192 (recordowl)
10                                                                                                                                             230 VICTORIA STREET #11-08 BUGIS JUNCTION TOWERS SINGAPORE 188024 (recordowl0
11                                                                                                                                                          1 WALLICH STREET #08-01 GUOCO TOWER SINGAPORE 078881 (recordowl)
12                                                                                                                                                   138 Market Street, #31-01, CapitaGreen, Singapore 048946 (marubeni.com)
13                                                                                                                                                12 Marina View, #31-01, Asia Square Tower 2, Singapore 018961 (mitsui.com)
14                                                                                                                                   391A Orchard Road #12-01/04 Ngee Ann City Tower A, Singapore (238873) (ptt-trading.com)
15                                                                              Shell Singapore Pte. Ltd., Shell Card Team, 9 North Buona Vista Drive, The Metropolis Tower 1, #06-01 Mailroom, Singapore 138588 (shell.com)
16                                                                                                                                                  7 Straits View, #26-01, Marina One East Tower, Singapore 018936 (bp.com)
17                                                                                                                                                      25 NORTH BRIDGE ROAD 07 25 NORTH BRIDGE SINGAPORE 179104 (recordowl)
18                                                                                                                                                  9 TEMASEK BOULEVARD #18-03 SUNTEC TOWER TWO SINGAPORE 038989 (recordowl)
19                                                                                                                                              10 Anson Road #32-03 International Plaza, Singapore 079903 (agrocorp.com.sg)
20                                                                                                                                   108 Pasir Panjang Road, #06-00, Golden Agri Plaza, Singapore 118535 (goldenagri.com.sg)
21                                                                                                                                                     150 Beach Road, #24-01, Gateway West, Singapore 189720 (musimmas.com)
22                                                                                                                                   8 Temasek Boulevard, #41-02, Suntec Tower Three, Singapore 038988 (first-resources.com)
23                                                                                                                         6 SHENTON WAY #33-00 OUE DOWNTOWN SINGAPORE (068809) , 068809 , Singapore (sg.globaldatabase.com)
24                                                                                                                                                                      3 Temasek Avenue, Singapore, 0391901 (gceglobal.com)
25                                                                                                                                        4008 Ang Mo Kio Avenue 1, Techplace 1 #02-15 Singapore 569625 (straitsintl.com.sg)
26                                                                                                                                                                     44 WOODLANDS TERRACE SINGAPORE 738458 (unisoy.com.sg)
27                                                                                                                                           7 Straits View, Marina One East Tower, #20-01, Singapore, 018936, SG (linkedin)
28                                                                                                                                                        28 BIOPOLIS ROAD WILMAR INTERNATIONAL SINGAPORE 138568 (recordowl)
29     legal address: 36 Robinson Road #13-01 City House Singapore, 068877 SINGAPORE; hq address: Unit 22-26, Level 22, Ocean Financial Centre 10 Collyer Quay Raffles Place Singapore, 049315 SINGAPORE (lei.bloomberg.com)
30                                                                                                                                    Noble Resources 128 Beach Rd, #28-01 Guoco Midtown, Singapore 189773 (thisisnoble.com)
31                                                                                                                                                            80 RAFFLES PLACE #32-01 UOB PLAZA SINGAPORE 048624 (recordowl)
32                                                                                                                                                                    73 Tras Street #04-01, SINGAPORE , 079012 (traxys.com)
33                                                                                                                                                                      68 CIRCULAR ROAD #02-01 SINGAPORE 049422 (recordowl)
34                                                                                                                         MRI Group Pte. Ltd, 37-06/07, OCBC Tower East, 65 Chulia Street, Singapore 049513 (mri-group.com)
35                                                                                                                                            Level 19, Singapore Land Tower, 50 Raffles Place, Singapore 048623 (ssgil.com)
36                                                                                                                                            #08-01, Straits Trading Building 11 Battery Road Singapore 049910 (perplexity)
37                                                                                                                                             101, Cecil Street, # 23 - 05, Tong Eng Building (pacificmineral.lookchem.com)
38                                                                                                                            Head office: 9 Raffles Place, Republic Plaza #53-02, Singapore 048619 (concordenergygroup.com)
39                                                                                                       Ginga Petroleum (Singapore) Pte Ltd, 3 Temasek Avenue, #04-01, Centennial Building, Singapore 039190 (ginga.com.sg)
40                                                                                                                                       9 RAFFLES PLACE, #17-20, REPUBLIC PLAZA II, SINGAPORE 048619 (straitsbunkering.com)
41                                                                                                                                                      1 Temasek Avenue, 23-01 Millenia Tower, Singapore (sahara-group.com)
42                                                                                                                                           8 Temasek Boulevard, #15-05A Suntec Tower 3, Singapore 038988 (petraco-oil.com)
43                                                                                                                                                 1 Temasek Ave, #36-05 Millenia Tower, Singapore 039192 (socartrading.com)
44                                                                                                                                                        152 BEACH ROAD #13-02/03 GATEWAY EAST SINGAPORE 189721 (recordowl)
45                                                                                                                                                       #36-06 The Concourse, 300 Beach Road, Singapore 199555 (helmag.com)
46                                                                                                                                                                             21 TUAS AVENUE 8 SINGAPORE 639236 (recordowl)
47                                                                                                                                              60 Paya Lebar Road, 11-40, Paya Lebar Square, Singapore 409051 (swanipl.com)
48                                                                                                                                      8, Boon Lay Way, #07-16 Trade Hub 21, 609964 Singapore (straits-energyresources.com)
49                                                                                                                                         # 29-04 Millenia Tower, One Temasek Avenue, Singapore 039192 (quantum-global.com)
50                                                                                                                                                                   16 KALLANG PLACE #05-10/18 SINGAPORE 339156 (recordowl)
51                                                                       470 NORTH BRIDGE ROAD #05-12 BUGIS CUBE SINGAPORE 188735 (recordowl), 80 Raffles Place, #50-01 UOB Plaza 1 Singapore 048624 (pacificenergycorp.com)
52                                                                                      Meridian Energy Pte. Ltd., 250 North Bridge Rd., #15-02/04 Raffles City Tower, Singapore 179101 (https://www.meridianenergy.com.sg/)
53                                                                                                                                             5 Temasek Boulevard #04-01A Suntec Tower Five Singapore (038985) (oilmar.com)
54                                                                                                                                           14 ROBINSON ROAD #08-01A FAR EAST FINANCE BUILDING SINGAPORE 048545 (recordowl)
56                                                                                                                                                   3, Temasek Ave, #33-03 Centennial Tower, Singapore 039190 (triland.com)
57                                                                                                                                                  80 Raffles Place, #50-01 UOB Plaza 1, Singapore 048624 (apicalgroup.com)
58                                                                                                                                      10 Collyer Quay, #29-01/05, Ocean Financial Centre, Singapore 049315 (trafigura.com)
60                                                                                                                                           IXM Pte. Ltd., 3 Church Street, #24-03 Samsung Hub, Singapore 049483, Singapore
61                                                                                                                                 3 Temasek Avenue #32-01 Centennial Tower, Singapore 039190 (global.mitsubishicorprtm.com)
62                                                                                                                                            6 Battery Road, #39-01, Six Battery Road, Singapore (049909) (kztrading.co.kr)
63                                                                                                                   6 Shenton Way #18-08C, OUE Downtown2, Singapore 068809  (https://www.tatainternational.com/contact-us/)
64                                                                                                                                                        65 Chulia Street, #48-05, OCBC Center, Singapore 049513, ( gemini)
65                                                                                                                                                 9 TEMASEK BOULEVARD #10-02B SUNTEC TOWER TWO SINGAPORE 038989 (recordowl)
66                                                                                                                                                     10 BUKIT BATOK CRESCENT #10-01 THE SPIRE SINGAPORE 658079 (recordowl)
67                                                                                                                                                            6 SHENTON WAY #21-12 OUE DOWNTOWN SINGAPORE 068809 (recordowl)
68                                                                                                                                                                  114 LAVENDER STREET,SINGAPORE 338729,SINGAPORE (bary.sg)
69                                                                                                                                            491B RIVER VALLEY ROAD,, #11-03 VALLEY POINT, SINGAPORE, 248373, SG (linkedin)
70                                                                                                                                          6 Shenton Way #22-08 OUE Downtown 2 Singapore 068809 (https://www.itochu.co.jp/)
71                                                                                                                                        8 Temasek Boulevard, #26-01A, Suntec City Tower 3, Singapore 038988 (gsgcorp.com),
72                                                                                                                                                    9 Straits View, #12-07/12, Singapore, Singapore 018937, SG (Linkedin),
73                                                                                                                                                7500A Beach Road #08-312 The Plaza, Singapore 199591 (oriental-energy.com)
74                                                                                                                                                           1 TEMASEK AVENUE 27 MILLENIA TOWER SINGAPORE 039192 (recordowl)
75                                                                                                                                     7 Temasek Boulevard, #23-01/02/03, Suntec Tower One, Singapore, 038987, SG (linkedin)
76                                                                                                                                    9 Raffles Place, #41-01 Republic Plaza, Singapore 048619 (https://intl.sinopec.com/sg)
78                                                                                                                                                             1 Temasek Avenue, #29-02 Millenia Tower, Singapore (emis.com)
79                                                                                                                                                            79 ROBINSON ROAD #16-03 CAPITASKY SINGAPORE 068897 (recordowl)
80                                                                                                                                               182 Cecil Street, #22-01 Frasers Tower, Singapore 069547 (sumitomocorp.com)
81                                                                                                                                                    1 Wallich Street # 24-01/02 Guoco Tower, Singapore 078881 (sojitz.com)
82                                                                                                                                      3 Church Street, #21-02, Samsung Hub Bldg. Singapore 049483 (trading.samsungcnt.com)
83                                                                                                                                                8 TEMASEK BOULEVARD #26-02 SUNTEC TOWER THREE SINGAPORE 038988 (recordowl)
84                                                                                                                                            9 Temasek Boulevard #17-02 Suntec Tower Two, 038989, Singapore (korchamdb.com)
85                                                                                                                                                    12 MARINA VIEW #18-03 ASIA SQUARE TOWER 2 SINGAPORE 018961 (recordowl)
86                                                                                                                                                  7 TEMASEK BOULEVARD #29-02 SUNTEC TOWER ONE SINGAPORE 038987 (recordowl)
87                                                                                                                                           8 Eu Tong Sen Street, #16-96/97 The Central Singapore 059818 (indofoodagri.com)
88                                                                                                               The Metropolis Tower 1, 9 North Buona Vista Drive, #06-01 Singapore 138588   (shell.com.sg/contact-us.html)
89                                                                                                                                                                  114 LAVENDER STREET,SINGAPORE 338729,SINGAPORE (bary.sg)
90                                                                                               182 Cecil Street, #22-01, Frasers Tower, Singapore 069547  Singapore; Singapore; Postal Code: 069547 (recordowl, emis.com )
91                                                                                                                                              1 Raffles Place Tower1 #56-00 Singapore 048616 (https://pimd.pertamina.com/)
92                                                                                                                                                1 HARBOURFRONT AVENUE #14-07 KEPPEL BAY TOWER SINGAPORE 098632 (recordowl)

In [19]:
# check Estimated Revenue
# strip whitespace & lowercase
p1["Estimated Revenue"] = p1["Estimated Revenue"].str.strip()

#cannot use revenue to size the nodes because the revenue are inaccurate: inconsistent years, inaccurate number, some are ranges, 
# some are turnover / net sales / total sales / net brokerage
#some number is at group level or consolidated, some is quarterly figure or half of the year figure
#leave it as it is with no more standardizaton

In [20]:
# check headcount(estimated numbers with inconsistent year, some belong to group, some belong to SG branch, some are ranges)
# remove the word 'employees'
p1["Headcount (Global)"] = p1["Headcount (Global)"].str.replace(r"employees?", "", case=False, regex=True)
# remove whitespace
p1["Headcount (Global)"] = p1["Headcount (Global)"].str.strip()
p1["Headcount (Global)"]

0                                                                       5011 (linkedin)
1                                                                       1990 (linkedin)
2                                                                       1380 (linkedin)
3                                                                       1035 (linkedin)
4                                                                     13,359 (linkedin)
5                                                                      7,723 (linkedin)
6                                                                       8766 (linkedin)
7                                  ~11,000  (cofcointernational.com 2024 annual review)
8                                                ~160,000  (Cargill 2024 annual report)
9                                                ~81,000  (Glencore 2024 annual report)
10                                                    ~41,000  (ADM 2024 annual report)
11                                                  ~23,000  (Bunge 2024 annual report)
12                                           ~45,000  (Marubeni 2024 integrated report)
13                                       ~46,000  (Mitsui & Co. 2024 integrated report)
14                                                    ~41,000  (PTT 2024 annual report)
15                                                  ~93,000  (Shell 2024 annual report)
16                                                     ~67,000  (BP 2024 annual report)
17                       ~105,000  (TotalEnergies 2024 universal registration document)
18                                     ~220,000  (Sinochem Holdings 2024 annual report)
19                                                        ~500  (LinkedIn company page)
20                                                    ~23,000  (GAR 2024 annual report)
21                                                           ~37,000  (company website)
22                                ~22,000  (First Resources 2025 sustainability report)
23                                                      2 – 13  (2024–2026) (google AI)
24                                                                   80 (gceglobal.com)
25                                                                    8 (2024) (tracxn)
26                                                                        13 (linkedin)
27                              10,000+ (olamagri-corporate-factsheet-2025-english.pdf)
28                                                                       793 (linkedin)
29                                                                       723 (linkedin)
30                                                                      1076 (linkedin)
31                                                                       247 (linkedin)
32                                                                       393 (linkedin)
33                                                                        45 (linkedin)
34                                                                        83 (linkedin)
35                                                                    307 (rocketreach)
36                                     32 (linkedin: trimex industries private limited)
37                                                                              Unknown
38                                                                        24 (linkedin)
39                                                                     177 (perplexity)
40                                                                        46 (linkedin)
41                                                                      1821 (linkedin)
42                                                                        38 (linkedin)
43                                                                       571 (linkedin)
44                                                                      1044 (linkedin)
45                                                                       693 (linkedin)
46                                                                    < 50 (perplexity)
47                                                                         6 (linkedin)
48                                                                         2 (linkedin)
49                                                                        73 (linkedin)
50                                         363 (2025 annual report sinogasholdings.com)
51                                                        184 (pacific energy linkedin)
52                                                                        4 (recordowl)
53                                                                        61 (linkedin)
54                                                                        79 (linkedin)
56                                                                        92 (linkedin)
57                                                              >3000 (apicalgroup.com)
58                                             14476 (2025_trafigura_annual_report_pdf)
60                                                                       370 (linkedin)
61                                                                       105 (linkedin)
62                                                                        59 (linkedin)
63       Tata group: 1,010,425 (Linkedin), Tata International Limited: 1,916 (Linkedin)
64                                                                 400+(abgtrading.com)
65                                                                       623 (linkedin)
66                                                                         1 (linkedin)
67                                                                              Unknown
68                                                                 11 to 50 (google ai)
69                                                                 1 to 10 (prospeo.io)
70                                                                       125 (Linkedin)
71                                                                       139 (linkedin)
72                                                                 2,605 (skenergy.com)
73                                                                        28 (linkedin)
74                                                                       163 (linkedin)
75                                                                        66 (linkedin)
76                                                     13,535  (Group global linkedin )
78                                                     13,535  (Group global linkedin )
79                                                                    sg: 16 (linkedin)
80                                                       Sumitomo Corp: 6211 (linkedin)
81                                                         26,789 (global) (sojitz.com)
82                                                         9261 FY2025 (samsungcnt.com)
83                                                   FY2025: 9770 (lxinternational.com)
84                                                                      1061 (linkedin)
85                                                                      5903 (linkedin)
86                                                                      1538 (linkedin)
87                                           32.64k (markets.ft.com) , 18620 (linkedin)
88                                      85,000 (shell.com/who-we-are/shell-at-a-glance)
89                                                                    10 to 50 (Gemini)
90                                             Sumitomo Corp (parent): 82,488  (google)
91                                                                        42 (LinkedIn)
92                                                                       645 (linkedIn)
93                                                                        33 (linkedin)
94                                                                        95 (linkedin)
95                                                                        < 50 (gemini)
96                                                                      1156 (linkedin)
97                                                                         2 (LinkedIn)
98                                                            6,487 (COSMO REPORT 2025)
99                                              8744 (https://en.jfe-shoji.co.jp/data/)
100                                              ~464 (CCS 2023 Annual report + gemini)
101                                                   100+ (https://radiant-world.com/)
102    Aluminum Corporation of China Limited:  63,133  as of December 31, 2024 (google)
103                                                        2,228   (2025 annual report)
104                                                                     2084 (linkedin)
105                                                                    > 35000 (global)
106                                                         317 (https://www.emis.com/)
Name: Headcount (Global), dtype: str

In [21]:
# check trade volume (inaccurate), estimated numbers, inconsistent year, some are total trade volume some are just across a few commodity types, most cases are undisclosed
# some are ranges
# remove whitespace
p1["Trade Volume (Est.)"] = p1["Trade Volume (Est.)"].str.strip()
p1["Trade Volume (Est.)"]

0                                                                                                                                                                                                                                                approx. 462 million metric tons (2025 annual report + claude)
1                                                                                                                                                                                                                    total energy trade volume: 605 million tonnes of oil equivalent (mTOE ) (company website)
2                                                                                                                                                                                                                                                6M+ barrels of oil equivalent (BOE) per day (company website)
3                                                                                                                                                                                                                                                                             253 million MT (company website)
4                                                                                                                                                                                        ~100 million tonnes of products shipped annually, with volumes up 10.6% YoY in 2025 (2025.12 LDC - Integrated Report)
5                                                                                                                                                                                                                                                                       ~105.8 million MT (Annual report 2025)
6                                                                                                                                                                                                                                58,091,900 metric tonnes (58.1 million MT) globally (olam annual report 2025)
7                                                                                                                                                                                               approx. 130 million metric tons of agri-commodities traded in 2024 (cofcointernational.com 2024 annual review)
8                                                                                                                                                                               approx. 200 million metric tons equivalent of agricultural and energy commodities handled in 2024 (Cargill 2024 annual report)
9                                                                                                                                                                                         approx. 240 million metric tons of metals, coal and other commodities marketed in 2024 (Glencore 2024 annual report)
10                                                                                                                                                                                                 approx. 60 million metric tons of grains and oilseeds processed and traded in 2024 (ADM 2024 annual report)
11                                                                                                                                                                                                      approx. 65 million metric tons of grains, oilseeds and sugar traded in 2024 (Bunge 2024 annual report)
12                                                                                                                                                                                        approx. 100 million metric tons equivalent of commodities handled globally in 2024 (Marubeni 2024 integrated report)
13                                                                                                                                                                    approx. 110 million metric tons equivalent of energy, metals and other commodities handled in 2024 (Mitsui & Co. 2024 integrated report)
14                                                                                                                                                                                          approx. 20 million tons per year of crude oil and products traded via Singapore arm (company website, 2024 review)
15                                                                                                                                                                                   approx. 8 million barrels per day equivalent of oil and gas products marketed globally in 2024 (Shell 2024 annual report)
16                                                                                                                                                                                                 approx. 7 million barrels per day equivalent of oil and gas traded globally in 2024 (BP 2024 annual report)
17                                                                                                                                                             approx. 6 million barrels per day equivalent of oil, gas and power traded globally in 2024 (TotalEnergies 2024 universal registration document)
18                                                                                                                                                                            approx. 60 million tons of chemicals, petroleum and agri products traded globally in 2024 (Sinochem Holdings 2024 annual report)
19                                                                                                                                                                                                                         approx. 6 million metric tons of agri-commodities traded annually (company website)
20                                                                                                                                                                                                               approx. 10 million tons of palm products produced and traded in 2024 (GAR 2024 annual report)
21                                                                                                                                                                                                           approx. 5 million tons of palm oil and derivatives produced and traded annually (company website)
22                                                                                                                                                                                   approx. 3 million tons of crude palm oil and palm products produced and sold annually (First Resources corporate profile)
23                                                                                                                                                                                                                                                                                                     Unknown
24                                                                                                                                                                                                                                                                                                     Unknown
25                                                                                                                                                                                                                                                                                                     Unknown
26                                                                                                                                                                                                                                                                                                     Unknown
27                                                                                                                                                                                                                                   45.1m Metric Tons Handled (olamagri-corporate-factsheet-2025-english.pdf)
28                                                                                                                                                                                                                                             approx. 12 million MT of raw & white sugar annually (google AI)
29                                                                                                                                                                           Total cargo volume in 2025: 79.8 million tonnes; agri products: ~23.9 million tonnes (claude + Pacific Basin 2025 Annual Results)
30                                                                                                                                                                                                  Noble Resources trades and manages more than 35 million tonnes per year of thermal coal alone (perplexity)
31                                                                                                                                                                                                                                                 More than 5.5 million tonnes of metal annually (perplexity)
32                                                                                                                                                                                                                                                                       ~ 30 million MT annually (perplexity)
33                                                                                                                                                                                                                                                                                                     Unknown
34                                                                                                                                                                                                                                                                   ~  1-2 million metric tonnes (perplexity)
35                                                                                                                                                                                                                                                                over 16 million tonnes annually (perplexity)
36                                                                                                                                                                                                                                                                                                     Unknown
37                                                                                                                                                                                                                                                                                                     Unknown
38                                                                                                                                                                                                                                                                      90m MT (2024) (concordenergygroup.com)
39                                                                                                                                                                                                                                                                                                     Unknown
40                                                                                                                                                                                                                                                    approx. 6,700-10,000 metric tonnes annually (perplexity)
41                                                                                                                                                                                        14.88 million metric tonnes per year (approximately 109.32 million barrels per year) (perplexity + sahara-group.com)
42                                                                                                                                                                                                                                       approx. 182.5 million barrels per year (perplexity + petraco-oil.com)
43                                                                                                                                                                                                                                                                         49.68 mmt FY2024 (socartrading.com)
44                                                                                                                                                                                                                                                                                                     Unknown
45                                                                                                                                                                                                     8 million metric tonnes of chemicals annually (helmag.com), Trade volume for agricultural products: n/a
46                                                                                                                                                                                                                                                                      2,000 tons annually (nittokasei.co.jp)
47                                                                                                                                                                                                                                                                                                     Unknown
48                                                                                                                                                                                                                                                                                                     Unknown
49                                                                                                                                                                                                                                                                                                     Unknown
50                                                                                                                                                                                            LPG: 449,390 tonnes, LNG: 14,379 tonnes, CNG: 43.7 million cubic metres (2025 annual report sinogasholdings.com)
51                                                                                                                                                                                                                                                                                                     Unknown
52                                                                                                                                                                                                                                                                                                     Unknown
53                                                                                                                                                                                                                                                    bunker trading volumes FY2023: 1 040 594 mt (oilmar.com)
54                                                                                                                                                                                                                                                                                                     Unknown
56                                                                                                                                                                                                                                                                               >10 millions mt (group level)
57                                                                                                                                                                                                                                                           ~ 11.6 million metric tonnes annually (google ai)
58                                                                                                                                                                                                                                                                                    165 Mmt+ (trafigura.com)
60                                                                                                                                                                                                                                                                    4.17 million tonnes FY2025 (en.cmoc.com)
61                                                                                                                                                                                                                                                                                                     Unknown
62                                                                                                                                                                                                                                                                            3M metric tons (kztrading.co.kr)
63                                                                                                                                                                                                                                                                1.3 million tonnes. (metal segment) (Gemini)
64                                                                                                                                                                                                                                                                              32 Million MT (abgtrading.com)
65                                                                                                                                                                                                                                                                                                     Unknown
66                                                                                                                                                                                                                                                                                                     Unknown
67                                                                                                                                                                                                                                                                                                     Unknown

In [22]:
# check ownership structure
# remove brackets & whitespace & make it lowercase
p1["Ownership Structure"] = p1["Ownership Structure"].str.replace(r'\(.*?\)', '', regex=True).str.strip().str.lower()
p1["Ownership Structure"] = (
    p1["Ownership Structure"]
    .str.replace(
        r"listed, ultimate parent company is state-owned)",
        "listed, ultimate parent company is state-owned",
        regex=False,
    )
    .str.strip()
    .str.lower()
)

p1["Ownership Structure"].unique()

<StringArray>
[                                       'private',
                                         'listed',
                                    'state-owned',
 'listed, ultimate parent company is state-owned',
   'listed aluminum corporation of china limited']
Length: 5, dtype: str

In [23]:
# check Listed / Exchange
# remove brackets & whitespace
p1["Exchange"] = p1["Exchange"].str.strip()

# pattern to find inside each cell, its canoncial name / transformation. Format as list of tuples [(,),(,),(,)...] where (,) has (pattern, cannonical)
# \b*\b is word boundary. Ex: \bLSE\b will extract only LSE and not PULSE.
standardized_exchange = [
    (r"\blse\b|london", "London Stock Exchange LSE"),
    (r"\bnyse\b|new york", "New York Stock Exchange NYSE"),
    (r"\btse\b|tokyo", "Tokyo Stock Exchange TSE"),
    (r"\bset\b|thailand", "The Stock Exchange of Thailand SET"),
    (r"\bams\b|amsterdam", "Euronext Amsterdam AMS"),
    (r"\bparis\b", "Euronext Paris ENX"),
    (r"\bsgx\b|singapore", "Singapore Exchange SGX"),
    (r"\bhkex\b|hong kong", "Stock Exchange of Hong Kong HKEX"),
    (r"\bkrx\b|korea", "Korea Exchange KRX"),
    (r"\bnasdaq\b", "Nasdaq Stock Market NDAQ"),
    (r"\basx\b|australian securities", "Australian Securities Exchange ASX"),
    (r"\bidx\b|indonesia", "Indonesia Stock Exchange IDX"),
    (r"\bmyx\b|malaysia", "Malaysia Exchange MYX"),
    (r"\bsse\b|shanghai", "Shanghai Stock Exchange SSE"),
]

def standardize(text):
    #check if the cell is na or empty str or unknown
    if pd.isna(text) or text.strip() == '' or 'unknown' in text.lower():
        #return it 
        return text
    else:
        text = text.lower() #put here so capitalized 'Unknown' doesn't become lowercase
        #list to store unique exchange 
        found = []
        #text has exchange, find the pattern in the text
        for pattern, cannonical in standardized_exchange:
            if re.search(pattern, text, re.IGNORECASE): #returns true of pattern is found in text
                if cannonical not in found: #avoids duplication of the same cannonical if pattern is found once
                    found.append(cannonical)
    #once all patterns are found, join the cannonicals as a string and return else return original text if patterns were not found
    return ', '.join(found) if found else text

# run this function for every row in the exchange column
p1['Exchange'] = p1['Exchange'].apply(standardize)
p1["Exchange"].unique()

<StringArray>
[                                                                               '',
                                                          'Singapore Exchange SGX',
                                                       'London Stock Exchange LSE',
                                                    'New York Stock Exchange NYSE',
                                                        'Tokyo Stock Exchange TSE',
                                              'The Stock Exchange of Thailand SET',
 'London Stock Exchange LSE, New York Stock Exchange NYSE, Euronext Amsterdam AMS',
                                                              'Euronext Paris ENX',
                                                'Stock Exchange of Hong Kong HKEX',
                                                                         'Unknown',
                                                              'Korea Exchange KRX',
                                                        'Nasdaq Stock Market NDAQ',
                'New York Stock Exchange NYSE, Australian Securities Exchange ASX',
                                                    'Indonesia Stock Exchange IDX',
                                                           'Malaysia Exchange MYX',
                                                     'Shanghai Stock Exchange SSE',
                       'Australian Securities Exchange ASX, Malaysia Exchange MYX']
Length: 17, dtype: str

In [24]:
#check notes
#remove whitespace
p1['Notes'] = p1['Notes'].str.strip()

In [25]:
p1.head()

   Tier           Company Name       Commodity Type                                                                                                                                         Commodity Focus                                             Legal Name / ACRA UEN   HQ Country                                                                                 APAC Offices                                               Estimated Revenue Headcount (Global)                                                                                                    Trade Volume (Est.) Ownership Structure Exchange                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Notes
0     1              Trafigura   [multi (>2 types)]                                                                  Multi-commodity (Oil & Petroleum Products, Natural Gas & LNG, Metals & Minerals, Agri)                TRAFIGURA GROUP PTE. LTD. / 201017488D (recordowl)    Singapore  10 Collyer Quay, #29-01/05, Ocean Financial Centre, Singapore 049315, Singapore (recordowl)            Trafigura Group: 240.3 USD bn FY2025 (trafigura.com)    5011 (linkedin)                                                          approx. 462 million metric tons (2025 annual report + claude)             private                                                                                                                                                                                                                                                                                                                                                                               Latest acquisition (after Sep 2025): Greenergy that is owned by trafigura, acquired France's Armorine Group (trafigura 2025 annual report)
1     1                  Vitol     multi (>2 types)  Crude Oil, Petroleum Products, LNG, Natural gas, Biogas/BioLNG, thermal coal, metcoke, metals, power/electricity, plastics recycling (company website)                      VITOL ASIA PTE LTD. / 199001917Z (recordowl)  Switzerland                                  128 BEACH ROAD #28-01 GUOCO MIDTOWN OFFICE SINGAPORE 189773               Turnover of $343 billion FY2025 (company website)    1990 (linkedin)                              total energy trade volume: 605 million tonnes of oil equivalent (mTOE ) (company website)             private                                                                                                                                                                                                                                                                                                                                                                                                                              Its largest operations are in Geneva, Houston, London and Singapore. (world economic forum)
2     1               Mercuria   [multi (>2 types)]                                                                                                                                    Energy, Metals, Agri  MERCURIA HOLDINGS (SINGAPORE) PTE. LTD. / 201808173Z (recordowl)  Switzerland                 12 Marina View, #26-01, Asia Square Tower 2, Singapore 018961 (mercuria.com)                                      $618.7 Million (zoom.info)    1380 (linkedin)                                                          6M+ barrels of oil equivalent (BOE) per day (company website)             private                                                                                                                                                                                                                             Mercuria Holdings (Singapore) Pte. Ltd. is a global commodity trader connecting essential resources to energy markets, operating globally and at scale. The company operates in over 50 countries across 5 continents and has a main trading hub located in Geneva, Switzerland. (recordowl)
3     1                 Gunvor             [energy]                                    Crude oil, refined petroleum products, natural gas and liquefied natural gas, biofuels, power, and carbon emissions.            GUNVOR SINGAPORE PTE. LTD. / 200606959K (acra bizfile)  Switzerland               128 Beach Road, #29-01, Guoco Midtown Office, Singapore 189773 (recordowl.com)                               US $144 billion (company website)    1035 (linkedin)                                                                                       253 million MT (company website)             private                                                                                                                                                                                                                                                                                                                                                                       one of the world's largest independent commodities trading houses by turnover. It has trading offices in Geneva, Singapore, the Bahamas and Dubai.
4     1  Louis Dreyfus Company  [soft/agricultural]                                            Agri, Soft Commodities, Grains, Oilseeds, coffee, cotton, sugar, rice, juice, food & feed solutions, freight  LOUIS DREYFUS COMPANY ASIA PTE. LTD. / 199306551Z (acra bizfile)  Netherlands    12 MARINA BOULEVARD #33-03 MARINA BAY FINANCIAL CENTRE SINGAPORE 018982 (company website)  Net Sales: US$ 53.2bn FY2025 (2025.12 LDC - Integrated Report)  13,359 (linkedin)  ~100 million tonnes of products shipped annually, with volumes up 10.6% YoY in 2025 (2025.12 LDC - Integrated Report)             private           LDC is purely agricultural, no energy commodity trading, heavily weighted towards grains & oilseeds, Profitability declined slightly in 2025 vs. 2024 (EBITDA -2.8%, Net Income -10%) despite higher revenues, due to tariff headwinds, geopolitical uncertainty, and higher finance costs, Aggressive capex cycle: capital expenditure nearly doubled to US$2.0 billion in 2025 (from US$1.0 billion in 2024), reflecting major processing and logistics expansion (2025.12 LDC - Integrated Report + claude)

In [26]:
# reset all index again
p1 = p1.reset_index(drop=True)
p1

     Tier                                                                   Company Name                       Commodity Type                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Commodity Focus                                                                                    Legal Name / ACRA UEN              HQ Country                                                                                                                                                                                                           APAC Offices                                                                                                             Estimated Revenue                                                                Headcount (Global)                                                                                                                                                                                                                                                                                      Trade Volume (Est.)                             Ownership Structure                                                                         Exchange                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Notes
0       1                                                                      Trafigura                   [multi (>2 types)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Multi-commodity (Oil & Petroleum Products, Natural Gas & LNG, Metals & Minerals, Agri)                                                       TRAFIGURA GROUP PTE. LTD. / 201017488D (recordowl)               Singapore                                                                                                                            10 Collyer Quay, #29-01/05, Ocean Financial Centre, Singapore 049315, Singapore (recordowl)                                                                          Trafigura Group: 240.3 USD bn FY2025 (trafigura.com)                                                                   5011 (linkedin)                                                                                                                                                                                                                                            approx. 462 million metric tons (2025 annual report + claude)                                         private                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Latest acquisition (after Sep 2025): Greenergy that is owned by trafigura, acquired France's Armorine Group (trafigura 2025 annual report)
1       1                                                                          Vitol                     multi (>2 types)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Crude Oil, Petroleum Products, LNG, Natural gas, Biogas/BioLNG, thermal coal, metcoke, metals, power/electricity, plastics recycling (company website)                                                             VITOL ASIA PTE LTD. / 199001917Z (recordowl)             Switzerland                                                                                                                                                            128 BEACH ROAD #28-01 GUOCO MIDTOWN OFFICE SINGAPORE 189773                                                                             Turnover of $343 billion FY2025 (company website)                                                                   1990 (linkedin)                                                                                                                                                                                                                total energy trade volume: 605 million tonnes of oil equivalent (mTOE ) (company website)                                         private                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Its largest operations are in Geneva, Houston, London and Singapore. (world economic forum)
2       1                                                                       Mercuria                   [multi (>2 types)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Energy, Metals, Agri                                         MERCURIA HOLDINGS (SINGAPORE) PTE. LTD. / 201808173Z (recordowl)             Switzerland                                                                                                                                           12 Marina View, #26-01, Asia Square Tower 2, Singapore 018961 (mercuria.com)                                                                                                    $618.7 Million (zoom.info)                                                                   1380 (linkedin)                                                                                                                                                                                                                                            6M+ barrels of oil equivalent (BOE) per day (company website)                                         private                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Mercuria Holdings (Singapore) Pte. Ltd. is a global commodity trader connecting essential resources to energy markets, operating globally and at scale. The company operates in over 50 countries across 5 continents and has a main trading hub located in Geneva, Switzerland. (recordowl)
3       1                                                                         Gunvor                             [energy]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Crude oil, refined petroleum products, natural gas and liquefied natural gas, biofuels, power, and carbon emissions.                                                   GUNVOR SINGAPORE PTE. LTD. / 200606959K (acra bizfile)             Switzerland                                                                                                                                         128 Beach Road, #29-01, Guoco Midtown Office, Singapore 189773 (recordowl.com)                                                                                             US $144 billion (company website)                                                                   1035 (linkedin)                                                                                                                                                                                                                                                                         253 million MT (company website)                                         private                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             one of the world's largest independent commodities trading houses by turnover. It has trading offices in Geneva, Singapore, the Bahamas and Dubai.
4       1                                                          Louis Dreyfus Company                  [soft/agricultural]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Agri, Soft Commodities, Grains, Oilseeds, coffee, cotton, sugar, rice, juice, food & feed solutions, freight                                         LOUIS DREYFUS COMPANY ASIA PTE. LTD. / 199306551Z (acra bizfile)             Netherlands                                                                                                                              12 MARINA BOULEVARD #33-03 MARINA BAY FINANCIAL CENTRE SINGAPORE 018982 (company website)                                                                Net Sales: US$ 53.2bn FY2025 (2025.12 LDC - Integrated Report)                                                                 13,359 (linkedin)                                                                                                                                                                                    ~100 million tonnes of products shipped annually, with volumes up 10.6% YoY in 2025 (2025.12 LDC - Integrated Report)                                         private                                                                                                                                                                                                                                                 LDC is purely agricultural, no energy commodity trading, heavily weighted towards grains & oilseeds, Profitability declined slightly in 2025 vs. 2024 (EBITDA -2.8%, Net Income -10%) despite higher revenues, due to tariff headwinds, geopolitical uncertainty, and higher finance costs, Aggressive capex cycle: capital expenditure nearly doubled to US$2.0 billion in 2025 (from US$1.0 billion in 2024), reflecting major processing and logistics expansion (2025.12 LDC - Integrated Report + claude)
5       1                                                           Wilmar International                  [soft/agricultural]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Palm Oil, Sugar, Grains, Oilseeds                                                    WILMAR INTERNATIONAL LIMITED / 199904785Z (recordowl)               Singapore                                                                                                                                                          28 Biopolis Road, Singapore 138568 (wilmar-international.com)                                                                                                US$70.42B (Annual Report 2025)                                                                  7,723 (linkedin)                                                                                                                                                                                                                                                                   ~105.8 million MT (Annual report 2025)                                          listed                                                           Singapore Exchange SGX  Wilmar is Asia's largest agribusiness group, founded in 1991 and headquartered in Singapore. The Group's business activities include oil palm cultivation, oilseed crushing, edible oils refining, flour and rice milling, sugar milling and refining, manufacturing of consumer products, ready-to-eat meals, central kitchen products, specialty fats, oleochemicals, biodiesel and fertilisers as well as food park operations. FY2025 faced misconduct allegations involving a subsidiary and a state-owned enterprise but the company categorically denied all allegations and stated it will defend its position through legal channels. (annual report 2025 + claude)
6       1                                                                     Olam Group                  [soft/agricultural]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Agri, Food, Industrial Raw Materials, cocoa, coffee, cotton, nuts and spices                                                          OLAM GROUP LIMITED / 202180000W (olamgroup.com)               Singapore                                                                                                                                        7 Straits View, #20-01, Marina One East Tower, Singapore 018936 (olamgroup.com)                                    Total Sales Revenue: S$66,997.3 million (~S$67.0 billion) FY2025 (olam annual report 2025)                                                                   8766 (linkedin)                                                                                                                                                                                                                            58,091,900 metric tonnes (58.1 million MT) globally (olam annual report 2025)                                          listed                                                           Singapore Exchange SGX                                    Olam divides into 3: olam food ingredients (ofi), olam agri (discontinuing as being sold to SALIC), remaining olam group. Its immediate parent is Temasek Capital (Private) Limited.Olam is undergoing a major Re-organisation Plan — it is divesting Olam Agri (the largest segment by volume and revenue) to SALIC and intends to distribute net proceeds progressively to shareholders, leaving ofi as the primary remaining operating business. Olam is exclusively agricultural.Co-Founder and Group CEO Sunny George Verghese is stepping down as Executive Director and Group CEO following the 2026 AGM. (olam annual report 2025)

In [27]:
# save as cleaned_pillar1
p1.to_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar1.csv", index=False)