In [29]:
import pandas as pd

# display columns without truncation
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

# display rows without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.expand_frame_repr", False)

In [30]:
p2 = pd.read_csv(r"D:\commo\code\Pillar 2 - Law Firms(Active_sheet).csv", encoding='utf-8')

# drop columns
p2 = p2.drop(
    columns=[
        "(SG) Partners Specialized in Commodities / Trade / Shipping", "BD Contact Name",
        "BD Contact Email",
        "BD Contact Phone",
        "Relationship Status",
        "Priority (H/M/L)",
        "Done by",
        "Unnamed: 14",
        "Unnamed: 15",
        "Unnamed: 16",
        "Unnamed: 17",
    ]
)
# rename columns
p2.rename(columns={"Practice Areas (Disputes / Sanctions / Finance / M&A)": "Practice Areas", 
                   "Known Client Base (Chambers / Legal 500 / SIAC) ": "Known Client Base",
                   "Notes / Next Steps": "Notes"}, inplace=True)
# drop empty rows
p2 = p2.dropna(subset=["Type (Intl / Local)"])
# fill in missing val with Unknown
p2 = p2.fillna({"Office Location(s) in APAC":"Unknown",
                "Known Client Base":"Unknown",
                "Notable Cases / Disputes": "Unknown",
                "BD Contact Name": "Unknown",
                "Notes": ''})

p2.tail()

                  Firm Name Type (Intl / Local)                                                                               Office Location(s) in APAC                                                                                                                                                                                                                                                           Practice Areas                                                                                                                                                                                                                                                                                                                                       Known Client Base                                                                                                                                                                                                                            Notable Cases / Disputes                               Notes
35  Providence Law Asia LLC     Singapore Local                One Raffles Place, Tower 2, #29-62, Singapore 048616 (https://www.providencelawasia.com/)    International Arbitration, Corporate & Commercial Litigation, Restructuring & Insolvency, Construction, Infrastructure & Energy, Fraud & Asset Recovery, Investigations and Regulatory Affairs, SICC Expertise, Technology Disputes, Private Client Practice (gemini)                                            Telekom Malaysia, PricewaterhouseCoopers, GTP Advisory, Liberty House Group, GP Global Group, Zenrock Commodities Trading, Peking University Founder Group, Submarine Cable Logistics, PDV Marina (Venezuela), Agritrade Resources Limited, Thaicom,  Ventureast (gemini, https://www.providencelawasia.com)  Re Hin Leong Trading (Pte) Ltd [2025] / [2026], Re GP Global APAC Pte Ltd [2024] / [2025], HSBC v Zenrock Commodities Trading Pte Ltd, Alphard Maritime Ltd v Samson Maritime Ltd and Underwater Services Company Limited [2025] SGHC 154 (gemini)  https://www.providencelawasia.com/
36     LVM Law Chambers LLC     Singapore Local         160 Robinson Road, #13-02 SBF Center, Singapore 068914 (https://www.lvmlawchambers.com/contact/)                                                                                                                                                                                                                                            dispute resolution (chambers)           MS First Capital Insurance, Brazen Sky, United Overseas Bank, Golden Base Energy Pte Ltd, Unipec Singapore Pte Ltd, Hin Leong Trading (Pte.) Ltd, Ocean Tankers (Pte.) Ltd (Affiliated Matters), GrabTaxi Holdings Pte Ltd, Ochroid Trading Ltd, Laud Architects Pte Ltd, CKR Contract Services Pte Ltd, Lendlease Singapore Pte Ltd (gemini)                                                                                                                                                                The “Maersk Katalin” [2024] SGHC 282, CYE v CYF [2023] SGHC 275 (lvmlawchambers.com)     https://www.lvmlawchambers.com/
37         Incisive Law LLC     Singapore Local                                             120 Robinson Road #08-01, Singapore 068913 (incisivelaw.com)                                                                                                     shipping, international trade, international arbitration, commercial litigation, insurance, criminal law, corporate, shp finance & escrow services (incisivelaw.com)  Teras Lyza Pte Ltd / Teras Offshore Pte Ltd (Ezion Holdings group), MISC Berhad (Malaysia International Shipping Corporation), ArgoGlobal Underwriting Asia Pacific Pte Ltd, Scandinavian Bunkering AS, China National Petroleum Corporation (CNPC) / PetroChina Subsidiaries, Oversea-Chinese Banking Corporation (OCBC), SBM Offshore Group (gemini)                                                                       Argoglobal Underwriting Asia Pacific Pte Ltd and others v Oversea-Chinese Banking Corporation Limited SGCA 14, The “Sea Justice” SGCA 32, The “Tina I” 3 SLR 121 (perplexity)            https://incisivelaw.com/
38         Damodara Ong LLC     Singapore Local          30 Cecil St, #11-01 Prudential Tower, Singapore 049712 (https://www.damodaraong.com/#!/contact)                                                                                                                                                                                      Dispute resolution, corporate, family and private wealth, criminal law (perplexity)                                                                                                                                                                                                                                                                                                                   Ocean Tankers (Pte.) Ltd (perplexity)                                                                                                                                                                                                                                             Unknown        https://www.damodaraong.com/
39       Focus Law Asia LLC     Singapore Local  16 Raffles Quay #21-01, Hong Leong Building, Singapore 048581 (https://www.focuslawasia.com/contact-us)  Commercial Litigation, International Arbitration, Shipping & Commodities, Building & Construction, Restructuring & Insolvency, Family & Private Clients, Employment Law, Corporate Advice, Fintech & Cryptocurrency, Business Formation (https://www.focuslawasia.com/)                                                                                                                                                                                                                                                                                     Maersk Tankers Singapore, Hin Leong Trading (Pte.) Ltd (perplexity)                                                                   Advising  the liquidators of Hin Leong Trading (Pte.) Ltd,  [2022] SGHC 242, [2021] SGHC 286, [2024] SGHC 63,  [2025] SGCA 33 (https://www.focuslawasia.com/our-people/shem-khoo)       https://www.focuslawasia.com/

In [31]:
p2.shape
p2.columns

Index(['Firm Name', 'Type (Intl / Local)', 'Office Location(s) in APAC',
       'Practice Areas', 'Known Client Base', 'Notable Cases / Disputes',
       'Notes'],
      dtype='str')

In [32]:
p2.isna().sum()

Firm Name                     0
Type (Intl / Local)           0
Office Location(s) in APAC    0
Practice Areas                0
Known Client Base             0
Notable Cases / Disputes      0
Notes                         0
dtype: int64

In [33]:
p2.info()

<class 'pandas.DataFrame'>
Index: 38 entries, 1 to 39
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Firm Name                   38 non-null     str
 1   Type (Intl / Local)         38 non-null     str
 2   Office Location(s) in APAC  38 non-null     str
 3   Practice Areas              38 non-null     str
 4   Known Client Base           38 non-null     str
 5   Notable Cases / Disputes    38 non-null     str
 6   Notes                       38 non-null     str
dtypes: str(7)
memory usage: 2.4 KB

In [34]:
# check Firm Name
#remove whitespace
p2['Firm Name'] = p2['Firm Name'].str.strip()
p2.loc[p2["Firm Name"].isna()]
p2['Firm Name'].unique()

<StringArray>
[                  'Reed Smith',  'HFW (Holman Fenwick Willan)',
                   'Clyde & Co',           'Stephenson Harwood',
     'Watson Farley & Williams',                         'Ince',
        'Norton Rose Fulbright',               'Baker McKenzie',
          'Squire Patton Boggs',               'Hill Dickinson',
              'Mayer Brown LLP',         'Latham & Watkins LLP',
                 'Rajah & Tann',             'Allen & Gledhill',
                'Drew & Napier',              'WongPartnership',
                 'Helmsman LLC',            'Blackstone & Gold',
        'Braddell Brothers LLP',    'Joseph Tan Jude Benny LLP',
 'Dentons Rodyk & Davidson LLP',              'Oon & Bazul LLC',
                  'PDLegal LLC',          'Shook Lin & Bok LLP',
         'TSMP Law Corporation',               'Virtus Law LLP',
                'DennisMathiew',                'AsiaLegal LLC',
          'Christopher Lau, SC',    'Dunbar & Lim Chambers LLC',
       'Haridass Ho & Partners',    'Gill Arbitration Services',
           'PK Wong & Nair LLC',      'Providence Law Asia LLC',
         'LVM Law Chambers LLC',             'Incisive Law LLC',
             'Damodara Ong LLC',           'Focus Law Asia LLC']
Length: 38, dtype: str

In [35]:
# firms that are associated with each other
"""
https://www.reedsmith.com/legal-notices/country-specific-legal-notices/singapore/
Reed Smith practices law in Singapore through Reed Smith Resource Law Alliance comprising Reed Smith Pte Ltd and Resource Law LLC.
Reed Smith Pte Ltd is a company registered in Singapore and licensed by the Ministry of Law and operates under license as a formal law alliance with Resource Law LLC, which is a Singapore law practice.

https://www.virtus-law.com/international-network/
Virtus Law LLP is a member of the Stephenson Harwood (Singapore) Alliance, a formal law alliance with Stephenson Harwood LLP.

https://www.legalbusinessonline.com/incisive-law-qa-%E2%80%98-single-singapore-law-practice-way-forward%E2%80%99
Ince & Co Singapore LLP and Incisive Law LLC consolidated into one entity in terms of business and management but function individually in terms of legal licensing.
"""

'\nhttps://www.reedsmith.com/legal-notices/country-specific-legal-notices/singapore/\nReed Smith practices law in Singapore through Reed Smith Resource Law Alliance comprising Reed Smith Pte Ltd and Resource Law LLC.\nReed Smith Pte Ltd is a company registered in Singapore and licensed by the Ministry of Law and operates under license as a formal law alliance with Resource Law LLC, which is a Singapore law practice.\n\nhttps://www.virtus-law.com/international-network/\nVirtus Law LLP is a member of the Stephenson Harwood (Singapore) Alliance, a formal law alliance with Stephenson Harwood LLP.\n\nhttps://www.legalbusinessonline.com/incisive-law-qa-%E2%80%98-single-singapore-law-practice-way-forward%E2%80%99\nInce & Co Singapore LLP and Incisive Law LLC consolidated into one entity in terms of business and management but function individually in terms of legal licensing.\n'

In [36]:
# change Ince to Ince & co
p2.loc[p2["Firm Name"] == "Ince", "Firm Name"] = "Ince & Co Singapore LLP"
p2.loc[p2["Firm Name"] == "Ince & Co Singapore LLP", "Office Location(s) in APAC"] = (
    "5 SHENTON WAY, #19-01, UIC BUILDING, Singapore 068808"
)
#p2.loc[p2["Firm Name"] == "Ince & Co Singapore LLP", "(SG) Partners Specialized in Commodities / Trade / Shipping"] = "Unknown"
p2.loc[p2["Firm Name"] == "Ince & Co Singapore LLP", "Practice Areas"] = (
    "disputes, transactions and projects in Maritime, Insurance, Trade Law and more"
)

In [37]:
# add a single row: Resource Law LLC row

resourcelawLLC = {
    "Firm Name": "Resource Law LLC",
    "Type (Intl / Local)": "Singapore Local",
    "Office Location(s) in APAC": "10 Collyer Quay, #18-01, Ocean Financial Centre, Singapore 049315",
    #"(SG) Partners Specialized in Commodities / Trade / Shipping": "MD: Bernard Yee",
    "Practice Areas": "Bankruptcy & Commercial Restructuring, Competition, Corporate & Securities, Energy & Natural Resources, Finance, Information Technology, Privacy & Data Security, Insurance Litigation, Intellectual Property, International Trade, Labour & Employment, Life Sciences, Litigation & Dispute Resolution, Real Estate, Shipping",
    "Known Client Base": "Unknown",
    "Notable Cases / Disputes": "Unknown",
    "BD Contact Name": "Unknown",
    "Notes": "https://www.resourcelawasia.com/",
}

# get index of last row
p2.index[-1] #39, new row will be index 40

p2.loc[40] = resourcelawLLC
p2.index[-1] #last index should be index 40

np.int64(40)

In [38]:
#check Type (Intl / Local)
p2['Type (Intl / Local)'].unique()

array(['International', 'Singapore Local'], dtype=object)

In [39]:
# check office locations
# strip whitespace
p2["Office Location(s) in APAC"] = p2["Office Location(s) in APAC"].str.strip()
# title-case every word
p2["Office Location(s) in APAC"] = p2["Office Location(s) in APAC"].str.title()
p2["Office Location(s) in APAC"]

1                                                                      10 Collyer Quay, #18-01 Ocean Financial Centre, Singapore 049315 (Reedsmith.Com)
2                                                                                       30 Raffles Place, #24-01, Bni Tower, Singapore 048622 (Hfw.Com)
3                                                       12 Marina Boulevard, #30-03 Marina Bay Financial Centre Tower 3, Singapore 018982 (Clydeco.Com)
4     Stephenson Harwood (Singapore) Alliance, 8 Marina Boulevard #29-01, Marina Bay Financial Centre Tower 1, Singapore 018981 (Stephensonharwood.Com)
5                                                                         88 Market Street #31-05, Capitaspring, Singapore, 048948, Singapore (Wfw.Com)
6                                                                                                 5 Shenton Way, #19-01, Uic Building, Singapore 068808
7                                                          Norton Rose Fulbright (Asia) Llp ,9 Straits Viewmarina One West Tower#09-09 Singapore 018937
8                                                                           38 Beach Road #23-11 South Beach Tower Singapore 189767 (Bakermckenzie.Com)
9                                                         1 Marina Boulevard, #21-01 One Marina Boulevard, Singapore 018989 (Www.Squirepattonboggs.Com)
10                                                          3 Anson Road, Springleaf Tower, 24-03, Singapore, 079909, Sg ( Hill Dickinson Llp Linkedin)
11                                                          6 Battery Road, #10-01, Singapore 049909 (Https://Www.Mayerbrown.Com/En/About-Us/Locations)
12                                                                        9 Raffles Place #42-02 Republic Plaza Singapore, 048619 (Https://Www.Lw.Com/)
14                                                                9 Straits View, #06-07 Marina One West Tower, Singapore 018937 (Sg.Rajahtannasia.Com)
15                                                                                One Marina Boulevard, #28-00, Singapore 018989 (Allenandgledhill.Com)
16                             10 Collyer Quay #10-01 Ocean Financial Centre , Singapore, Singapore Island, Singapore, 049315, Singapore (Chambers.Com)
17                                          12 Marina Boulevard Level 28 Marina Bay Financial Centre Tower 3 Singapore 018982 (Www.Wongpartnership.Com)
18                                                  21A Duxton Hill (Reception: 19 Duxton Hill), Singapore 089604 (Https://Www.Helmsmanlaw.Com/Contact)
19                                                                                70 Shenton Way, Eon Shenton, #10-12, S079118 (Www.Blackstonegold.Com)
20                                                11 Beach Road #04-01 Singapore , Singapore, Singapore Island, Singapore, 189675, Singapore (Chambers)
21                                                                                 168 Robinson Road, #18-02 Capital Tower, Singapore 068912 (Jtjb.Com)
22                                                                          80 Raffles Place, #33-00 Uob Plaza 1, 048624, Singapore (Dentons.Rodyk.Com)
23                                                             36 Robinson Road, #08-01/06 City House, Singapore 068877 (Https://Oonbazul.Com/Contact/)
24                                                                        1 Coleman Street , #08-02 The Adelphi , Singapore 179803 (Www.Pdlegal.Com.Sg)
25                                                                   1 Robinson Road, #18-00 Aia Tower, Singapore 048542 (Https://Www.Shooklin.Com/En/)
26                                                                      6 Battery Road, Level 5, Singapore 049909 (Https://Www.Tsmplaw.Com/Contact-Us/)
27                                      8 Marina Boulevard, #29-01, Marina Bay Financial Centre Tower 1, Singapore 018981 (Https://Www.Virtus-Law.Com/)
28                                                      7500A Beach Road, #14-324, The Plaza, Singapore 199591 (Https://Www.Dennismathiew.Com/Contact/)
29                                                                                    1 Coleman Street, #07-02A, The Adelphi, Singapore 179803 (Gemini)
30                                    32 Maxwell Road, #02-04 Maxwell Chambers, Singapore 069115 (Https://Arbitrationlaw.Com/Profile/Christopher-Lau-0)
31                                                             160 Robinson Road, #18-03 Sbf Center, Singapore 068914  (Https://Dunbarlim.Com/Contact/)
32                                                            4 Shenton Way, #10-03/06 Sgx Centre 2, Singapore 068807 (Https://Hhp.Com.Sg/Sample-Page/)
33                                             81A Clemenceau Avenue, #05-18, Ue Square, Singapore 239918 (Https://Www.Judithgill.Com/#Answers-Section)
34                                                                                       6 Battery Road, #09-03, Singapore 049909 (Https://Pkw.Com.Sg/)
35                                                            One Raffles Place, Tower 2, #29-62, Singapore 048616 (Https://Www.Providencelawasia.Com/)
36                                                     160 Robinson Road, #13-02 Sbf Center, Singapore 068914 (Https://Www.Lvmlawchambers.Com/Contact/)
37                                                                                         120 Robinson Road #08-01, Singapore 068913 (Incisivelaw.Com)
38                                                      30 Cecil St, #11-01 Prudential Tower, Singapore 049712 (Https://Www.Damodaraong.Com/#!/Contact)
39                                              16 Raffles Quay #21-01, Hong Leong Building, Singapore 048581 (Https://Www.Focuslawasia.Com/Contact-Us)
40                                                                                    10 Collyer Quay, #18-01, Ocean Financial Centre, Singapore 049315
Name: Office Location(s) in APAC, dtype: object

In [40]:
# check the partners
# p2['(SG) Partners Specialized in Commodities / Trade / Shipping'].unique()
# strip whitespace
# change , to ; between Managing Partner: n/a, Partners :Jun Bautista, Kimarie Cheang, Sumeet Malhotra
# partner_mapping = {
#    "Managing Partner - Asia: Prajakt Samant (reedsmith.com)": "Managing Partner, Asia: Prajakt Samant (reedsmith.com)",
#    "Managing Partner: n/a, Partners :Jun Bautista, Kimarie Cheang, Sumeet Malhotra, Merrick White (wfw.com)": "Partners: Jun Bautista, Kimarie Cheang, Sumeet Malhotra, Merrick White (wfw.com)",
#    "Global Managing Partner; Europe, Middle East and Asia Pacific in London: Peter Scott (google ai), Partners in SG : Ben Rose & Nick Merritt, Head of Singapore: Yu-En Ong  (nortonrosefulbright.com)": "Global Managing Partner, Europe, Middle East, and Asia Pacific in London: Peter Scott (google ai). Head of Singapore: Yu-En Ong (nortonrosefulbright.com)",
#    "Managing Partner: Barry Stimpson, Partner: Chris Swart (squirepattonboggs.com), Managing Partner: Ignatius Hwang (SN)": "Managing Partner: Barry Stimpson, Ignatius Hwang. Partner: Chris Swart (squirepattonboggs.com)",
#    "Master Mariner /Counsel: Binoy Dubey, Master Mariner /Partner: Donal Keaney, Partner | Head of Singapore office: Andrew Lee (https://www.hilldickinson.com/)": "Master Mariner/Counsel: Binoy Dubey. Master Mariner/Partner: Donal Keaney. Partner/Head of Singapore office: Andrew Lee (https://www.hilldickinson.com/)",
#    "Partner:Nicholas P. Luongo (https://www.lw.com/), Associate Managing Partner, Asia: Simon Cooke (https://law.asia/), Partner: Yvette D. Valdez, Douglas K. Yatter, Carlos Alvarez (https://www.lw.com/)": "Partners: Nicholas P. Luongo, Yvette D. Valdez, Douglas K. Yatter, Carlos Alvarez (https://www.lw.com/). Associate Managing Partner, Asia: Simon Cooke (https://law.asia/)",
#    "Head of Shipping & International Trade: Leong Kah Wah, Head of Corporate Shipping & Finance: Chua Choon King, Deputy Head of Shipping & International trade: Nathanael Lin, Partners: (V Bala, Aleksandar Anatoliev Georgiev, Daphne Chua, Dedi Affandi Bin Ahmad, Dharini Ravi, Jainil Bhandari, Jonathan Oon, Kendall Tan, Lim Chen Chen, Nicole Ong, Ting Yong Hong, Winston Kwek, Wu Junneng, Yang Lih Shyng, Yu Zheng), Senior Partner: Toh Kian Sing, SC (sg.rajahtannasia.com)": "Head of Shipping & International Trade: Leong Kah Wah. Head of Corporate Shipping & Finance: Chua Choon King",
#    "Partners: (Vivian Ang, Jonathan Choo, Ho Pey Yann, Daniel Liang, Dorcas Seah, Soh Yin Chuin, Corina Song, Siva Subramaniam, Erik Widjaja, Kenny Yap, Yap Yin Soon, Tan Zhi Feng) (allendandgledhill.com), Managing Partner: Jerry Koh (SN)": "Managing Partner: Jerry Koh (SN)",
#    "Chairman: Jimmy Yim SC, MD Dispute Resolution: Mahesh Rai (drewnapier.com)": "Chairman: Jimmy Yim SC. MD Dispute Resolution: Mahesh Rai (drewnapier.com)",
#    "Managing Partner: Chou Sean Yu (chambers), Partners: Alessa PANG, Charles TIAN XIAOMING, Daniel GAW, KOH Swee Yen, Senior Counsel, Lesley TAN, LIN Chunlong, Melanie HO, TAY Peng Cheng (www.wongpartnership.com)": "Managing Partner: Chou Sean Yu (chambers)",
#    "Deputy Managing Partner: John Sze (SN), Senior Partners: K. MURALI PANY, TING CHI YEN, partners: RAFIZAH GAFFOOR, JOLENE TAN (jtjb.com)": "Deputy Managing Partner: John Sze (SN). Senior Partners: K. MURALI PANY, TING CHI YEN",
#    "Snr Partners: Lawrence Teh, Rodney Keong, Kirindeep Singh, Melissa Thng (dentons.rodyk.com)": "Senior Partners: Lawrence Teh, Rodney Keong, Kirindeep Singh, Melissa Thng (dentons.rodyk.com)",
#    "Group Managing Partner: Peter Doraisamy, Group Deputy Managing Partner: Gerard Quek (https://www.pdlegal.com.sg/people/)": "Group Managing Partner: Peter Doraisamy. Group Deputy Managing Partner: Gerard Quek (https://www.pdlegal.com.sg/people/)",
#    "Managing Partner: Liew Kai Zee (chambers); Co Managing Partner: David Chong (linkedin); Partners: Moses Lin, Sarjit Singh Gill, Soong Jun De (shooklin.com)": "Managing Partner: Liew Kai Zee (chambers). Co Managing Partner: David Chong (linkedin)",
#    "Director: Magdalene Chew, Snr Dirs: Timothy Tan & P. Jeya Putra (gemini)": "Director: Magdalene Chew. Senior Directors: Timothy Tan & P. Jeya Putra (gemini)",
#    "MD: Lok Vi Ming, S.C.; Joint MD: Joseph Lee (https://www.lvmlawchambers.com/practice/international-trade-shipping-and-sanctions/)": "MD: Lok Vi Ming, S.C.. Joint MD: Joseph Lee (https://www.lvmlawchambers.com/practice/international-trade-shipping-and-sanctions/)",
#    "MD: Loh Wai Yue, Deputy MD: Davis Tan (https://incisivelaw.com/our-people/)": "MD: Loh Wai Yue. Deputy MD: Davis Tan (https://incisivelaw.com/our-people/)",
# }
# p2['(SG) Partners Specialized in Commodities / Trade / Shipping'] = p2['(SG) Partners Specialized in Commodities / Trade / Shipping'].replace(partner_mapping)

# p2['(SG) Partners Specialized in Commodities / Trade / Shipping'] = p2['(SG) Partners Specialized in Commodities / Trade / Shipping'].str.replace(r'\bMD\b', 'Managing Director',regex=True)
# p2['(SG) Partners Specialized in Commodities / Trade / Shipping'] = p2['(SG) Partners Specialized in Commodities / Trade / Shipping'].str.strip()

# p2["(SG) Partners Specialized in Commodities / Trade / Shipping"].unique()

In [41]:
# check Practice Areas
# normalize delimiters
p2['Practice Areas'] = (p2['Practice Areas']
 .str.replace(r'\s*;\s*', ', ', regex=True) # \s* >= 0 whitespace
 .str.replace(r',\s*and\s+', ', ', regex=True) # \s+ >0 whitespace. X, and Y -> X, Y
 .str.replace(r'\s+and\s+(?=[A-Za-z])', ', ', regex=True) # (?) is the condition. ' and letters' becomes ', letters'
 .str.replace(r'\s+,\s*', ', ', regex=True) # '  ,...' becomes ', '
 .str.replace(r'\(.*?\)', '', regex=True)
 .str.strip())

# fix common typos
import re 
typo_fixes = {
    r"\bemploymebt\b": "employment",
    r"\bcommerical\b": "commercial",
    r"\bcommerical\b": "commercial",
    r"\bmartime\b": "maritime",
    r"\bconveynacing\b": "conveyancing",
    r"\bshp finance\b": "ship finance",
    r"\bemployement\b": "employment",
    r"\bproerty\b": "property",
    r"\bintl trade\b": "international trade",
    r"\bintl\b": "international",
}
for key, value in typo_fixes.items():
    p2['Practice Areas'] = p2['Practice Areas'].str.replace(key, value, regex=True, flags=re.IGNORECASE)

p2['Practice Areas'].unique()

array(['Advisory & Counseling, Regulatory, Litigations & Disputes, Transactional',
       'Corporate & Commercial, Dispute, Finance, Regulatory, Specialized areas',
       'corporate, commercial, construction, dispute resolution , employment, finance, governance, regulatory, compliance',
       'commercial, data & tech, corporate, dispute resolution, employment, pensions & immigration, finance, insurance, intellectual property, maritime, trade & offshore, private wealth, projects, energy & infrastructure, real estate, regulatory & investigations',
       'Finance & Capital Markets, Corporate & M&A, Dispute Resolution, Regulatory & Competition, etc',
       'disputes, transactions, projects in Maritime, Insurance, Trade Law, more',
       'Litigation, disputes, Energy, Corporate, M&A, securities, Banking, finance, Regulation, investigations, Projects, Private equity, Real estate, Restructuring, Intellectual property, Infrastructure, Capital markets, Corporate governance, Employment, labor, Renewables',
       'Antitrust & Competition, Artificial Intelligence, Banking & Finance, Capital Markets, Data, Technology, Privacy & Cybersecurity, Dispute Resolution, Employment & Compensation, Energy & Infrastructure, Environment & Climate Change, Funds & Investment Management, Intellectual Property, International Commercial & Trade, Investigations, Compliance & Ethics, Mergers & Acquisitions, Private Equity, Real Estate, Restructuring & Insolvency, Sustainability, ESG, Tax',
       'Banking, finance, Commodities, shipping, Corporate, commercial transactions, Data privacy, cybersecurity, digital assets, Energy, resources, Hospitality, leisure, Infrastructure development, construction, International arbitration, Mergers, acquisitions, Private equity, Public-private partnerships, Real estate',
       'general advisory, regulatory compliance,  real estate operations, Disputes, Sanctions, Finance, M&A',
       'Finance & Banking , Litigation & Dispute Resolution, Corporate & Securities, Specialized & Industry Sectors',
       'Economic Sanctions & Export Controls, Banking & Private Credit, Fund Finance, Hybrid Capital, Investment Funds, Islamic Finance, Private Equity Finance, Project Development & Finance, Structured Finance, Sustainable Finance, Mergers & Acquisitions, Mergers & Acquisitions Litigation, Securities, M&A Litigation',
       'Aviation, Banking & Finance, Banking & Financial Disputes, Capital Markets, China-Related Investment Dispute Resolution, Commercial & Corporate Disputes, Competition & Antitrust, Trade, Construction & Projects, Corporate Commercial, Corporate Real Estate, Data & Digital Economy, Employment, Energy & Resources, Entertainment & Media, Financial Institutions, Foreign Investment Approvals, Fraud, Asset Recovery & Investigations, Funds & Investment Management, Gaming & Gambling, Hospitality, Insurance & Reinsurance, Intellectual Property, International Arbitration, Legal Basix, Medical, Healthcare & Life Sciences, Mergers & Acquisitions, Private Client Disputes, Private Wealth, Project Finance, Restructuring & Insolvency, Shipping & International Trade, Sports, Sustainability, Tax, Technology, Media & Telecommunications, White Collar Crime',
       'Banking & Finance, Capital Markets, China Practice, Competition & Foreign Investment Review, Construction & Engineering, Corporate & Commercial, Corporate Real Estate, Corporate Regulatory & Compliance, Corporate Services, Cybersecurity & Data Protection, Employment, Health & Safety, Energy, Infrastructure & Projects, English Law Practice, ESG & Public Policy, Financial Regulatory & Compliance, Fintech, Healthcare, Life Sciences & Pharmaceuticals, India Practice, Indonesia Practice, Intellectual Property, International Arbitration, International Trade, Investment Funds, Islamic Finance, Johor-Singapore Special Economic Zone Desk, Litigation, Maritime & Aviation, Mergers & Acquisitions, Private Equity, Private Wealth, Real Estate Investment Trusts, Restructuring & Insolvency, Tax, Technology & Corporate Intellectual Property, Technology Disputes, Technology, Media & Telecommunications, Venture Capital, White Collar & Investigations',
       'Arbitration, Artificial Intelligence, Digital Trust, Asset Recovery, Banking & Finance, Blockchain & Digital Assets, Business Establishment, Capital Markets, Commercial Litigation, Competition Law & Regulatory Practice, Competition Law Practice , Construction & Engineering, Corporate Litigation, Corporate/M&A, Corporate Restructuring & Workouts, Corporate Secretarial, Immigration, Process Agent Services , Crime, Data Protection, Privacy, Cybersecurity, Drew Data Protection & Cybersecurity Academy, Defamation, Employment, Environmental, Social & Governance, Financial Services Regulation, Insurance, Intellectual Property, International Arbitration, International Trade, Investigations, Investment Funds, Mediation, Medical Negligence, Private Client Disputes, Private Clients – Family Offices, Trusts, Immigration, Projects, Energy & Infrastructure , Projects, Energy & Infrastructure , Public International Law, Real Estate, Shipping, SICC Expertise, Strategy & Transactions, Tax, Wills, Probate, Estate Administration',
       'Corporate & Financial services, Intellectual property, technology & data, international practices, litigation & dispute resolution, regulatory, senior counsel, specialized practices, tax',
       'Banking & Finance, commercial disputes, commodities, corporate M&A, employment,  intellectual property, shipping',
       'arbitration, commercial litigation, restructuring & insolvency, power projects / EPC / marine construction, commodities trading / transport & finance, fraud / investigations / asset recovery, blockchain & digital assets, esg & carbon credits',
       'Banking & Financial Services, Commercial & Contract, Confidentiality, Corporate Restructuring & Insolvency, Corporate Shareholder & Partnerships, Defamation & Reputation Management, Employment & Labour, Energy & Natural Resources, Fraud Conspiracy & Unjust Enrichment, Medical Negligence & Misconduct, Property & Tenancy, Wealth Inheritance & Probate',
       'Shipping, International Trade & Logistics, Dispute Resolution, Conveyancing & Real Estate, Corporate & Commercial, Construction & Infrastructure, Regulatory & Compliance, Corporate Secretarial Services',
       'Banking & Finance, Capital Markets, Competition & Antitrust, Construction, Corporate, Corporate Real Estate, Employment, Energy, Franchising & Distribution, Infrastructure & PPP, Insurance, International Arbitration, Intellectual Property & Technology, Islamic Finance, Life Sciences, Litigation & Dispute Resolution, Mergers & Acquisitions, Privacy & Cybersecurity, Private Equity, Restructuring, Insolvency & Bankruptcy, Tax, Trade, WTO & Customs, Transportation, Trusts, Estates & Wealth Preservation, Venture Technology & Emerging Growth Companies, White Collar & Government Investigations',
       'Litigation & Dispute Resolution, International Arbitration, Fraud & Asset Recovery, Restructuring & Insolvency, International Trade, Shipping, Insurance & Reinsurance, Oil & Gas, Sanctions & Regulatory Compliance, Investigations, India Practice',
       'corporate & commercial, disputes, FinTech, restructuring & insolvency, maritime & shipping, real estate',
       'Asset & Wealth Management, Banking & Finance, Capital Markets, Construction & Projects, Corporate Commercial, Corporate Governance, Corporate Real Estate, Employment, Energy & Natural Resources, Environmental, Social, Governance, Financial Services Regulatory, Intellectual Property & Technology, International Arbitration, Litigation & Dispute Resolution, Mergers & Acquisitions, Private Equity & Venture Capital, Private Wealth, Restructuring & Insolvency, Shipping & Commodities, Technology, Media & Telecommunications',
       'M&A, dispute resolution, international arbitration, real estate, construction, employment',
       'Asset finance, banking & finance, capital markets, corporate, criminal & regulatory offenses, data protection, dispute resolution, employment, financial services regulation, maritime & international trade, M&A, private wealth, restructuring & insolvency, technology, white collar crime & investigations',
       'Shipping & Admiralty, Trade & Commodities, Corporate & Commercial, Dispute Resolution: Litigation, Arbitration & Mediation',
       'Admiralty, Shipping Law, Arbitration, Banking, Finance And Securities Law, Bankruptcy, Insolvency Law, Civil, Commercial Litigation, Conveyancing, Property Law, Criminal Law, Employment Law, Family Law, Insurance Law, Mediation, Wills, Probate And Administration Of Estate, Workers’ Compensation Claims',
       'charterparties, commodities coal, oil & gas, ship build & repair, maritime mediators',
       'Counsel Practice , Arbitrator Practice',
       'arbitration & mediation, banking & finance, commercial & corporate litigation, corporate & corporate secretarial,  international trade & commodities, shipping & admiralty law, real estate, conveyancing & estate planning, restructuring & insolvency',
       'International Commercial Arbitration',
       'Arbitration, Banking, Construction, Corporate & Commercial, Digital, Technology, Data Privacy, Employment & Immigration Law, Estate Planning & Trusts, Intellectual Property, Litigation, Real Estate & Conveyancing, Restructuring & Insolvency',
       'International Arbitration, Corporate & Commercial Litigation, Restructuring & Insolvency, Construction, Infrastructure & Energy, Fraud & Asset Recovery, Investigations, Regulatory Affairs, SICC Expertise, Technology Disputes, Private Client Practice',
       'dispute resolution',
       'shipping, international trade, international arbitration, commercial litigation, insurance, criminal law, corporate, ship finance & escrow services',
       'Dispute resolution, corporate, family, private wealth, criminal law',
       'Commercial Litigation, International Arbitration, Shipping & Commodities, Building & Construction, Restructuring & Insolvency, Family & Private Clients, Employment Law, Corporate Advice, Fintech & Cryptocurrency, Business Formation',
       'Bankruptcy & Commercial Restructuring, Competition, Corporate & Securities, Energy & Natural Resources, Finance, Information Technology, Privacy & Data Security, Insurance Litigation, Intellectual Property, International Trade, Labour & Employment, Life Sciences, Litigation & Dispute Resolution, Real Estate, Shipping'],
      dtype=object)

In [42]:
import re

# Standardized categories with keyword triggers (checked via substring match, case-insensitive)
category_keywords = {
    'Corporate & M&A': ['corporate', 'm&a', 'mergers', 'acquisitions', 'corporate/m&a', 'corporate & commercial',
                         'commercial & corporate', 'corporate commercial', 'business establishment',
                         'corporate secretarial', 'corporate services', 'corporate governance', 'commercial'],
    'Banking & Finance': ['banking', 'finance', 'financial services', 'project finance', 'structured finance',
                           'fund finance', 'hybrid capital', 'sustainable finance', 'asset finance', 'ship finance',
                           'securities law', 'financial institutions'],
    'Capital Markets': ['capital markets'],
    'Private Equity & Venture Capital': ['private equity', 'venture capital', 'venture technology'],
    'Funds & Investment Management': ['investment funds', 'funds & investment', 'asset & wealth management',
                                       'fund finance'],
    'Islamic Finance': ['islamic finance'],
    'Dispute Resolution & Litigation': ['dispute', 'litigation', 'litigations'],
    'International Arbitration': ['arbitrator','arbitration', 'mediation', 'mediators'],
    'Restructuring & Insolvency': ['restructuring', 'insolvency', 'bankruptcy'],
    'Fraud, Investigations & White Collar': ['fraud', 'asset recovery', 'investigations', 'white collar', 'crime',
                                              'criminal law'],
    'Regulatory & Compliance': ['regulatory', 'compliance', 'sanctions', 'export controls', 'investigations, compliance',
                                 'financial regulatory'],
    'Competition & Antitrust': ['competition', 'antitrust'],
    'Real Estate & Construction': ['real estate', 'construction', 'conveyancing', 'property law', 'reits',
                                    'property & tenancy'],
    'Employment & Labor': ['employment', 'labour', 'labor', 'pensions', 'immigration', 'workers'],
    'Intellectual Property': ['intellectual property', 'trademark', 'patent'],
    'Tax': ['tax'],
    'Shipping & Maritime': ['shipping', 'maritime', 'admiralty', 'ship build', 'ship repair', 'charterparties'],
    'International Trade & Commodities': ['trade', 'commodities', 'wto', 'customs', 'offshore'],
    'Energy & Infrastructure': ['energy', 'infrastructure', 'natural resources', 'oil & gas', 'renewables',
                                 'power projects', 'epc', 'projects'],
    'Private Wealth & Estate Planning': ['private wealth', 'private client', 'wills', 'probate', 'estate',
                                          'trusts', 'wealth inheritance', 'family offices'],
    'Family Law': ['family law', 'family,'],
    'Technology, Data & Cybersecurity': ['technology', 'data', 'cybersecurity', 'privacy', 'digital', 'fintech',
                                          'blockchain', 'digital assets', 'artificial intelligence', 'ai,'],
    'Insurance': ['insurance', 'reinsurance'],
    'Healthcare & Life Sciences': ['healthcare', 'life sciences', 'medical', 'pharmaceuticals', 'medical negligence'],
    'Aviation': ['aviation'],
    'ESG & Sustainability': ['esg', 'sustainability', 'environmental, social', 'carbon credits', 'environment & climate'],
    'Hospitality & Leisure': ['hospitality', 'leisure', 'gaming', 'gambling', 'sports'],
    'Entertainment & Media': ['entertainment', 'media', 'telecommunications'],
    'Defamation & Reputation': ['defamation', 'reputation'],
}

def standardize_practice_areas(raw_string):
    # split into rough tokens on commas, but keep '&' groupings intact by lowering first
    text = raw_string.lower()
    matched = []
    for category, keywords in category_keywords.items():
        for kw in keywords:
            if kw in text:
                matched.append(category)
                break  # only add category once
    # preserve a stable, de-duplicated order
    seen = set()
    ordered = []
    for m in matched:
        if m not in seen:
            seen.add(m)
            ordered.append(m)
    return ordered

# Apply to your unique values array (replace `values` with your actual array/column)
practice_area_map = {}
for val in p2["Practice Areas"].unique():  # `values` = your array of unique strings
    practice_area_map[val] = standardize_practice_areas(val)

# Apply to the actual column
p2['Practice Areas (Standardized)'] = p2['Practice Areas'].apply(standardize_practice_areas)

# Convert list to comma-separated string
p2['Practice Areas (Standardized)'] = p2['Practice Areas (Standardized)'].apply(
    lambda x: ', '.join(x) if isinstance(x, list) else x
)

# Flag unmatched rows BEFORE overwriting (use the list output, empty list = no match)
no_match = p2[p2['Practice Areas (Standardized)'].apply(len) == 0]['Practice Areas'].unique()
if len(no_match) > 0:
    print(f"WARNING - {len(no_match)} values matched no category:")
    for v in no_match:
        print(f"  - {v}")

        
p2['Practice Areas'] = p2["Practice Areas (Standardized)"]

In [43]:
p2 = p2.drop(columns=["Practice Areas (Standardized)"])

In [44]:
p2['Practice Areas'].unique()

<StringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'Dispute Resolution & Litigation, Regulatory & Compliance',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, Regulatory & Compliance',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, Regulatory & Compliance, Real Estate & Construction, Employment & Labor',
                                                                                                                                                                                                                                                                 'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, Fraud, Investigations & White Collar, Regulatory & Compliance, Real Estate & Construction, Employment & Labor, Intellectual Property, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, Insurance',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Corporate & M&A, Banking & Finance, Capital Markets, Dispute Resolution & Litigation, Regulatory & Compliance, Competition & Antitrust',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               'Dispute Resolution & Litigation, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Insurance',
                                                                                                                                                                                                                                                                                                                'Corporate & M&A, Banking & Finance, Capital Markets, Private Equity & Venture Capital, Dispute Resolution & Litigation, Restructuring & Insolvency, Fraud, Investigations & White Collar, Real Estate & Construction, Employment & Labor, Intellectual Property, Energy & Infrastructure, Private Wealth & Estate Planning',
                                                                                                                               'Corporate & M&A, Banking & Finance, Capital Markets, Private Equity & Venture Capital, Funds & Investment Management, Dispute Resolution & Litigation, Restructuring & Insolvency, Fraud, Investigations & White Collar, Regulatory & Compliance, Competition & Antitrust, Real Estate & Construction, Employment & Labor, Intellectual Property, Tax, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, ESG & Sustainability',
                                                                                                                                                                                                                                                                                                                                   'Corporate & M&A, Banking & Finance, Private Equity & Venture Capital, International Arbitration, Real Estate & Construction, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, Hospitality & Leisure',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, Regulatory & Compliance, Real Estate & Construction, Private Wealth & Estate Planning',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Corporate & M&A, Banking & Finance, Private Equity & Venture Capital, Funds & Investment Management, Islamic Finance, Dispute Resolution & Litigation, Regulatory & Compliance',
                                           'Corporate & M&A, Banking & Finance, Capital Markets, Funds & Investment Management, Dispute Resolution & Litigation, International Arbitration, Restructuring & Insolvency, Fraud, Investigations & White Collar, Competition & Antitrust, Real Estate & Construction, Employment & Labor, Intellectual Property, Tax, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, Insurance, Healthcare & Life Sciences, Aviation, ESG & Sustainability, Hospitality & Leisure, Entertainment & Media',
 'Corporate & M&A, Banking & Finance, Capital Markets, Private Equity & Venture Capital, Funds & Investment Management, Islamic Finance, Dispute Resolution & Litigation, International Arbitration, Restructuring & Insolvency, Fraud, Investigations & White Collar, Regulatory & Compliance, Competition & Antitrust, Real Estate & Construction, Employment & Labor, Intellectual Property, Tax, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, Healthcare & Life Sciences, Aviation, ESG & Sustainability, Entertainment & Media',
                          'Corporate & M&A, Banking & Finance, Capital Markets, Funds & Investment Management, Dispute Resolution & Litigation, International Arbitration, Restructuring & Insolvency, Fraud, Investigations & White Collar, Regulatory & Compliance, Competition & Antitrust, Real Estate & Construction, Employment & Labor, Intellectual Property, Tax, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, Insurance, Healthcare & Life Sciences, ESG & Sustainability, Entertainment & Media, Defamation & Reputation',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, Regulatory & Compliance, Intellectual Property, Tax, Technology, Data & Cybersecurity',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, Employment & Labor, Intellectual Property, Shipping & Maritime, International Trade & Commodities',
                                                                                                                                                                                                                                                                                                                          'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, International Arbitration, Restructuring & Insolvency, Fraud, Investigations & White Collar, Real Estate & Construction, International Trade & Commodities, Energy & Infrastructure, Technology, Data & Cybersecurity, ESG & Sustainability',
                                                                                                                                                                                                                                                                                                                                                                      'Corporate & M&A, Banking & Finance, Restructuring & Insolvency, Fraud, Investigations & White Collar, Real Estate & Construction, Employment & Labor, Energy & Infrastructure, Private Wealth & Estate Planning, Healthcare & Life Sciences, Defamation & Reputation',
                                                                                                                                                                                                                                                                                                                                                                                                                  'Corporate & M&A, Dispute Resolution & Litigation, Regulatory & Compliance, Real Estate & Construction, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning',
                                                                                                                          'Corporate & M&A, Banking & Finance, Capital Markets, Private Equity & Venture Capital, Islamic Finance, Dispute Resolution & Litigation, International Arbitration, Restructuring & Insolvency, Fraud, Investigations & White Collar, Competition & Antitrust, Real Estate & Construction, Employment & Labor, Intellectual Property, Tax, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, Insurance, Healthcare & Life Sciences',
                                                                                                                                                                                                                                                                                                                                                                                         'Dispute Resolution & Litigation, International Arbitration, Restructuring & Insolvency, Fraud, Investigations & White Collar, Regulatory & Compliance, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Insurance',
                                                                                                                                                                                                                                                                                                                                                                                                                                         'Corporate & M&A, Dispute Resolution & Litigation, Restructuring & Insolvency, Real Estate & Construction, Shipping & Maritime, Private Wealth & Estate Planning, Technology, Data & Cybersecurity',
                                                                                                                            'Corporate & M&A, Banking & Finance, Capital Markets, Private Equity & Venture Capital, Funds & Investment Management, Dispute Resolution & Litigation, International Arbitration, Restructuring & Insolvency, Regulatory & Compliance, Real Estate & Construction, Employment & Labor, Intellectual Property, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, ESG & Sustainability, Entertainment & Media',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'Corporate & M&A, Dispute Resolution & Litigation, International Arbitration, Real Estate & Construction, Employment & Labor, Private Wealth & Estate Planning',
                                                                                                                                                                                                                                                                                                           'Corporate & M&A, Banking & Finance, Capital Markets, Dispute Resolution & Litigation, Restructuring & Insolvency, Fraud, Investigations & White Collar, Regulatory & Compliance, Employment & Labor, Shipping & Maritime, International Trade & Commodities, Private Wealth & Estate Planning, Technology, Data & Cybersecurity',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Corporate & M&A, Dispute Resolution & Litigation, International Arbitration, Shipping & Maritime, International Trade & Commodities, Entertainment & Media',
                                                                                                                                                                                                                                                                                                                     'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, International Arbitration, Restructuring & Insolvency, Fraud, Investigations & White Collar, Real Estate & Construction, Employment & Labor, Shipping & Maritime, Private Wealth & Estate Planning, Family Law, Insurance, Entertainment & Media',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'International Arbitration, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Entertainment & Media',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'International Arbitration',
                                                                                                                                                                                                                                                                                                                                                                   'Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, International Arbitration, Restructuring & Insolvency, Real Estate & Construction, Shipping & Maritime, International Trade & Commodities, Private Wealth & Estate Planning, Entertainment & Media',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Corporate & M&A, International Arbitration',

In [45]:
p2.columns

Index(['Firm Name', 'Type (Intl / Local)', 'Office Location(s) in APAC',
       'Practice Areas', 'Known Client Base', 'Notable Cases / Disputes',
       'Notes'],
      dtype='str')

In [46]:
# known client base might include companies that are restructured or liquidated or something like that,
# or companies that are unclear whether they are not commodity trader or maritime shipping,
# or companies that are not located in singapore, or companies with hq abroad, or companies not listed in geographic scope of the project
# source verification are inconsistent
p2['Known Client Base'] = p2['Known Client Base'].str.replace(r'\s+,\s*', ', ', regex=True)

# turn every client into a list of strings
def string_to_listOfStr(clients):
    if not isinstance(clients, str) or not clients.strip():  # <- guard for NaN/empty, unrelated to URLs
        return clients
    else:
        final_clients = []
        clients = re.split(r',\s*(?![^()]*\))', clients) 
        # split commas that are not inside (). , followed by \s* >=0 space and the condition to NOT split (?![]) condition where any character [^()]* follows by \)
        # means .split only if the comma does not meet the condition. condition to not meet is [^()]*\)
        for name in clients:
            final_clients.append(name.strip()) #name.strip() removes the first whitespace
        return final_clients
    
# p2["Known Client Base"] = p2["Known Client Base"].apply(string_to_listOfStr)
p2["Known Client Base"] = p2["Known Client Base"].apply(
    lambda x: ", ".join(x) if isinstance(x, list) else x
)

p2['Known Client Base']

1     Uniper Global Commodities SE, AM Green Ammonia (India) Pvt. Ltd, China Merchants Energy Shipping, Sinopec, Crescent Petroleum, Crescent Gas, ARC Resources Ltd. (ARC), SGO: a UK election technology company, Eurobank, Trifylli Iliaki S.M.S.A.,  DRW,  Art-Invest Real Estate, Avery Healthcare, Vendrix Inc., Beehive, UAE Creative Media Authority and Abu Dhabi Film Commission, Samsung Austin Semiconductor, Purdue Pharmacy, Federated Hermes, Santander Holdings USA, Perrigo Company, Roman Catholic Diocese of Rockville Center New York, J.M. Smith Corporation, Philips Healthcare,  Elevate Services, Phoebe Energy S.M.S.A., PPC Renewables S.M.S.A., Spin Master UK Limited (reedsmith.com)
2                                                                                                                                                                                                                                                                                                      BGN Energy, Sumitomo Mitsui Banking Corporation,  the Republic of South Africa, the Gunvor Group, Northumbrian Water, Uniserve, Technip Energie, Abu Dhabi Commercial Bank, Asertis, CAFI (Commodity & Freight Integrators DMCC), China Hanking Holdings Limited (China Hanking), Cosco Shipping Ports Limited (COSCO),  UBS Switzerland AG,  Al Seer Marine (ASM), Venetico Marine SA (chambers, hfw.com)
3                                                                                                                                                                                                                                                                                                                                                    Urban&Civic, TransactPay, Al Buhaira National Insurance Company (ABNIC), E D & F Man Capital Markets Ltd (MCM), Galliford Try, Welborne Land, Native Land Limited,  Lendlease Group, Citigroup, ThinCats, Community Pharmacy England,  Jaguar Land Rover, Erada Finance,  Pearl Infrastructure capital, Al Bawardi Enterprises, Suez Fortune Investments Ltd
4                                                                                                                                                                                                                                                                                                                                                               Bicycle Therapeutics, Trafigura, WindAcre Partnership, KFin Technologies,  National Bank of Fujairah PJSC, The Arab Energy Fund, Yellow Door Energy, ICICI Bank, BW Group, HSBC, Standard Chartered, ICBC Leasing, PSA International, Mitsui & Co., Olam International, ADM (perplexity + google, from standard chartered till adm by perplexity)
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Cerulean Winds, Vattenfall, HSBC UK, UCED, Maas Capital Shipping, Willow MezzCo, Heytesbury, Trafigura, Shell Energy Europe Limited (SEEL), JE Energy Ltd, BW Energy Holdings Pte Ltd (wfw.com), MRI Trading AG (google AI)
6                                                                                                                                                                                                                                                                                                                                                                     London Commodity Brokers Ltd.(vlex.co.uk),Statoil ASA (gemini), Glory Bulk Carriers Pte Ltd. (hongkongmaritimehub.com),TCC Group (Tai Chong Cheang Shipping) (Google Ai), Seacon Shipping Group Holdings, Mur Shipping B.V.,Stena Bulk / CM P-Max (Gemini), Clearlake Shipping, Trafigura Group (Gemini), Permasteelisa Gartner HK (gemini)
7                                                                                                                                                                                                                                                                                                                                                                                                                                                Energy Transfer (gemini),Louis Dreyfus Company (LDC) ( gemini), Nippon Yusen Kabushiki Kaisha (NYK Group),  Stena Group, Costamare Inc., P&O Ferries, Carnival Corporation, Dubai Ports World, Roi Tinto, DVB (legal500), P&O North Sea Ferries Ltd (perplexity)
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Mondelez Global, Veritas,  Olink Holding AB, Pacific Gas & Electric, Physicians Realty Trust, Cummins Inc, Numab Therapeutics, Premier Assurance Group, Acorda, Regent, Vesta Advisors, Shell Singapore Pte. Ltd., Bunge Limited (google ai)
9                                                                                                                                                                                                                                                                                                                                                                                                                China National Petroleum Corporation (CNPC), China Petroleum Technology & Development Corporation (CPTDC), Stellar Chartering & Brokerage Inc., T.K. Boesen A/S, Orient Shipping (Rotterdam) B.V., AIC Ltd, Marine Pilot Ltd, Shackerley Holdings Ltd, Itochu Europe PLC, Cedar Fair (google ai)
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Reabold Resources (chamber), Star Academies  (chamber),Fox Brothers Holdings (chamber), CPM UK (chamber), Extrude Hone(chamber), moby group(gemini), Socar Trading Middle East DMCC (google ai),P&I Clubs (google ai)
11                                                                                                                                                                                                                                                                                                                                                                                     Trafigura, OQ Trading (OQT), Glencore plc, Shell & Shell Western Supply and Trading, TotalEnergies / TOTAL, PetroChina & CNOOC, JERA & Pavilion Energy, PETRONAS (Marine & LNG Transport), Deutsche Energy Terminal GmbH (DET), Hong Kong LNG Terminal Limited (HKLTL), Mitsui & Osaka Gas, Excelerate Energy (perplexity)
12                                                                                                                                                                                                                                                                                                                                                                                                                        Michelin, Revolution Medicines, Inc., AMD (Advanced Micro Devices, Inc.) (chambers), Riverstone Holdings LLC (https://www.lw.com/ & Gemini), Delfin Midstream (https://www.lw.com/ ), Ocean Network Express Pte. Ltd. (ONE)(https://www.lw.com/ ), Macquarie Group (Macquarie) (gemini)
14                                                                                                                                                                                                                                                                           Hanjin Shipping, Sumifru Singapore Pte Ltd., COSCO Shipping Specialized Carriers Co, Ltd., Sinopec International (Singapore) Pte Ltd, Pacific Richfield Marine, CH Offshore Limited, Chuan Hup Holdings, Miclyn Express Offshore Limited, Neptune Associated Shipping Pte Ltd, Neptune Associated Shipping Pte Ltd, Pacific Shipping Trust, PT Rig Tenders Indonesia, Searights Maritime Services Group (gemini + rajahtannasia.com)
15                                                                                                                                                                                                                                                                                                                                                                                                            PT Commodities & Energy Resources, JSW International Tradecorp Pte Ltd (JSW), Telemedia Global Data Centres, BTS Tankers Pte Ltd, Natixis Singapore Branch, Hai Jiang 1401 Pte Ltd, DBS Bank, United Overseas Bank, Oversea-Chinese Banking, World Bank (chambers, google ai, allenandgledhill.com)
16                                                                                                                                                                                                                            Daelim Industrial Co., Ltd., Resources Prima Group Ltd, CVC Capital Partners (CVC), PT Berlian Laju Tanker Tbk, Metro Holdings Limited, Asia Pulp & Paper group of companies (APP Group), Brightoil Petroleum (S'pore) Pte. Ltd. (BOPS), Razer, Tencent, Eagle Hospitality Trust, ST Marine Ltd, Shandong Shipping Corporation, O.W. Bunker Far East (Pte) Ltd, Dynamic Oil Trading (Singapore) Pte Ltd, Hin Leong Trading, Hilal Denizcilik (drewnpaier.com, google ai, chambers)
17                                                                                                                                                                                                                                                                                                                                                                                                                                                 Nuance Pharma, First Resources, CC Capital, First Sponsor Group, China Railway Tunnel Group's Singapore branch, BNP Paribas Wealth Management, Meta Platforms Inc, KKR, DBS, PDV Marina, Ocean Tankers Pte Ltd, Seatrium, Hin Leong Trading (google, chambers)
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         China Base Group Limited, United Overseas Bank, Maersk Tankers, Straits Bunkering Pte Ltd, Great Asia Maritime Limited, Quaestus Capital Pte. Ltd., Nanjing Tanker Corporation (Subsidiaries) (google)
19                                                                                                                                                                                                                                                                                                                                                                                                                      Majestica Enterprises, Avani Resources Pte. Ltd., Alvari Pte. Ltd., InterChem Pte. Ltd., Phoenix Group, Somap International Pte. Ltd., QBE Insurance (Singapore) Pte Ltd, Hin Leong Trading, Pavilion Gas, Pertamina, PETRONAS, Mitsui Asia-Pacific Pte Ltd (gemini + blackstonegold.com)
20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     PT First Media Tbk (Lippo Group), BAFCO Singapore Pte. Ltd., The Singapore Medical Council, Ngng Pte Ltd, PJSC Power Machines, BASF Intertrade AG (gemini)
21                                                                                                                                                                                                                                                                                                                                                                                                           Petrobras, Myanmar Five Star Line Company Limited (MFSL), Paragon Shipping, Consortium of shipowners, Hin Leong Trading (Pte) Ltd, Xihe Holdings Pte Ltd, Uni Petroleum Pte Ltd, Myanmar National Airlines Company Limited (MNA), Kylen Resources, FTI Consulting (Singapore) Pte. Ltd. (perplexity)
22                                                                                                                                                                                                                                                                                                                                                         Bulk Trident Shipping Ltd, WEM-3 Pte Ltd, WEM-4 Pte Ltd, WEM-5 Pte Ltd, WEM-6 Pte Ltd, INEOS Styrolution Korea Ltd, UniCredit Bank AG SG branch, Bank of China Limited, Shenzhen Branch, Oversea-Chinese Banking Corporation (OCBC), Boustead Projects Limited, Thomson Medical Group (TMG), Templewater Hong Kong Limited, ZeroNorth A/S (perplexity)
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                     the International Oil Pollution Compensation Funds, Taconic Capital Advisors, Winson Oil Trading Pte Ltd, OCBC Bank, ECOBULK SHIPPING INC.), Energe Asia Pte Ltd, Aastar Trading Pte Ltd, Black Swan Petroleum DMCC (perplexity, legal500)
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Evergreen Marine Corporation, Mercuria Energy Group (legal500), Louis Dreyfus Company Asia, Rotating Offshore Solutions, Skuld P&I Club, Pacific Distribution Investment Company (perplexity)
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       The Hongkong and Shanghai Banking Corporation (HSBC), POS Maritime VX SA, Standard Chartered Bank (Singapore) Limited (SCB) (perplexity)
26                                                                                                                                                                                                                                                                                                                                                                                    Century Holding Company Limited, Nan Chiau Maritime, Halcyon Agri Corporation Limited, DHL, Seraya Energy, KPMG, Mizuho Bank, Perrenial Real Estate Holdings, Ho Lee construction, WestBridge Ventures II Investment Holdings, Luckin Coffee, Smart Glove, Hyundai Engineering & Construction, Asiana Airlines (perplexity)
27                                                                                                                                                                                                                                                                                                                                                                                            Standard Chartered Bank, the Hongkong and Shanghai Banking Corporation, HJ Shipbuilding & Construction Co., Ltd., Oldendorff Carriers GmbH & Co. KG, ING Bank, StraitNZ, X-Press Feeders, Hafnia Limited, Brightoil Petroleum (Singapore) Pte Ltd, BW LPG Limited, DeepOcean APAC AS (legal500, perplexity, gemini)
28                                                                                                                                                                                                                                                                                                                                                                   Atlantic Navigation Holdings (Singapore) Ltd, Fairmacs Shipping & Transport Services Pte Ltd, Marco Polo Shipping Company Pte Ltd, Royal Global Exports Pte Ltd, ASL Marine Group, A.P. Moller-Maersk, Asian Infrastructure Ltd, U-Hin Manufacturing Pte Ltd, International Coatings Pte Ltd, Heroic Warrior Inc (dennismathiew.com, gemini)
29                                                                                                                                                                                                                                                                     Louis Dreyfus Asia Pte Ltd, Sunlight Mercantile Pte Ltd, Bhavani Stores Pte Ltd, Amrose Singapore Pte Ltd, Trans-Tec / World Fuels Group, A.P. Moller-Maersk / Maersk Line, Saigon Shipping Company, Ever Lucky Shipping Company Limited, Admiral Chartering Ltd, Transfield Shipping Inc. Panama, Pacific Integrated Logistics Pte Ltd, Prestige Marine Services Pte Ltd, Wijsmuller Offshore Terminal Towage (Far East) Pte Ltd (gemini)

In [47]:
# check 'Notable Cases / Disputes'

# co. ltd or co, ltd or co., ltd to co ltd. natixis, singapore branch becomes natixis singapore branch.
# ltd. or ltd, to ltd
# pte. ot pte, to pte
# duncan, to duncan and
p2['Notable Cases / Disputes'] = p2['Notable Cases / Disputes'].str.replace(r'\b(co|ltd|pte|inc|corp)[.,]+', r'\1', regex=True, case=False)
p2['Notable Cases / Disputes'] = p2['Notable Cases / Disputes'].str.replace(r',\s*(singapore branch)', r' \1', regex=True, case=False)
p2['Notable Cases / Disputes'] = p2['Notable Cases / Disputes'].str.replace(r'\bDuncan,\s*', r'Duncan and ', regex=True, case=False)

# turn every case into an item inside a list
def string_to_listOfStr(cases):
    if (
        not isinstance(cases, str) or not cases.strip()
    ):  # <- guard for NaN/empty, unrelated to URLs
        return cases
    else:
        final_cases = []
        cases = re.split(r",\s*(?![^()]*\))", cases)
        # split commas that are not inside (). , followed by \s* >=0 space and the condition to NOT split (?![]) condition where any character [^()]* follows by \)
        # means .split only if the comma does not meet the condition. condition to not meet is [^()]*\)
        for name in cases:
            final_cases.append(
                name.strip()
            )  # name.strip() removes the first whitespace
        return final_cases

# p2['Notable Cases / Disputes'] = p2['Notable Cases / Disputes'].apply(string_to_listOfStr)
p2["Notable Cases / Disputes"] = p2["Notable Cases / Disputes"].apply(
    lambda x: ", ".join(x) if isinstance(x, list) else x
)
p2["Notable Cases / Disputes"]
# case label name (e.g. The {text}, The {text}) etc
# actual case name {text} v {text} etc. (many columns might appear even though it belongs to one {text} ex:COSCO Shipping Specialized Carriers Co, Ltd v PT OKI Pulp & Paper Mills and others [2023] SGHC 149)
# some case name {text} (Comm) etc
# some are literal descriptions (e.g. "Precedent setting FOSFA sale of goods arbitration (switzerland)", "Appealing the Refined Sugar Associations Arbitration Award (UK)") etc
# some case name {text} advises or advised or advising the {text}
# some case name are In re: {text}
# commas inside parenthesis are not to be split
# some case name is Re {text} ex: Re Brightoil Petroleum (S’pore) Pte Ltd [2022] SGHC 35
# some case name is {text} ex: $60 Million African Oil Project Arbitration (LCIA London)
# some case name is Case involving {text}
# some case name is Representing {text} ex: Representing Japanese ship owner Masao Mizobuchi (perplexity)
# some case name is acting for {text}
# some case naem is engaged by {text}
# some case name si advising on {text}
# in some case is In the matter of {text} or In re {text} or Re {text}
# some case name is dispute over {text} or dispute between {text}
# some case name is just {text} ex: PDV Marina Wind-Up (CV Shipping Liquidation)

1                                                                                                                                                                                                                                                 RTI Ltd v MUR Shipping BV [2024] UKSC 18, Sharp Corp Ltd v Viterra BV [2024] UKSC 14, The Aquafreedom [2024] EWHC 255 (Comm), The Ever Given – SMIT Salvage BV and Others v Luster Maritime SA [2024] EWCA Civ 260, Maersk Guiné-Bissau v Almar-Hum Bubacar Baldé [2024] EWHC 993 (Comm) (reedsmith.com)
2                                                                                                                                                                                                                                                                                                               The "Rena" Grounding, OW Bunker Bankruptcy, The "Prestige" Oil Spill, The "Ocean Victory" Case (https://www.studocu.com/en-gb/messages/question/5472340/what-are-some-famous-cases-that-were-advised-by-hfw-and-how-were-they-influential)
3                                                                                                                                         The 'Brillante Virtuoso' Case, Precedent setting FOSFA sale of goods arbitration (switzerland), Appealing the Refined Sugar Associations Arbitration Award (UK), Collision of VLCC "ALEXANDRA 1" and "EVER SMART" (UK), Penglai 19-3 Oil Field Pollution (China/USA),  COSCO BUSAN Allision with San Francisco-Oakland Bay Bridge (USA), Agarwal Coal High Court Appeal (UK) (claude + clydeco.com + perplexity)
4                                                                                                                                                                                                            former Yukos Oil Company shareholders v The Russian Federation, Trafigura Pte Ltd & Anor v Prateek Gupta & Ors [2026] EWHC 159 (Comm), SLB and others v PAK and others [2026] EWHC 449 (Comm), GAIL (India) Limited v SEFE Marketing & Trading Singapore Pte Limited, Narciso v Nash (ARB 009/2024) (google AI + google  & news + claude AI )
5                                                                                                                                                      The merger between Hapag-Lloyd and the United Arab Shipping Company (UASC), WFW advises Guinea as US$24bn Simandou African mega-project closes, Niko Resources (Bangladesh) Ltd v. Bangladesh Petroleum Exploration & Production Company Limited ("Bapex") and Bangladesh Oil Gas and Mineral Corporation ("Petrobangla"), MRI Trading AG v Erdenet Mining Corp LLC (2013) (perplexity + google AI)
6                                                                                                                                                                                                                                                                                                                     Global Coal Ltd v London Commodity Brokers (vlex.couk),Statoil ASA v Louis Dreyfus Energy Services LP (The Harriette N)(ipsaloquitur.com ), Priyanka Shipping Limited v Glory Bulk Carriers Pte Ltd [2019] EWHC 2804 (Comm) (Gemini)
7                                                                                                        Suez Fortune Investments Ltd v Talbot(gemini), PD Teesport Ltd v. P&O North Sea Ferries Ltd — Force Majeure / Ferry Operator Dispute (2022–2023), Carnival Corporation v. Fincantieri S.p.A — Shipbuilding Contract / Breach of Guarantee (Ongoing as of 2024–2025), Shell UK v. Greenpeace UK — FPSO Boarding Dispute (2023–2024), KfW IPEX-Bank v. World Dream Limited ("The World Dream") — Ship Mortgage Enforcement (2022–2024) (perplexity)
8                                                                                                                                                                                                                                                                                         Anaklia Development Consortium (ADC) and Bob Meijer v. Georgia (ICC & ICSID parallel claims), Lakatamia Shipping Co Ltd v Su & Ors,  Lehram Capital Investments Ltd v. Baker McKenzie, Anaklia Development Consortium (ADC) v. Government of Georgia (google ai)
9                                                                                                                             LG Caltex v CNPC, Triad Shipping Co v Stellar Chartering & Brokerage Inc (The "Island Archon") [1994] 2 Lloyd's Rep 227, Merit Shipping Co Inc v T.K. Boesen A/S (The "Goodpal") [2000] 1 Lloyd's Rep 638, André & Cie S.A. v Orient Shipping (Rotterdam) B.V. (The "Laconian Confidence") [1997] 1 Lloyd's Rep 139, AIC Ltd v ITS Testing Services (UK) Ltd (The "Kriti Palm") [2006] EWCA Civ 1601 (squirepattonboggs.com)
10                                                                                                                                                                                                                                                                               SY Roro 1 Pte Ltd and another v Onorato Armatori S.R.L. and others [2024] EWHC 611 (Comm) (google AI), Trafigura PTE Ltd & Anor v Gupta & Ors [2026] EWHC 159 (Comm) (hilldickinson.com/our-view/articles/commodity-trader-successful-in-fraudulent-nickel-trade-claims/)
11                                                                                                                                                                                                                                                                                                    Clearlake Shipping Pte Ltd v. Guvnor Shipping & Others, Aabar Holdings v. Glencore plc, The "Reluctant Ship Owner" Mortgages Enforcement Action, In re: Singamas and Container Cartel Litigation, In re: Glencore PLC SFO Investigation (perplexity)
12    Latham & Watkins Advises Riverstone in Acquisition of Trailstone by Engelhart Commodities Trading Partners ( https://www.lw.com/ & Gemini), Latham & Watkins Advises Delfin Midstream on First Offshore Floating Vessel LNG Export Facility in the US (https://www.lw.com/ & Gemini), Latham & Watkins Advised Ocean Network Express in the Completion of Atlas’ Going Private Transaction(https://www.lw.com/ & Gemini), Latham & Watkins Advises Macquarie on 15-Year LNG Sale and Purchase Agreement With AMIGO LNG(https://www.lw.com/ & Gemini)
14                                                                                                             The Mount Apo [2019] 4 SLR 909, BWG v BWF [2020] 1 SLR 1296, PT Adidaya Energy Mandiri v MS First Capital Insurance Ltd [2022] 4 SLR 371, Sumifru Singapore Pte Ltd v Felix Santos Ishizuka and others [2022] SGHC 14, COSCO Shipping Specialized Carriers Co Ltd v PT OKI Pulp & Paper Mills and others [2023] SGHC 149, Sinopec International (Singapore) Pte Ltd v Bank of Communications Co Ltd [2024] 3 SLR 476 (sg.rajahtannasia.com)
15                                                                                                                            Public Prosecutor v. Captain George Vakirtzis, Public Prosecutor v. Captain Janusz Czubak, Five Ocean Corp v Cingler Ship Pte Ltd (PT Commodities & Energy Resources, intervener) [2016] 1 SLR 1159, Valency International Pte Ltd v JSW International Tradecorp Pte Ltd & Ors, Natixis Singapore Branch v Lim Oon Kuin and Ors, Hai Jiang 1401 Pte Ltd v Singapore Technologies Marine Ltd (allenandgledhill.com, chambers)
16                                                                                                                                                                                                                        Suntech Power Holdings Co Ltd v GSF Capital Pte Ltd and Javier Romero, Ng Joo Soon v Dovechem Holdings Pte Ltd Re Brightoil Petroleum (S’pore) Pte Ltd [2022] SGHC 35, Voss Peer v APL Co Pte Ltd [2002] SGHC 81, Hyosung (HK) Ltd v Owners of the Ship or Vessel "Hilal I" [2000] SGHC 268 (drewnapier.com, googleai, chambers)
17                                                                                                                                                                                                                                                                                                                                                                     Timing Limited v Tay Toh Hin & Anor [2020] 5 SLR 974, Prime Shipping Corp v Public Prosecutor [2018] 4 SLR 795, Hin Leong Trading / Ocean Tankers Interpleader Proceedings (google)
18                                                                                                                                                                                                                                                                                                                                                                                  Public Prosecutor v Richard Ouwehand and Others, Orion Shipping and Trading Ltd v Great Asia Maritime Ltd Vasily Trubnikov v Evgeny Volosov [2025] HKCFI 1576 (google)
19                                                                                                                                                                                                                                                                                                                                    Marketlend Pty Ltd v QBE Insurance (Singapore) Pte Ltd Majestica Enterprises Ltd v Kams Singapore Pte Ltd $60 Million African Oil Project Arbitration (LCIA London), The Hin Leong Trading Collapse Fallout (gemini)
20                                                                                                                                                                                                                                                                                                                                                                            BASF Intertrade AG Singapore Branch v H&C S Holding Pte Ltd PetroVietnam v PJSC Power Machines, Teunis Eigenraam v Ngng Pte Ltd Vessel Charterer Winding-Up Defense (gemini)
21                                                                                                  The “Miracle Hope” [2020] SGHCR 3; BNP Paribas v Bandung Shipping Pte Ltd (Shweta International Pte Ltd and another, third parties) [2003] 3 SLR(R) 611; [2003] SGHC 111; Freight Connect (S) Pte Ltd v Paragon Shipping Pte Ltd [2015] SGCA 37; Zim Integrated Shipping Services Ltd and others v Dafni Igal and others [2010] SGCA 45; The “Rainbow Star” [2011] 3 SLR 1; [2011] SGHC 35 (jtjb.com), Paragon Shipping v Freight Connect (perplexity)
22                                                                                                                                                                                                                                                                                                                     Government of Sri Lanka v Shipowners of Vessel X-Press Pearl and associated persons, Fastfreight Pte Ltd v Bulk Trident Shipping Ltd Case involving vessel GULF DEFFI, UniCredit Bank AG v Hin Leong Trading (Pte) Ltd (perplexity)
23                                                                                                                                                                                                                          The Miracle Hope, Standard Chartered Bank (Singapore) Ltd v Maersk Tankers Singapore Pte Ltd (Winson Oil Trading Pte Ltd intervener) [2022] SGHC 242, The “STI Orchard” (Winson Oil Trading Pte Ltd intervener) [2022] SGHCR 6, he “Yue You 902” [2019] SGHC 106, The “Luna” and another appeal [2021] SGCA 84  (oonbazul.com)
24                                                                                                                                                                                                                                                                               The Owner and/or Demise Charterer of the Vessel “Marine Honour” v. The Owner and/or Demise Charterer of the Vessel “Vox Maxima” and Others (gemini), Acting for owners of SOV Southern Star (a DP3 vessel), Representing Japanese ship owner Masao Mizobuchi (perplexity)
25                                                                                                                                                                                Duncan and Cameron Lindsay and another v Diablo Fortune Inc and another matter SGHC 172, Winson Oil Trading Pte Ltd v Oversea-Chinese Banking Corporation and Standard Chartered Bank (Singapore) Limited SGHC 220, Claim of more than USD80 million against OK Lim and his children, founder/ex-directors, and former senior employee of Hin Leong Trading (perplexity)
26                                                                                                                                                                                          Acting for Asiana Airlines in dispute with catering agent over arbitration agreements, Engaged by judicial managers in the liquidation of Nan Chiau Maritime, Advising on offshore shipping sector infrastructure financing deal (US$300 million), Representing client in dispute over nickel mine in Indonesia (Century Holding Company Limited) (perplexity)
27                                                                                                                                                                                                                                                                                                                        The "Brightoil Glory", In the matter of Coastal Oil Singapore Pte Ltd (In Liquidation), In re Varada Marine Pte Ltd ---, In the matter of Hin Leong Trading (Pte) Ltd and Winson Oil Trading v. Hin Leong Trading & Ors (gemini)
28                                                                                                                          Atlantic Navigation Holdings (Singapore) Ltd v Chang Yee Meng Malcolm and another [2021] SGHC 159, Marco Polo Shipping Co Pte Ltd v Fairmacs Shipping & Transport Services Pte Ltd [2015] 5 SLR 541, The “Emma Maersk” [2006] SGHC 180, Royal Global Exports Pte Ltd v Good Stream Co Ltd and anor [2004] 4 SLR(R) 247, The “ASL Power” [2003] 1 SLR(R) 545, The “Caraka Jaya Niaga III-11” [2021] SGHC 43 (dennismathiew.com)
29                                                                                                                  The "Kaminesan" (Three-Ship Collision), The "Asia Star" [2006] SGHC 115, The "Ching Ho" & "Noble Spirit" Container Losses, Pacific Integrated Logistics Pte Ltd v German Vernel International Freight Ltd [2007] 1 SLR 1017, The O.W. Bunker Collapse Litigation: Precious Shipping Public Company Ltd v OW Bunker Far East [2015] SGHC 187, Ever Lucky Shipping Company Limited v Sunlight Mercantile Pte Ltd [2003] SGHC 80 (gemini)
30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Unknown
31                                                                                                                                                                                                                                                                                                The US$168 Million LNG Non-Delivery Arbitration (ICC Singapore), The Concurrent Gas Production Arbitrations (SIAC Singapore), The US$3 Billion Upstream State Dispute (ICC), The European Multinational v. Asian Commodities Firm Dispute (ICC) (gemini)
32                                                                                                                                                                     The “August 8” [1980–1981] SLR 144 / [1982–1983] SLR 32 (Privy Council), The “Hung Vuong 2” [2001] 3 SLR 146, Faith Maritime Co Ltd v Feoso (Singapore) Pte Ltd & Another [2002] 4 SLR 716, The “Neptra Premier” [2002] 2 SLR 124, The “Patraikos 2” [2002] 4 SLR 232, Marina Offshore Pte Ltd v China Insurance Co (Singapore) Pte Ltd [2006] 1 SLR 800 (Court of Appeal) (gemini)
33                                                                                                                                                                                                                    Glencore International A.G. v. Republic of Colombia, dispute over the bulk purchase of physical hydrocarbon products by a Chinese entity, dispute between two major Saudi Arabian companies involving cross-border logistics, as price review dispute involving physical gas supply and off-take agreements across Asia (perplexity)
34                                                                                                                                                                                                                                                                                                                                                                                                                                     PDV Marina Wind-Up (CV Shipping Liquidation), Goldilocks Investment Co Ltd v Noble Group Ltd 5 SLR 425 (perplexity)
35                                                                                                                                                                                                                                                                                                       Re Hin Leong Trading (Pte) Ltd [2025] / [2026], Re GP Global APAC Pte Ltd [2024] / [2025], HSBC v Zenrock Commodities Trading Pte Ltd Alphard Maritime Ltd v Samson Maritime Ltd and Underwater Services Company Limited [2025] SGHC 154 (gemini)
36                                                                                                                                                                                                                                                                                                                                                                                                                                                                    The “Maersk Katalin” [2024] SGHC 282, CYE v CYF [2023] SGHC 275 (lvmlawchambers.com)
37                                                                                                                                                                                                                                                                                                                                                                           Argoglobal Underwriting Asia Pacific Pte Ltd and others v Oversea-Chinese Banking Corporation Limited SGCA 14, The “Sea Justice” SGCA 32, The “Tina I” 3 SLR 121 (perplexity)
38                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Unknown

In [48]:
# check notes
p2['Notes'] = p2['Notes'].str.strip()
p2["Notes"].unique()

array(['website: https://www.reedsmith.com/',
       'website: https://www.hfw.com/', '', 'https://www.wfw.com/',
       "Rosita Lau (Partner & Head of Shipping), Ince don't have  office in sg(gemini)",
       'bakermckenzie.com', 'squirepattonboggs.com',
       'https://www.hilldickinson.com/', 'https://www.mayerbrown.com/en',
       'https://www.lw.com/',
       'Rajah & Tann Sing apore LLP. https://sg.rajahtannasia.com/',
       'allenandgledhill.com', 'www.drewnapier.com',
       'https://www.wongpartnership.com/', 'https://www.helmsmanlaw.com/',
       'https://www.blackstonegold.com/', 'https://braddellbrothers.com/',
       'https://jtjb.com/',
       'Dentons Rodyk is part of Dentons ASEAN, the first global pan-ASEAN law firm. https://dentons.rodyk.com/en/office-details/singapore',
       'https://oonbazul.com/', 'https://www.pdlegal.com.sg/',
       'shooklin.com', 'https://www.tsmplaw.com/',
       'Virtus Law LLP is a member of the Stephenson Harwood (Singapore) Alliance. Focus is on five sectors:',
       'DennisMathiew has built a solid reputation in maritime and commercial law, services span across shipping, logistics, international trade, and oil & gas. https://www.dennismathiew.com/',
       'website not working.', 'https://dunbarlim.com/',
       'https://hhp.com.sg/',
       'She has experience in various commercial arbitration areas, including joint ventures, corporate sales, construction, energy contracts, and investment treaty disputes. https://www.judithgill.com/#answers-section',
       'https://pkw.com.sg/', 'https://www.providencelawasia.com/',
       'https://www.lvmlawchambers.com/', 'https://incisivelaw.com/',
       'https://www.damodaraong.com/', 'https://www.focuslawasia.com/',
       'https://www.resourcelawasia.com/'], dtype=object)

In [49]:
p2

                       Firm Name Type (Intl / Local)                                                                                                                         Office Location(s) in APAC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Practice Areas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Known Client Base                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Notable Cases / Disputes                                                                                                                                                                                                               Notes
1                     Reed Smith       International                                                                   10 Collyer Quay, #18-01 Ocean Financial Centre, Singapore 049315 (Reedsmith.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Dispute Resolution & Litigation, Regulatory & Compliance  Uniper Global Commodities SE, AM Green Ammonia (India) Pvt. Ltd, China Merchants Energy Shipping, Sinopec, Crescent Petroleum, Crescent Gas, ARC Resources Ltd. (ARC), SGO: a UK election technology company, Eurobank, Trifylli Iliaki S.M.S.A.,  DRW,  Art-Invest Real Estate, Avery Healthcare, Vendrix Inc., Beehive, UAE Creative Media Authority and Abu Dhabi Film Commission, Samsung Austin Semiconductor, Purdue Pharmacy, Federated Hermes, Santander Holdings USA, Perrigo Company, Roman Catholic Diocese of Rockville Center New York, J.M. Smith Corporation, Philips Healthcare,  Elevate Services, Phoebe Energy S.M.S.A., PPC Renewables S.M.S.A., Spin Master UK Limited (reedsmith.com)                                                                                                                                                                                                                                              RTI Ltd v MUR Shipping BV [2024] UKSC 18, Sharp Corp Ltd v Viterra BV [2024] UKSC 14, The Aquafreedom [2024] EWHC 255 (Comm), The Ever Given – SMIT Salvage BV and Others v Luster Maritime SA [2024] EWCA Civ 260, Maersk Guiné-Bissau v Almar-Hum Bubacar Baldé [2024] EWHC 993 (Comm) (reedsmith.com)                                                                                                                                                                                 website: https://www.reedsmith.com/
2    HFW (Holman Fenwick Willan)       International                                                                                    30 Raffles Place, #24-01, Bni Tower, Singapore 048622 (Hfw.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, Regulatory & Compliance                                                                                                                                                                                                                                                                                                   BGN Energy, Sumitomo Mitsui Banking Corporation,  the Republic of South Africa, the Gunvor Group, Northumbrian Water, Uniserve, Technip Energie, Abu Dhabi Commercial Bank, Asertis, CAFI (Commodity & Freight Integrators DMCC), China Hanking Holdings Limited (China Hanking), Cosco Shipping Ports Limited (COSCO),  UBS Switzerland AG,  Al Seer Marine (ASM), Venetico Marine SA (chambers, hfw.com)                                                                                                                                                                                                                                                                                                            The "Rena" Grounding, OW Bunker Bankruptcy, The "Prestige" Oil Spill, The "Ocean Victory" Case (https://www.studocu.com/en-gb/messages/question/5472340/what-are-some-famous-cases-that-were-advised-by-hfw-and-how-were-they-influential)                                                                                                                                                                                       website: https://www.hfw.com/
3                     Clyde & Co       International                                                    12 Marina Boulevard, #30-03 Marina Bay Financial Centre Tower 3, Singapore 018982 (Clydeco.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, Regulatory & Compliance, Real Estate & Construction, Employment & Labor                                                                                                                                                                                                                                                                                                                                                 Urban&Civic, TransactPay, Al Buhaira National Insurance Company (ABNIC), E D & F Man Capital Markets Ltd (MCM), Galliford Try, Welborne Land, Native Land Limited,  Lendlease Group, Citigroup, ThinCats, Community Pharmacy England,  Jaguar Land Rover, Erada Finance,  Pearl Infrastructure capital, Al Bawardi Enterprises, Suez Fortune Investments Ltd                                                                                                                                      The 'Brillante Virtuoso' Case, Precedent setting FOSFA sale of goods arbitration (switzerland), Appealing the Refined Sugar Associations Arbitration Award (UK), Collision of VLCC "ALEXANDRA 1" and "EVER SMART" (UK), Penglai 19-3 Oil Field Pollution (China/USA),  COSCO BUSAN Allision with San Francisco-Oakland Bay Bridge (USA), Agarwal Coal High Court Appeal (UK) (claude + clydeco.com + perplexity)
4             Stephenson Harwood       International  Stephenson Harwood (Singapore) Alliance, 8 Marina Boulevard #29-01, Marina Bay Financial Centre Tower 1, Singapore 018981 (Stephensonharwood.Com)                                                                                                                                                                                                                                                                  Corporate & M&A, Banking & Finance, Dispute Resolution & Litigation, Fraud, Investigations & White Collar, Regulatory & Compliance, Real Estate & Construction, Employment & Labor, Intellectual Property, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, Insurance                                                                                                                                                                                                                                                                                                                                                            Bicycle Therapeutics, Trafigura, WindAcre Partnership, KFin Technologies,  National Bank of Fujairah PJSC, The Arab Energy Fund, Yellow Door Energy, ICICI Bank, BW Group, HSBC, Standard Chartered, ICBC Leasing, PSA International, Mitsui & Co., Olam International, ADM (perplexity + google, from standard chartered till adm by perplexity)                                                                                                                                                                                                         former Yukos Oil Company shareholders v The Russian Federation, Trafigura Pte Ltd & Anor v Prateek Gupta & Ors [2026] EWHC 159 (Comm), SLB and others v PAK and others [2026] EWHC 449 (Comm), GAIL (India) Limited v SEFE Marketing & Trading Singapore Pte Limited, Narciso v Nash (ARB 009/2024) (google AI + google  & news + claude AI )
5       Watson Farley & Williams       International                                                                      88 Market Street #31-05, Capitaspring, Singapore, 048948, Singapore (Wfw.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Corporate & M&A, Banking & Finance, Capital Markets, Dispute Resolution & Litigation, Regulatory & Compliance, Competition & Antitrust                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Cerulean Winds, Vattenfall, HSBC UK, UCED, Maas Capital Shipping, Willow MezzCo, Heytesbury, Trafigura, Shell Energy Europe Limited (SEEL), JE Energy Ltd, BW Energy Holdings Pte Ltd (wfw.com), MRI Trading AG (google AI)                                                                                                                                                   The merger between Hapag-Lloyd and the United Arab Shipping Company (UASC), WFW advises Guinea as US$24bn Simandou African mega-project closes, Niko Resources (Bangladesh) Ltd v. Bangladesh Petroleum Exploration & Production Company Limited ("Bapex") and Bangladesh Oil Gas and Mineral Corporation ("Petrobangla"), MRI Trading AG v Erdenet Mining Corp LLC (2013) (perplexity + google AI)                                                                                                                                                                                                https://www.wfw.com/
6        Ince & Co Singapore LLP       International                                                                                              5 Shenton Way, #19-01, Uic Building, Singapore 068808                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Dispute Resolution & Litigation, Shipping & Maritime, International Trade & Commodities, Energy & Infrastructure, Insurance                                                                                                                                                                                                                                                                                                                                                                  London Commodity Brokers Ltd.(vlex.co.uk),Statoil ASA (gemini), Glory Bulk Carriers Pte Ltd. (hongkongmaritimehub.com),TCC Group (Tai Chong Cheang Shipping) (Google Ai), Seacon Shipping Group Holdings, Mur Shipping B.V.,Stena Bulk / CM P-Max (Gemini), Clearlake Shipping, Trafigura Group (Gemini), Permasteelisa Gartner HK (gemini)                                                                                                                                                                                                                                                                                                                  Global Coal Ltd v London Commodity Brokers (vlex.couk),Statoil ASA v Louis Dreyfus Energy Services LP (The Harriette N)(ipsaloquitur.com ), Priyanka Shipping Limited v Glory Bulk Carriers Pte Ltd [2019] EWHC 2804 (Comm) (Gemini)                                                                                                                                      Rosita Lau (Partner & Head of Shipping), Ince don't have  office in sg(gemini)
7          Norton Rose Fulbright       International                                                       Norton Rose Fulbright (Asia) Llp ,9 Straits Viewmarina One West Tower#09-09 Singapore 018937                                                                                                                                                                                                                                                                                                                 Corporate & M&A, Banking & Finance, Capital Markets, Private Equity & Venture Capital, Dispute Resolution & Litigation, Restructuring & Insolvency, Fraud, Investigations & White Collar, Real Estate & Construction, Employment & Labor, Intellectual Property, Energy & Infrastructure, Private Wealth & Estate Planning                                                                                                                                                                                                                                                                                                                                                                                                                                             Energy Transfer (gemini),Louis Dreyfus Company (LDC) ( gemini), Nippon Yusen Kabushiki Kaisha (NYK Group),  Stena Group, Costamare Inc., P&O Ferries, Carnival Corporation, Dubai Ports World, Roi Tinto, DVB (legal500), P&O North Sea Ferries Ltd (perplexity)                                                                                                     Suez Fortune Investments Ltd v Talbot(gemini), PD Teesport Ltd v. P&O North Sea Ferries Ltd — Force Majeure / Ferry Operator Dispute (2022–2023), Carnival Corporation v. Fincantieri S.p.A — Shipbuilding Contract / Breach of Guarantee (Ongoing as of 2024–2025), Shell UK v. Greenpeace UK — FPSO Boarding Dispute (2023–2024), KfW IPEX-Bank v. World Dream Limited ("The World Dream") — Ship Mortgage Enforcement (2022–2024) (perplexity)
8                 Baker McKenzie       International                                                                        38 Beach Road #23-11 South Beach Tower Singapore 189767 (Bakermckenzie.Com)                                                                                                                                Corporate & M&A, Banking & Finance, Capital Markets, Private Equity & Venture Capital, Funds & Investment Management, Dispute Resolution & Litigation, Restructuring & Insolvency, Fraud, Investigations & White Collar, Regulatory & Compliance, Competition & Antitrust, Real Estate & Construction, Employment & Labor, Intellectual Property, Tax, International Trade & Commodities, Energy & Infrastructure, Private Wealth & Estate Planning, Technology, Data & Cybersecurity, ESG & Sustainability                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Mondelez Global, Veritas,  Olink Holding AB, Pacific Gas & Electric, Physicians Realty Trust, Cummins Inc, Numab Therapeutics, Premier Assurance Group, Acorda, Regent, Vesta Advisors, Shell Singapore Pte. Ltd., Bunge Limited (google ai)                                                                                                                                                                                                                                                                                      Anaklia Development Consortium (ADC) and Bob Meijer v. Georgia (ICC & ICSID parallel claims), Lakatamia Shipping Co Ltd v Su & Ors,  Lehram Capital Investments Ltd v. Baker McKenzie, Anaklia Development Consortium (ADC) v. Government of Georgia (google ai)                                                                                                                                                                                                   bakermckenzie.com

In [50]:
# reset all index again
p2 = p2.reset_index(drop=True)
# save
p2.to_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar2.csv", index=False)